
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 12:06:46 2018


 Enter file name for storing session run (*.run): null.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Data file name: F:\Documentos\Estudio - Documentos\Farmacocinética 2012-1\Bioequivalencia (2018)\Escritura\ADAPT\Modelo_Nulo\data_null.d

 Enter the data file name (*.dat): data_null.dat

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Parameter file name: F:\Documentos\Estudio - Documentos\Farmacocinética 2012-1\Bioequivalencia (2018)\Escritura\ADAPT\Modelo_Nulo\null_parame

 Enter parameter file name (*.prm or *IND.csv):  parameters_null.prm

 Enter parameter file name (*.prm or *IND.csv):  null_parameters.pr

 Enter parameter file name (*.prm or *IND.csv):  null_parameters.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           n
 KA          2.000           y
 V           21.00           n
 F          0.8000           y
 SDinter    0.1000E-01       n
 SDslope    0.1000E-01       y

 Fix non estimated system parameters to subject specific values (Y/N)?  n

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  1

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  2

 Enter number of samples/EM iteration (1000 -   3000):      1000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -41.127    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.501       1.501      0.2223      [  1.494    ,   1.509    ]
 F             0.7998      0.7998      0.6878E-01  [ 0.7985    ,  0.8010    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.111E-04
 F         -.813E-06 0.303E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.20        13.20       -0.1085E-02   0.5426E-03
      3       1.000        18.00        18.00        0.1512E-02   0.7911E-03
      4       1.500        19.00        18.98        0.1522E-01   0.8479E-03
      5       2.000        18.30        18.31       -0.1094E-01   0.8089E-03
      6       3.000        15.40        15.44       -0.4232E-01   0.6529E-03
      7       4.000        12.50        12.47        0.3142E-01   0.5088E-03
      8       6.000        7.920        7.916        0.3647E-02   0.3230E-03
      9       8.000        5.000        5.000        0.2938E-03   0.2261E-03
     10       10.00        3.160        3.156        0.3656E-02   0.1737E-03
     11       12.00        1.990        1.993       -0.2554E-02   0.1442E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.20       0.1748E-01  -0.4600E-01
                3       18.00       0.1542E-01   0.5407E-01
                4       18.98       0.1213E-01   0.5227    
                5       18.31       0.1157E-01  -0.3844    
                6       15.44       0.1208E-01   -1.656    
                7       12.47       0.1094E-01    1.393    
                8       7.916       0.7367E-02   0.2031    
                9       5.000       0.4686E-02   0.1964E-01
               10       3.156       0.2960E-02   0.2775    
               11       1.993       0.1869E-02  -0.2127    

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -39.639    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.502       1.502      0.2193      [  1.494    ,   1.509    ]
 F             0.8238      0.8238      0.6758E-01  [ 0.8225    ,  0.8251    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.108E-04
 F         -.802E-06 0.310E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.60        13.60        0.9196E-03   0.5615E-03
      3       1.000        18.54        18.54       -0.3501E-03   0.8221E-03
      4       1.500        19.57        19.56        0.1426E-01   0.8818E-03
      5       2.000        18.85        18.86       -0.1122E-01   0.8407E-03
      6       3.000        15.86        15.91       -0.4600E-01   0.6770E-03
      7       4.000        12.88        12.84        0.3717E-01   0.5260E-03
      8       6.000        8.160        8.154        0.6073E-02   0.3317E-03
      9       8.000        5.150        5.150        0.2536E-03   0.2306E-03
     10       10.00        3.250        3.251       -0.1065E-02   0.1762E-03
     11       12.00        2.050        2.052       -0.2350E-02   0.1456E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.1782E-01   0.3938E-01
                3       18.54       0.1571E-01  -0.1191E-01
                4       19.56       0.1234E-01   0.4804    
                5       18.86       0.1172E-01  -0.3867    
                6       15.91       0.1222E-01   -1.768    
                7       12.84       0.1106E-01    1.621    
                8       8.154       0.7452E-02   0.3336    
                9       5.150       0.4739E-02   0.1679E-01
               10       3.251       0.2994E-02  -0.8019E-01
               11       2.052       0.1890E-02  -0.1947    

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.243    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.501       1.501      0.2256      [  1.493    ,   1.508    ]
 F             0.7759      0.7759      0.6966E-01  [ 0.7746    ,  0.7771    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.115E-04
 F         -.809E-06 0.292E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        12.80        12.80       -0.1974E-02   0.5241E-03
      3       1.000        17.46        17.46        0.3316E-02   0.7607E-03
      4       1.500        18.43        18.42        0.1488E-01   0.8149E-03
      5       2.000        17.75        17.76       -0.1275E-01   0.7778E-03
      6       3.000        14.94        14.98       -0.4121E-01   0.6294E-03
      7       4.000        12.13        12.10        0.3333E-01   0.4921E-03
      8       6.000        7.680        7.680       -0.3593E-03   0.3145E-03
      9       8.000        4.850        4.851       -0.6700E-03   0.2216E-03
     10       10.00        3.070        3.062        0.7743E-02   0.1712E-03
     11       12.00        1.930        1.933       -0.3158E-02   0.1427E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.80       0.1722E-01  -0.8567E-01
                3       17.46       0.1518E-01   0.1205    
                4       18.42       0.1193E-01   0.5213    
                5       17.76       0.1136E-01  -0.4571    
                6       14.98       0.1187E-01   -1.643    
                7       12.10       0.1075E-01    1.503    
                8       7.680       0.7243E-02  -0.2009E-01
                9       4.851       0.4607E-02  -0.4492E-01
               10       3.062       0.2911E-02   0.5918    
               11       1.933       0.1837E-02  -0.2643    

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -39.991    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.501       1.501      0.2277      [  1.493    ,   1.509    ]
 F             0.7598      0.7598      0.7039E-01  [ 0.7586    ,  0.7611    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.117E-04
 F         -.811E-06 0.286E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        12.54        12.54       -0.1590E-02   0.5121E-03
      3       1.000        17.10        17.10        0.6782E-03   0.7410E-03
      4       1.500        18.05        18.04        0.1366E-01   0.7932E-03
      5       2.000        17.39        17.40       -0.6158E-02   0.7573E-03
      6       3.000        14.63        14.67       -0.4085E-01   0.6138E-03
      7       4.000        11.88        11.85        0.3433E-01   0.4809E-03
      8       6.000        7.520        7.521       -0.8662E-03   0.3089E-03
      9       8.000        4.750        4.750        0.7039E-04   0.2186E-03
     10       10.00        3.000        2.999        0.1341E-02   0.1695E-03
     11       12.00        1.890        1.893       -0.3009E-02   0.1418E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.54       0.1701E-01  -0.6969E-01
                3       17.10       0.1499E-01   0.2522E-01
                4       18.04       0.1179E-01   0.4851    
                5       17.40       0.1124E-01  -0.2236    
                6       14.67       0.1174E-01   -1.649    
                7       11.85       0.1064E-01    1.566    
                8       7.521       0.7167E-02  -0.4912E-01
                9       4.750       0.4558E-02   0.4857E-02
               10       2.999       0.2880E-02   0.1031    
               11       1.893       0.1818E-02  -0.2527    

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -39.005    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.501       1.501      0.2175      [  1.493    ,   1.508    ]
 F             0.8399      0.8399      0.6718E-01  [ 0.8386    ,  0.8412    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.107E-04
 F         -.805E-06 0.318E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.86        13.86       -0.3513E-04   0.5740E-03
      3       1.000        18.90        18.90        0.1112E-02   0.8429E-03
      4       1.500        19.95        19.94        0.1393E-01   0.9047E-03
      5       2.000        19.22        19.23       -0.9519E-02   0.8624E-03
      6       3.000        16.17        16.22       -0.4800E-01   0.6934E-03
      7       4.000        13.13        13.10        0.3477E-01   0.5377E-03
      8       6.000        8.320        8.314        0.5673E-02   0.3376E-03
      9       8.000        5.250        5.251       -0.1061E-02   0.2337E-03
     10       10.00        3.320        3.315        0.4973E-02   0.1779E-03
     11       12.00        2.090        2.093       -0.2728E-02   0.1466E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.86       0.1802E-01  -0.8966E-03
                3       18.90       0.1591E-01   0.3861E-01
                4       19.94       0.1250E-01   0.4632    
                5       19.23       0.1188E-01  -0.3240    
                6       16.22       0.1237E-01   -1.823    
                7       13.10       0.1120E-01    1.500    
                8       8.314       0.7548E-02   0.3089    
                9       5.251       0.4801E-02  -0.6932E-01
               10       3.315       0.3033E-02   0.3729    
               11       2.093       0.1915E-02  -0.2253    

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -37.686    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.502       1.502      0.2150      [  1.495    ,   1.510    ]
 F             0.8636      0.8636      0.6647E-01  [ 0.8623    ,  0.8650    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.43      1.00


  Covariance Matrix

           KA        F         
 KA        0.104E-04
 F         -.806E-06 0.330E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        14.26        14.26        0.3528E-04   0.5935E-03
      3       1.000        19.44        19.44        0.3583E-03   0.8748E-03
      4       1.500        20.52        20.50        0.1707E-01   0.9393E-03
      5       2.000        19.76        19.77       -0.1385E-01   0.8949E-03
      6       3.000        16.63        16.67       -0.4475E-01   0.7179E-03
      7       4.000        13.50        13.46        0.3675E-01   0.5550E-03
      8       6.000        8.550        8.548        0.2268E-02   0.3463E-03
      9       8.000        5.400        5.398        0.1547E-02   0.2383E-03
     10       10.00        3.410        3.408        0.1925E-02   0.1804E-03
     11       12.00        2.150        2.151       -0.1468E-02   0.1480E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       14.26       0.1835E-01   0.2019E-02
                3       19.44       0.1620E-01   0.1241E-01
                4       20.50       0.1274E-01   0.5570    
                5       19.77       0.1210E-01  -0.4628    
                6       16.67       0.1259E-01   -1.670    
                7       13.46       0.1139E-01    1.560    
                8       8.548       0.7669E-02   0.1220    
                9       5.398       0.4877E-02   0.1003    
               10       3.408       0.3081E-02   0.1434    
               11       2.151       0.1945E-02  -0.1206    

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -39.158    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.500       1.501      0.2311      [  1.493    ,   1.508    ]
 F             0.7359      0.7359      0.7138E-01  [ 0.7347    ,  0.7371    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.45      1.00


  Covariance Matrix

           KA        F         
 KA        0.120E-04
 F         -.817E-06 0.276E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        12.14        12.14       -0.2248E-02   0.4941E-03
      3       1.000        16.56        16.56        0.2660E-02   0.7115E-03
      4       1.500        17.48        17.47        0.1340E-01   0.7612E-03
      5       2.000        16.84        16.85       -0.7968E-02   0.7272E-03
      6       3.000        14.17        14.21       -0.3981E-01   0.5910E-03
      7       4.000        11.50        11.47        0.2616E-01   0.4646E-03
      8       6.000        7.290        7.285        0.5071E-02   0.3006E-03
      9       8.000        4.600        4.601       -0.9299E-03   0.2141E-03
     10       10.00        2.910        2.905        0.5405E-02   0.1671E-03
     11       12.00        1.830        1.834       -0.3628E-02   0.1403E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.14       0.1667E-01  -0.1006    
                3       16.56       0.1467E-01   0.1000    
                4       17.47       0.1153E-01   0.4858    
                5       16.85       0.1102E-01  -0.2953    
                6       14.21       0.1155E-01   -1.637    
                7       11.47       0.1046E-01    1.214    
                8       7.285       0.7053E-02   0.2927    
                9       4.601       0.4486E-02  -0.6345E-01
               10       2.905       0.2834E-02   0.4182    
               11       1.834       0.1789E-02  -0.3063    

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.384    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.502       1.502      0.2264      [  1.494    ,   1.509    ]
 F             0.7677      0.7677      0.6987E-01  [ 0.7665    ,  0.7689    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.116E-04
 F         -.810E-06 0.288E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        12.67        12.67       -0.3142E-02   0.5182E-03
      3       1.000        17.28        17.28        0.2156E-02   0.7508E-03
      4       1.500        18.24        18.22        0.1601E-01   0.8039E-03
      5       2.000        17.57        17.58       -0.6701E-02   0.7674E-03
      6       3.000        14.78        14.82       -0.4268E-01   0.6214E-03
      7       4.000        12.00        11.97        0.3188E-01   0.4863E-03
      8       6.000        7.600        7.599        0.1437E-02   0.3116E-03
      9       8.000        4.800        4.799        0.1003E-02   0.2200E-03
     10       10.00        3.030        3.030        0.3652E-03   0.1703E-03
     11       12.00        1.910        1.913       -0.2564E-02   0.1422E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.67       0.1708E-01  -0.1375    
                3       17.28       0.1504E-01   0.7900E-01
                4       18.22       0.1182E-01   0.5647    
                5       17.58       0.1127E-01  -0.2417    
                6       14.82       0.1178E-01   -1.712    
                7       11.97       0.1067E-01    1.446    
                8       7.599       0.7192E-02   0.8158E-01
                9       4.799       0.4574E-02   0.6773E-01
               10       3.030       0.2890E-02   0.2803E-01
               11       1.913       0.1825E-02  -0.2150    

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.303    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.501       1.501      0.2180      [  1.494    ,   1.509    ]
 F             0.8319      0.8319      0.6734E-01  [ 0.8306    ,  0.8332    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.43      1.00


  Covariance Matrix

           KA        F         
 KA        0.107E-04
 F         -.797E-06 0.314E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.73        13.73        0.1059E-02   0.5677E-03
      3       1.000        18.72        18.72        0.9060E-03   0.8324E-03
      4       1.500        19.76        19.75        0.1440E-01   0.8932E-03
      5       2.000        19.03        19.05       -0.1524E-01   0.8515E-03
      6       3.000        16.02        16.06       -0.4205E-01   0.6852E-03
      7       4.000        13.00        12.97        0.3087E-01   0.5318E-03
      8       6.000        8.240        8.234        0.5794E-02   0.3346E-03
      9       8.000        5.200        5.200       -0.4555E-03   0.2322E-03
     10       10.00        3.290        3.283        0.6921E-02   0.1771E-03
     11       12.00        2.070        2.073       -0.2560E-02   0.1461E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.73       0.1791E-01   0.4503E-01
                3       18.72       0.1582E-01   0.3170E-01
                4       19.75       0.1243E-01   0.4820    
                5       19.05       0.1180E-01  -0.5221    
                6       16.06       0.1228E-01   -1.606    
                7       12.97       0.1112E-01    1.339    
                8       8.234       0.7488E-02   0.3169    
                9       5.200       0.4763E-02  -0.2979E-01
               10       3.283       0.3009E-02   0.5202    
               11       2.073       0.1900E-02  -0.2117    

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -36.063    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.504       1.504      0.2202      [  1.497    ,   1.512    ]
 F             0.8223      0.8223      0.6791E-01  [ 0.8210    ,  0.8236    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.110E-04
 F         -.810E-06 0.312E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.58        13.59       -0.9211E-02   0.5610E-03
      3       1.000        18.52        18.52        0.1294E-02   0.8208E-03
      4       1.500        19.55        19.53        0.2348E-01   0.8800E-03
      5       2.000        18.83        18.83        0.1328E-02   0.8388E-03
      6       3.000        15.84        15.87       -0.3438E-01   0.6753E-03
      7       4.000        12.86        12.82        0.4409E-01   0.5247E-03
      8       6.000        8.140        8.136        0.3621E-02   0.3310E-03
      9       8.000        5.130        5.139       -0.8630E-02   0.2303E-03
     10       10.00        3.230        3.244       -0.1404E-01   0.1760E-03
     11       12.00        2.030        2.048       -0.1792E-01   0.1455E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.59       0.1786E-01  -0.3883    
                3       18.52       0.1574E-01   0.4547E-01
                4       19.53       0.1236E-01   0.7915    
                5       18.83       0.1176E-01   0.4602E-01
                6       15.87       0.1226E-01   -1.323    
                7       12.82       0.1109E-01    1.925    
                8       8.136       0.7468E-02   0.1992    
                9       5.139       0.4749E-02  -0.5686    
               10       3.244       0.3001E-02   -1.059    
               11       2.048       0.1894E-02   -1.485    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -36.236    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.503       1.503      0.2173      [  1.496    ,   1.511    ]
 F             0.8384      0.8384      0.6718E-01  [ 0.8371    ,  0.8397    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.107E-04
 F         -.802E-06 0.317E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.84        13.85       -0.1027E-01   0.5735E-03
      3       1.000        18.88        18.88        0.2701E-02   0.8416E-03
      4       1.500        19.93        19.91        0.2316E-01   0.9029E-03
      5       2.000        19.20        19.20        0.3090E-02   0.8604E-03
      6       3.000        16.15        16.19       -0.3628E-01   0.6917E-03
      7       4.000        13.11        13.07        0.4180E-01   0.5364E-03
      8       6.000        8.300        8.297        0.3293E-02   0.3369E-03
      9       8.000        5.230        5.240       -0.9899E-02   0.2334E-03
     10       10.00        3.300        3.308       -0.7977E-02   0.1777E-03
     11       12.00        2.070        2.088       -0.1828E-01   0.1465E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.85       0.1799E-01  -0.4283    
                3       18.88       0.1587E-01   0.9339E-01
                4       19.91       0.1248E-01   0.7708    
                5       19.20       0.1187E-01   0.1055    
                6       16.19       0.1235E-01   -1.379    
                7       13.07       0.1117E-01    1.805    
                8       8.297       0.7524E-02   0.1796    
                9       5.240       0.4785E-02  -0.6478    
               10       3.308       0.3023E-02  -0.5983    
               11       2.088       0.1909E-02   -1.510    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.929    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             1.505       1.505      0.2199      [  1.497    ,   1.512    ]
 F             0.8222      0.8222      0.6767E-01  [ 0.8209    ,  0.8235    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.44      1.00


  Covariance Matrix

           KA        F         
 KA        0.109E-04
 F         -.807E-06 0.310E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        13.58        13.59       -0.1029E-01   0.5611E-03
      3       1.000        18.52        18.52        0.1151E-02   0.8208E-03
      4       1.500        19.55        19.53        0.2436E-01   0.8800E-03
      5       2.000        18.83        18.83        0.2895E-02   0.8387E-03
      6       3.000        15.84        15.87       -0.3238E-01   0.6752E-03
      7       4.000        12.86        12.81        0.4593E-01   0.5246E-03
      8       6.000        8.140        8.135        0.4863E-02   0.3310E-03
      9       8.000        5.130        5.138       -0.7840E-02   0.2303E-03
     10       10.00        3.220        3.244       -0.2355E-01   0.1760E-03
     11       12.00        2.030        2.048       -0.1760E-01   0.1455E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.59       0.1783E-01  -0.4340    
                3       18.52       0.1569E-01   0.4048E-01
                4       19.53       0.1231E-01   0.8215    
                5       18.83       0.1172E-01   0.1001    
                6       15.87       0.1222E-01   -1.246    
                7       12.81       0.1106E-01    2.006    
                8       8.135       0.7446E-02   0.2674    
                9       5.138       0.4736E-02  -0.5166    
               10       3.244       0.2992E-02   -1.775    
               11       2.048       0.1889E-02   -1.459    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -41.862    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.790       2.790      0.3244      [  2.769    ,   2.810    ]
 F             0.7997      0.7997      0.6312E-01  [ 0.7985    ,  0.8008    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.819E-04
 F         -.125E-05 0.255E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        18.70        18.69        0.6073E-02   0.8310E-03
      3       1.000        21.30        21.30        0.2853E-02   0.9890E-03
      4       1.500        20.10        20.13       -0.3230E-01   0.9166E-03
      5       2.000        18.20        18.23       -0.3002E-01   0.8043E-03
      6       3.000        14.60        14.56        0.3521E-01   0.6085E-03
      7       4.000        11.60        11.58        0.2284E-01   0.4691E-03
      8       6.000        7.310        7.309        0.1268E-02   0.3014E-03
      9       8.000        4.610        4.614       -0.3884E-02   0.2145E-03
     10       10.00        2.910        2.913       -0.2670E-02   0.1673E-03
     11       12.00        1.830        1.839       -0.8721E-02   0.1405E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.69       0.2646E-01   0.2115    
                3       21.30       0.1436E-01   0.9093E-01
                4       20.13       0.1267E-01   -1.067    
                5       18.23       0.1283E-01   -1.058    
                6       14.56       0.1102E-01    1.427    
                7       11.58       0.8841E-02    1.055    
                8       7.309       0.5587E-02   0.7313E-01
                9       4.614       0.3527E-02  -0.2651    
               10       2.913       0.2227E-02  -0.2064    
               11       1.839       0.1406E-02  -0.7358    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.879    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.791       2.791      0.3200      [  2.771    ,   2.812    ]
 F             0.8315      0.8315      0.6193E-01  [ 0.8303    ,  0.8327    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.798E-04
 F         -.125E-05 0.265E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        19.45        19.44        0.6079E-02   0.8751E-03
      3       1.000        22.15        22.15        0.2638E-02   0.1044E-02
      4       1.500        20.90        20.93       -0.3415E-01   0.9661E-03
      5       2.000        18.93        18.96       -0.2541E-01   0.8462E-03
      6       3.000        15.18        15.14        0.3594E-01   0.6376E-03
      7       4.000        12.06        12.04        0.2243E-01   0.4894E-03
      8       6.000        7.600        7.599        0.6074E-03   0.3116E-03
      9       8.000        4.790        4.797       -0.7373E-02   0.2200E-03
     10       10.00        3.030        3.029        0.1497E-02   0.1703E-03
     11       12.00        1.900        1.912       -0.1184E-01   0.1422E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.44       0.2715E-01   0.2063    
                3       22.15       0.1469E-01   0.8188E-01
                4       20.93       0.1293E-01   -1.098    
                5       18.96       0.1309E-01  -0.8733    
                6       15.14       0.1125E-01    1.424    
                7       12.04       0.9023E-02    1.014    
                8       7.599       0.5702E-02   0.3451E-01
                9       4.797       0.3600E-02  -0.4971    
               10       3.029       0.2272E-02   0.1147    
               11       1.912       0.1434E-02  -0.9932    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.979    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.788       2.788      0.3299      [  2.767    ,   2.809    ]
 F             0.7678      0.7678      0.6416E-01  [ 0.7667    ,  0.7690    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.846E-04
 F         -.124E-05 0.243E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        17.95        17.94        0.5861E-02   0.7880E-03
      3       1.000        20.45        20.45        0.2972E-02   0.9359E-03
      4       1.500        19.30        19.33       -0.3048E-01   0.8683E-03
      5       2.000        17.47        17.50       -0.3464E-01   0.7634E-03
      6       3.000        14.02        13.99        0.3447E-01   0.5801E-03
      7       4.000        11.14        11.12        0.2326E-01   0.4493E-03
      8       6.000        7.020        7.018        0.1930E-02   0.2913E-03
      9       8.000        4.430        4.430       -0.3937E-03   0.2091E-03
     10       10.00        2.790        2.797       -0.6835E-02   0.1643E-03
     11       12.00        1.760        1.766       -0.5596E-02   0.1387E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.94       0.2585E-01   0.2097    
                3       20.45       0.1404E-01   0.9737E-01
                4       19.33       0.1236E-01   -1.034    
                5       17.50       0.1251E-01   -1.254    
                6       13.99       0.1076E-01    1.432    
                7       11.12       0.8627E-02    1.097    
                8       7.018       0.5452E-02   0.1132    
                9       4.430       0.3442E-02  -0.2716E-01
               10       2.797       0.2173E-02  -0.5333    
               11       1.766       0.1372E-02  -0.4751    

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -39.183    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.789       2.789      0.3357      [  2.767    ,   2.811    ]
 F             0.7357      0.7357      0.6538E-01  [ 0.7346    ,  0.7368    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.28      1.00


  Covariance Matrix

           KA        F         
 KA        0.876E-04
 F         -.127E-05 0.231E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        17.20        17.20        0.3582E-02   0.7463E-03
      3       1.000        19.60        19.59        0.7815E-02   0.8839E-03
      4       1.500        18.49        18.52       -0.3107E-01   0.8210E-03
      5       2.000        16.74        16.77       -0.3122E-01   0.7231E-03
      6       3.000        13.43        13.40        0.3064E-01   0.5520E-03
      7       4.000        10.67        10.65        0.1920E-01   0.4296E-03
      8       6.000        6.730        6.724        0.6087E-02   0.2813E-03
      9       8.000        4.240        4.245       -0.4697E-02   0.2038E-03
     10       10.00        2.680        2.680        0.3919E-03   0.1613E-03
     11       12.00        1.680        1.692       -0.1159E-01   0.1370E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.20       0.2511E-01   0.1320    
                3       19.59       0.1362E-01   0.2631    
                4       18.52       0.1207E-01   -1.084    
                5       16.77       0.1224E-01   -1.161    
                6       13.40       0.1052E-01    1.304    
                7       10.65       0.8440E-02   0.9267    
                8       6.724       0.5334E-02   0.3630    
                9       4.245       0.3367E-02  -0.3290    
               10       2.680       0.2126E-02   0.3089E-01
               11       1.692       0.1342E-02  -0.9905    

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -37.211    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.791       2.791      0.3143      [  2.770    ,   2.811    ]
 F             0.8636      0.8636      0.6107E-01  [ 0.8624    ,  0.8649    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.769E-04
 F         -.125E-05 0.278E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        20.20        20.19        0.7838E-02   0.9202E-03
      3       1.000        23.00        23.00       -0.1486E-02   0.1100E-02
      4       1.500        21.71        21.74       -0.3230E-01   0.1017E-02
      5       2.000        19.66        19.69       -0.2748E-01   0.8897E-03
      6       3.000        15.77        15.73        0.4095E-01   0.6677E-03
      7       4.000        12.53        12.50        0.2742E-01   0.5104E-03
      8       6.000        7.890        7.893       -0.2955E-02   0.3222E-03
      9       8.000        4.980        4.983       -0.2695E-02   0.2255E-03
     10       10.00        3.140        3.145       -0.5494E-02   0.1734E-03
     11       12.00        1.970        1.986       -0.1570E-01   0.1440E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.19       0.2772E-01   0.2592    
                3       23.00       0.1505E-01  -0.4461E-01
                4       21.74       0.1324E-01   -1.012    
                5       19.69       0.1339E-01  -0.9210    
                6       15.73       0.1151E-01    1.585    
                7       12.50       0.9229E-02    1.214    
                8       7.893       0.5832E-02  -0.1645    
                9       4.983       0.3682E-02  -0.1794    
               10       3.145       0.2324E-02  -0.4172    
               11       1.986       0.1467E-02   -1.308    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.360    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.790       2.790      0.3193      [  2.770    ,   2.811    ]
 F             0.8398      0.8398      0.6186E-01  [ 0.8386    ,  0.8410    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.794E-04
 F         -.124E-05 0.270E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        19.64        19.63        0.6016E-02   0.8864E-03
      3       1.000        22.37        22.37        0.3723E-02   0.1058E-02
      4       1.500        21.11        21.14       -0.3214E-01   0.9792E-03
      5       2.000        19.11        19.14       -0.3414E-01   0.8573E-03
      6       3.000        15.33        15.30        0.3500E-01   0.6453E-03
      7       4.000        12.18        12.16        0.2243E-01   0.4948E-03
      8       6.000        7.680        7.675        0.4851E-02   0.3143E-03
      9       8.000        4.840        4.845       -0.5197E-02   0.2214E-03
     10       10.00        3.060        3.059        0.1306E-02   0.1711E-03
     11       12.00        1.920        1.931       -0.1090E-01   0.1427E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.63       0.2741E-01   0.2029    
                3       22.37       0.1486E-01   0.1147    
                4       21.14       0.1304E-01   -1.027    
                5       19.14       0.1319E-01   -1.166    
                6       15.30       0.1133E-01    1.378    
                7       12.16       0.9090E-02    1.008    
                8       7.675       0.5744E-02   0.2737    
                9       4.845       0.3626E-02  -0.3492    
               10       3.059       0.2289E-02   0.9989E-01
               11       1.931       0.1445E-02  -0.9128    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -41.371    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.792       2.792      0.3312      [  2.770    ,   2.813    ]
 F             0.7597      0.7597      0.6425E-01  [ 0.7586    ,  0.7609    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.28      1.00


  Covariance Matrix

           KA        F         
 KA        0.855E-04
 F         -.125E-05 0.238E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        17.77        17.77        0.3942E-02   0.7780E-03
      3       1.000        20.24        20.24        0.4723E-02   0.9229E-03
      4       1.500        19.10        19.13       -0.2639E-01   0.8563E-03
      5       2.000        17.29        17.32       -0.2838E-01   0.7530E-03
      6       3.000        13.87        13.84        0.3388E-01   0.5728E-03
      7       4.000        11.02        11.00        0.2207E-01   0.4442E-03
      8       6.000        6.940        6.943       -0.3056E-02   0.2887E-03
      9       8.000        4.380        4.383       -0.3039E-02   0.2078E-03
     10       10.00        2.760        2.767       -0.6941E-02   0.1635E-03
     11       12.00        1.740        1.747       -0.6724E-02   0.1383E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.77       0.2562E-01   0.1422    
                3       20.24       0.1388E-01   0.1557    
                4       19.13       0.1226E-01  -0.9018    
                5       17.32       0.1241E-01   -1.034    
                6       13.84       0.1067E-01    1.416    
                7       11.00       0.8558E-02    1.047    
                8       6.943       0.5408E-02  -0.1798    
                9       4.383       0.3414E-02  -0.2108    
               10       2.767       0.2155E-02  -0.5428    
               11       1.747       0.1361E-02  -0.5718    

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -40.178    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.789       2.789      0.3213      [  2.768    ,   2.809    ]
 F             0.8237      0.8237      0.6232E-01  [ 0.8225    ,  0.8249    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.803E-04
 F         -.125E-05 0.264E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        19.26        19.25        0.6715E-02   0.8638E-03
      3       1.000        21.94        21.94        0.3437E-02   0.1030E-02
      4       1.500        20.70        20.74       -0.3770E-01   0.9539E-03
      5       2.000        18.75        18.78       -0.2857E-01   0.8359E-03
      6       3.000        15.04        15.00        0.3680E-01   0.6305E-03
      7       4.000        11.95        11.93        0.2435E-01   0.4845E-03
      8       6.000        7.530        7.529        0.1261E-02   0.3091E-03
      9       8.000        4.750        4.753       -0.2771E-02   0.2186E-03
     10       10.00        3.000        3.000       -0.3464E-03   0.1696E-03
     11       12.00        1.880        1.894       -0.1407E-01   0.1418E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.25       0.2701E-01   0.2293    
                3       21.94       0.1464E-01   0.1073    
                4       20.74       0.1288E-01   -1.220    
                5       18.78       0.1304E-01  -0.9881    
                6       15.00       0.1121E-01    1.466    
                7       11.93       0.8993E-02    1.106    
                8       7.529       0.5683E-02   0.7184E-01
                9       4.753       0.3588E-02  -0.1873    
               10       3.000       0.2265E-02  -0.2657E-01
               11       1.894       0.1430E-02   -1.182    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -42.269    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.791       2.791      0.3285      [  2.769    ,   2.812    ]
 F             0.7756      0.7756      0.6388E-01  [ 0.7745    ,  0.7768    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.28      1.00


  Covariance Matrix

           KA        F         
 KA        0.840E-04
 F         -.125E-05 0.245E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        18.14        18.13        0.5366E-02   0.7988E-03
      3       1.000        20.66        20.66        0.2223E-02   0.9489E-03
      4       1.500        19.50        19.53       -0.2693E-01   0.8800E-03
      5       2.000        17.65        17.68       -0.3149E-01   0.7732E-03
      6       3.000        14.16        14.13        0.3360E-01   0.5869E-03
      7       4.000        11.25        11.23        0.2132E-01   0.4540E-03
      8       6.000        7.090        7.089        0.1265E-02   0.2937E-03
      9       8.000        4.470        4.475       -0.5003E-02   0.2104E-03
     10       10.00        2.820        2.825       -0.4996E-02   0.1650E-03
     11       12.00        1.780        1.783       -0.3374E-02   0.1391E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.13       0.2596E-01   0.1907    
                3       20.66       0.1408E-01   0.7238E-01
                4       19.53       0.1244E-01  -0.9076    
                5       17.68       0.1260E-01   -1.132    
                6       14.13       0.1083E-01    1.387    
                7       11.23       0.8683E-02    1.001    
                8       7.089       0.5487E-02   0.7391E-01
                9       4.475       0.3464E-02  -0.3448    
               10       2.825       0.2187E-02  -0.3890    
               11       1.783       0.1381E-02  -0.2860    

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -34.009    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.797       2.797      0.3208      [  2.777    ,   2.818    ]
 F             0.8302      0.8302      0.6206E-01  [ 0.8290    ,  0.8314    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.805E-04
 F         -.125E-05 0.265E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        19.43        19.43       -0.1050E-02   0.8743E-03
      3       1.000        22.13        22.12        0.1192E-01   0.1042E-02
      4       1.500        20.88        20.90       -0.2003E-01   0.9640E-03
      5       2.000        18.91        18.92       -0.1212E-01   0.8443E-03
      6       3.000        15.16        15.12        0.4351E-01   0.6362E-03
      7       4.000        12.04        12.02        0.2443E-01   0.4884E-03
      8       6.000        7.580        7.585       -0.5496E-02   0.3111E-03
      9       8.000        4.770        4.789       -0.1860E-01   0.2197E-03
     10       10.00        3.010        3.023       -0.1297E-01   0.1702E-03
     11       12.00        1.880        1.908       -0.2835E-01   0.1421E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.43       0.2716E-01  -0.3466E-01
                3       22.12       0.1469E-01   0.3695    
                4       20.90       0.1294E-01  -0.6449    
                5       18.92       0.1309E-01  -0.4169    
                6       15.12       0.1125E-01    1.725    
                7       12.02       0.9017E-02    1.105    
                8       7.585       0.5698E-02  -0.3115    
                9       4.789       0.3597E-02   -1.255    
               10       3.023       0.2271E-02  -0.9939    
               11       1.908       0.1434E-02   -2.378    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -28.728    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.797       2.797      0.3160      [  2.776    ,   2.817    ]
 F             0.8623      0.8623      0.6105E-01  [ 0.8611    ,  0.8635    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.27      1.00


  Covariance Matrix

           KA        F         
 KA        0.781E-04
 F         -.125E-05 0.277E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        20.18        20.18        0.6506E-03   0.9195E-03
      3       1.000        22.98        22.97        0.7922E-02   0.1098E-02
      4       1.500        21.69        21.71       -0.1797E-01   0.1015E-02
      5       2.000        19.64        19.65       -0.1396E-01   0.8876E-03
      6       3.000        15.75        15.70        0.4871E-01   0.6663E-03
      7       4.000        12.51        12.48        0.2958E-01   0.5094E-03
      8       6.000        7.870        7.879       -0.8960E-02   0.3217E-03
      9       8.000        4.960        4.974       -0.1386E-01   0.2253E-03
     10       10.00        3.120        3.140       -0.1992E-01   0.1732E-03
     11       12.00        1.950        1.982       -0.3218E-01   0.1439E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.18       0.2782E-01   0.2230E-01
                3       22.97       0.1504E-01   0.2393    
                4       21.71       0.1322E-01  -0.5638    
                5       19.65       0.1337E-01  -0.4684    
                6       15.70       0.1149E-01    1.887    
                7       12.48       0.9210E-02    1.311    
                8       7.879       0.5820E-02  -0.4995    
                9       4.974       0.3674E-02  -0.9234    
               10       3.140       0.2319E-02   -1.513    
               11       1.982       0.1464E-02   -2.682    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.dat

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -34.847    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA             2.794       2.794      0.3310      [  2.773    ,   2.815    ]
 F             0.7665      0.7665      0.6417E-01  [ 0.7654    ,  0.7676    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1007E-02
 SDinter       0.1000E-01   Not estimated


  Correlation Matrix

           KA        F         
 KA          1.00
 F          -0.28      1.00


  Covariance Matrix

           KA        F         
 KA        0.855E-04
 F         -.126E-05 0.242E-06


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-03
      2      0.5000        17.93        17.93       -0.1057E-02   0.7873E-03
      3       1.000        20.43        20.42        0.1195E-01   0.9341E-03
      4       1.500        19.28        19.30       -0.1687E-01   0.8663E-03
      5       2.000        17.45        17.47       -0.2189E-01   0.7615E-03
      6       3.000        14.00        13.96        0.4158E-01   0.5788E-03
      7       4.000        11.12        11.10        0.2489E-01   0.4483E-03
      8       6.000        7.000        7.004       -0.4407E-02   0.2908E-03
      9       8.000        4.410        4.422       -0.1177E-01   0.2089E-03
     10       10.00        2.770        2.791       -0.2139E-01   0.1641E-03
     11       12.00        1.740        1.762       -0.2216E-01   0.1386E-03

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.93       0.2583E-01  -0.3683E-01
                3       20.42       0.1398E-01   0.3913    
                4       19.30       0.1235E-01  -0.5731    
                5       17.47       0.1251E-01  -0.7931    
                6       13.96       0.1075E-01    1.728    
                7       11.10       0.8623E-02    1.176    
                8       7.004       0.5449E-02  -0.2583    
                9       4.422       0.3440E-02  -0.8142    
               10       2.791       0.2172E-02   -1.670    
               11       1.762       0.1371E-02   -1.882    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 12:08:05 2018

 Data file name: data_null.dat

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    1000

 Total number of EM iterations:   30

 Normal distribution option

 -2logLikelihood:   -925.640    

 Model Selection Criteria
  AIC:       -915.640    
  BIC:       -897.761    

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KA           2.15        6.49         0.645        30.0       0.306E+04
  F           0.806        1.13         0.391E-01    4.86        23.7    
  KE          0.230      Not estimated
  V            21.0      Not estimated

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KA        F         
 KA        0.416    
 F          0.00     0.153E-02

  Standard Errors of Estimated Covariance Matrix:

           KA        F         
 KA          25.    
 F          -1.0      0.73E-03

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope     0.101E-02   35.8    
  SDinter     0.100E-01  Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  2) =   2.146687         ! KA        
       Pmean(  4) =  0.8057227         ! F         
 
       Pcov(  2,  2) =  0.4157730      ! KA         & KA        
       Pcov(  4,  2) =   0.000000      ! F          & KA        
       Pcov(  4,  4) =  0.1531013E-02  ! F          & F         

      ________________________________________


 List of Files Created

  Record of program run and all results:
    null.run
  Summary of population estimates at each iteration:
    nullIT.csv
  Individual subject estimates at final iteration:
    nullIND.csv
  Table of predictions and residuals for each subject:
    nullRSD.csv
  Information for plotting model predictions for each subject:
    nullPLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    null.eps
  Command file for subsequent Batch runs:
    null.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 12:08:06 2018

