
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:51:12 2018


 Enter file name for storing session run (*.run): A.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Enter the data file name (*.dat): data_null.csv

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Enter parameter file name (*.prm or *IND.csv):  param_null.pr

 Enter parameter file name (*.prm or *IND.csv):  param_null.pr

 Enter parameter file name (*.prm or *IND.csv):  param_null.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           y
 KA1         2.000           y
 V           21.00           y
 F          0.8000           y
 KA2         2.000           y
 SDinter    0.1000           n
 SDslope    0.1000           y

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  1

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  1

 Enter number of samples/EM iteration (1000 -   3000):      3000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.785    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2287      [ 0.2285    ,  0.2312    ]
 KA1            1.505       1.505      0.4180      [  1.489    ,   1.521    ]
 V              24.67       24.73       3.110      [  22.76    ,   26.71    ]
 F             0.9389      0.9414       3.128      [ 0.8657    ,   1.017    ]
 KA2            2.775       2.783      0.9459      [  2.715    ,   2.850    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.43      1.00
 V           0.24      0.01      1.00
 F           0.27     -0.02      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.276E-06
 KA1       -.143E-05 0.396E-04
 V         0.959E-04 0.566E-04 0.592    
 F         0.414E-05 -.437E-05 0.226E-01 0.867E-03
 KA2       -.372E-05 0.232E-04 0.186E-02 0.637E-04 0.693E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.20        13.22       -0.1507E-01   0.2124E-02
      3       1.000        18.00        18.01       -0.6391E-02   0.7043E-03
      4       1.500        19.00        18.98        0.1529E-01   0.5084E-03
      5       2.000        18.30        18.31       -0.5434E-02   0.6411E-03
      6       3.000        15.40        15.43       -0.3326E-01   0.1372E-02
      7       4.000        12.50        12.46        0.3938E-01   0.2417E-02
      8       6.000        7.920        7.912        0.7573E-02   0.4586E-02
      9       8.000        5.000        4.998        0.1686E-02   0.6337E-02
     10       10.00        3.160        3.156        0.3817E-02   0.7591E-02
     11       12.00        1.990        1.993       -0.2910E-02   0.8440E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.22       0.2539E-01  -0.3283    
                3       18.01       0.1881E-01  -0.2429    
                4       18.98       0.1347E-01   0.6765    
                5       18.31       0.1560E-01  -0.2162    
                6       15.43       0.1950E-01  -0.8992    
                7       12.46       0.1915E-01   0.8004    
                8       7.912       0.1689E-01   0.1116    
                9       4.998       0.1473E-01   0.2104E-01
               10       3.156       0.1223E-01   0.4373E-01
               11       1.993       0.9670E-02  -0.3172E-01

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.396    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2271      [ 0.2285    ,  0.2312    ]
 KA1            1.505       1.505      0.3881      [  1.490    ,   1.520    ]
 V              24.55       24.62       3.104      [  22.66    ,   26.59    ]
 F             0.9625      0.9652       3.122      [ 0.8877    ,   1.043    ]
 KA2            2.774       2.782      0.9484      [  2.714    ,   2.850    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.45      1.00
 V           0.23     -0.00      1.00
 F           0.26     -0.04      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.272E-06
 KA1       -.138E-05 0.341E-04
 V         0.936E-04 -.148E-04 0.584    
 F         0.416E-05 -.651E-05 0.230E-01 0.908E-03
 KA2       -.368E-05 0.221E-04 0.188E-02 0.668E-04 0.696E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.60        13.61       -0.1175E-01   0.1977E-02
      3       1.000        18.54        18.55       -0.7085E-02   0.5921E-03
      4       1.500        19.57        19.55        0.1504E-01   0.4089E-03
      5       2.000        18.85        18.86       -0.5426E-02   0.5325E-03
      6       3.000        15.86        15.90       -0.3718E-01   0.1235E-02
      7       4.000        12.88        12.84        0.4465E-01   0.2269E-02
      8       6.000        8.160        8.151        0.9419E-02   0.4455E-02
      9       8.000        5.150        5.149        0.1117E-02   0.6240E-02
     10       10.00        3.250        3.251       -0.1339E-02   0.7523E-02
     11       12.00        2.050        2.053       -0.3045E-02   0.8395E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.61       0.2392E-01  -0.2655    
                3       18.55       0.1750E-01  -0.2933    
                4       19.55       0.1233E-01   0.7424    
                5       18.86       0.1444E-01  -0.2367    
                6       15.90       0.1829E-01   -1.059    
                7       12.84       0.1821E-01   0.9368    
                8       8.151       0.1663E-01   0.1409    
                9       5.149       0.1480E-01   0.1400E-01
               10       3.251       0.1240E-01  -0.1553E-01
               11       2.053       0.9843E-02  -0.3328E-01

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -28.903    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2298      [ 0.2285    ,  0.2312    ]
 KA1            1.505       1.505      0.4486      [  1.488    ,   1.522    ]
 V              24.76       24.82       3.119      [  22.83    ,   26.81    ]
 F             0.9140      0.9164       3.135      [ 0.8426    ,  0.9903    ]
 KA2            2.776       2.783      0.9461      [  2.716    ,   2.851    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.41      1.00
 V           0.24      0.03      1.00
 F           0.27     -0.01      1.00      1.00
 KA2        -0.27      0.14      0.09      0.09      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.279E-06
 KA1       -.145E-05 0.456E-04
 V         0.971E-04 0.165E-03 0.599    
 F         0.407E-05 -.102E-05 0.222E-01 0.825E-03
 KA2       -.370E-05 0.242E-04 0.194E-02 0.644E-04 0.693E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.80        12.82       -0.1763E-01   0.2276E-02
      3       1.000        17.46        17.47       -0.5497E-02   0.8263E-03
      4       1.500        18.43        18.41        0.1505E-01   0.6186E-03
      5       2.000        17.75        17.76       -0.6420E-02   0.7595E-03
      6       3.000        14.94        14.97       -0.3076E-01   0.1515E-02
      7       4.000        12.13        12.09        0.4266E-01   0.2569E-02
      8       6.000        7.680        7.675        0.4522E-02   0.4718E-02
      9       8.000        4.850        4.849        0.1338E-02   0.6435E-02
     10       10.00        3.070        3.062        0.8297E-02   0.7658E-02
     11       12.00        1.930        1.933       -0.3263E-02   0.8485E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.82       0.2685E-01  -0.3708    
                3       17.47       0.2013E-01  -0.1932    
                4       18.41       0.1460E-01   0.6038    
                5       17.76       0.1672E-01  -0.2345    
                6       14.97       0.2068E-01  -0.7913    
                7       12.09       0.2011E-01   0.8409    
                8       7.675       0.1718E-01   0.6558E-01
                9       4.849       0.1468E-01   0.1654E-01
               10       3.062       0.1206E-01   0.9474E-01
               11       1.933       0.9493E-02  -0.3546E-01

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -27.971    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2311      [ 0.2285    ,  0.2313    ]
 KA1            1.505       1.505      0.4708      [  1.487    ,   1.523    ]
 V              24.82       24.88       3.121      [  22.88    ,   26.88    ]
 F             0.8975      0.8997       3.137      [ 0.8271    ,  0.9723    ]
 KA2            2.777       2.784      0.9488      [  2.716    ,   2.852    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.39      1.00
 V           0.24      0.04      1.00
 F           0.27      0.00      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.282E-06
 KA1       -.149E-05 0.502E-04
 V         0.990E-04 0.230E-03 0.603    
 F         0.407E-05 0.790E-06 0.219E-01 0.797E-03
 KA2       -.382E-05 0.255E-04 0.193E-02 0.625E-04 0.698E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.54        12.56       -0.1529E-01   0.2379E-02
      3       1.000        17.10        17.11       -0.7451E-02   0.9124E-03
      4       1.500        18.05        18.04        0.1305E-01   0.6977E-03
      5       2.000        17.39        17.39       -0.1578E-02   0.8438E-03
      6       3.000        14.63        14.66       -0.3272E-01   0.1614E-02
      7       4.000        11.88        11.84        0.4160E-01   0.2673E-02
      8       6.000        7.520        7.517        0.2824E-02   0.4807E-02
      9       8.000        4.750        4.749        0.1467E-02   0.6501E-02
     10       10.00        3.000        2.998        0.1604E-02   0.7703E-02
     11       12.00        1.890        1.893       -0.3238E-02   0.8515E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.56       0.2787E-01  -0.3149    
                3       17.11       0.2104E-01  -0.2486    
                4       18.04       0.1533E-01   0.4926    
                5       17.39       0.1743E-01  -0.5578E-01
                6       14.66       0.2141E-01  -0.8155    
                7       11.84       0.2070E-01   0.8039    
                8       7.517       0.1737E-01   0.4047E-01
                9       4.749       0.1465E-01   0.1806E-01
               10       2.998       0.1196E-01   0.1820E-01
               11       1.893       0.9388E-02  -0.3514E-01

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -28.944    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2259      [ 0.2285    ,  0.2312    ]
 KA1            1.504       1.504      0.3675      [  1.490    ,   1.519    ]
 V              24.45       24.53       3.105      [  22.57    ,   26.48    ]
 F             0.9775      0.9803       3.122      [ 0.9016    ,   1.059    ]
 KA2            2.773       2.781      0.9481      [  2.713    ,   2.849    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.47      1.00
 V           0.23     -0.01      1.00
 F           0.26     -0.05      1.00      1.00
 KA2        -0.27      0.15      0.09      0.09      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.270E-06
 KA1       -.135E-05 0.306E-04
 V         0.926E-04 -.607E-04 0.580    
 F         0.419E-05 -.795E-05 0.233E-01 0.937E-03
 KA2       -.364E-05 0.213E-04 0.190E-02 0.691E-04 0.695E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.86        13.87       -0.1353E-01   0.1884E-02
      3       1.000        18.90        18.91       -0.6394E-02   0.5229E-03
      4       1.500        19.95        19.94        0.1417E-01   0.3485E-03
      5       2.000        19.22        19.22       -0.4056E-02   0.4653E-03
      6       3.000        16.17        16.21       -0.3928E-01   0.1147E-02
      7       4.000        13.13        13.09        0.4225E-01   0.2172E-02
      8       6.000        8.320        8.311        0.9027E-02   0.4368E-02
      9       8.000        5.250        5.250       -0.1952E-03   0.6175E-02
     10       10.00        3.320        3.315        0.4698E-02   0.7478E-02
     11       12.00        2.090        2.093       -0.3425E-02   0.8365E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.87       0.2283E-01  -0.3128    
                3       18.91       0.1659E-01  -0.2818    
                4       19.94       0.1156E-01   0.7576    
                5       19.22       0.1363E-01  -0.1896    
                6       16.21       0.1742E-01   -1.161    
                7       13.09       0.1753E-01   0.9059    
                8       8.311       0.1645E-01   0.1363    
                9       5.250       0.1485E-01  -0.2629E-02
               10       3.315       0.1251E-01   0.5424E-01
               11       2.093       0.9958E-02  -0.3750E-01

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -27.140    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2236      [ 0.2285    ,  0.2312    ]
 KA1            1.506       1.506      0.3394      [  1.492    ,   1.519    ]
 V              24.33       24.41       3.098      [  22.46    ,   26.35    ]
 F              1.000       1.003       3.116      [ 0.9228    ,   1.084    ]
 KA2            2.772       2.780      0.9451      [  2.712    ,   2.848    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.50      1.00
 V           0.23     -0.03      1.00
 F           0.26     -0.06      1.00      1.00
 KA2        -0.26      0.15      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.264E-06
 KA1       -.130E-05 0.261E-04
 V         0.903E-04 -.114E-03 0.572    
 F         0.419E-05 -.970E-05 0.236E-01 0.977E-03
 KA2       -.357E-05 0.200E-04 0.180E-02 0.672E-04 0.690E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        14.26        14.27       -0.1392E-01   0.1744E-02
      3       1.000        19.44        19.45       -0.7704E-02   0.4268E-03
      4       1.500        20.52        20.50        0.1675E-01   0.2674E-03
      5       2.000        19.76        19.77       -0.8933E-02   0.3744E-03
      6       3.000        16.63        16.67       -0.3657E-01   0.1024E-02
      7       4.000        13.50        13.46        0.4368E-01   0.2034E-02
      8       6.000        8.550        8.545        0.5113E-02   0.4243E-02
      9       8.000        5.400        5.398        0.1986E-02   0.6081E-02
     10       10.00        3.410        3.409        0.1313E-02   0.7412E-02
     11       12.00        2.150        2.152       -0.2420E-02   0.8321E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       14.27       0.2123E-01  -0.3344    
                3       19.45       0.1516E-01  -0.3751    
                4       20.50       0.1040E-01    1.023    
                5       19.77       0.1250E-01  -0.4634    
                6       16.67       0.1625E-01   -1.144    
                7       13.46       0.1665E-01   0.9679    
                8       8.545       0.1625E-01   0.7824E-01
                9       5.398       0.1494E-01   0.2532E-01
               10       3.409       0.1267E-01   0.1516E-01
               11       2.152       0.1011E-01  -0.2658E-01

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -25.882    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2325      [ 0.2285    ,  0.2313    ]
 KA1            1.505       1.505      0.5045      [  1.486    ,   1.525    ]
 V              24.88       24.94       3.137      [  22.93    ,   26.95    ]
 F             0.8713      0.8734       3.152      [ 0.8026    ,  0.9442    ]
 KA2            2.778       2.785      0.9471      [  2.717    ,   2.853    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.37      1.00
 V           0.24      0.06      1.00
 F           0.27      0.02      1.00      1.00
 KA2        -0.27      0.13      0.10      0.09      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.286E-06
 KA1       -.151E-05 0.577E-04
 V         0.101E-03 0.365E-03 0.612    
 F         0.401E-05 0.460E-05 0.215E-01 0.758E-03
 KA2       -.381E-05 0.265E-04 0.201E-02 0.634E-04 0.696E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.14        12.16       -0.1928E-01   0.2540E-02
      3       1.000        16.56        16.57       -0.7324E-02   0.1050E-02
      4       1.500        17.48        17.47        0.1291E-01   0.8259E-03
      5       2.000        16.84        16.84       -0.1862E-02   0.9791E-03
      6       3.000        14.17        14.20       -0.2908E-01   0.1770E-02
      7       4.000        11.50        11.46        0.3594E-01   0.2833E-02
      8       6.000        7.290        7.280        0.1044E-01   0.4942E-02
      9       8.000        4.600        4.599        0.1498E-02   0.6600E-02
     10       10.00        2.910        2.904        0.6294E-02   0.7771E-02
     11       12.00        1.830        1.833       -0.3478E-02   0.8560E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.16       0.2926E-01  -0.3839    
                3       16.57       0.2229E-01  -0.2279    
                4       17.47       0.1640E-01   0.4479    
                5       16.84       0.1850E-01  -0.6094E-01
                6       14.20       0.2255E-01  -0.6924    
                7       11.46       0.2164E-01   0.6745    
                8       7.280       0.1770E-01   0.1483    
                9       4.599       0.1463E-01   0.1831E-01
               10       2.904       0.1182E-01   0.7132E-01
               11       1.833       0.9223E-02  -0.3763E-01

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -28.445    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2304      [ 0.2285    ,  0.2313    ]
 KA1            1.505       1.506      0.4603      [  1.488    ,   1.523    ]
 V              24.80       24.87       3.115      [  22.87    ,   26.86    ]
 F             0.9063      0.9085       3.131      [ 0.8354    ,  0.9817    ]
 KA2            2.776       2.784      0.9496      [  2.716    ,   2.852    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.40      1.00
 V           0.24      0.04      1.00
 F           0.27     -0.00      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.281E-06
 KA1       -.147E-05 0.480E-04
 V         0.971E-04 0.195E-03 0.600    
 F         0.403E-05 -.199E-06 0.220E-01 0.809E-03
 KA2       -.378E-05 0.255E-04 0.190E-02 0.620E-04 0.699E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.67        12.69       -0.1799E-01   0.2327E-02
      3       1.000        17.28        17.29       -0.6971E-02   0.8687E-03
      4       1.500        18.24        18.23        0.1478E-01   0.6577E-03
      5       2.000        17.57        17.57       -0.2402E-02   0.8014E-03
      6       3.000        14.78        14.81       -0.3448E-01   0.1565E-02
      7       4.000        12.00        11.96        0.3933E-01   0.2622E-02
      8       6.000        7.600        7.595        0.5315E-02   0.4763E-02
      9       8.000        4.800        4.797        0.2548E-02   0.6469E-02
     10       10.00        3.030        3.029        0.7382E-03   0.7681E-02
     11       12.00        1.910        1.913       -0.2713E-02   0.8500E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.69       0.2742E-01  -0.3742    
                3       17.29       0.2064E-01  -0.2385    
                4       18.23       0.1499E-01   0.5751    
                5       17.57       0.1708E-01  -0.8635E-01
                6       14.81       0.2104E-01  -0.8727    
                7       11.96       0.2039E-01   0.7675    
                8       7.595       0.1726E-01   0.7676E-01
                9       4.797       0.1465E-01   0.3154E-01
               10       3.029       0.1200E-01   0.8346E-02
               11       1.913       0.9433E-02  -0.2947E-01

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.563    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.2261      [ 0.2285    ,  0.2312    ]
 KA1            1.505       1.505      0.3772      [  1.490    ,   1.520    ]
 V              24.50       24.57       3.103      [  22.61    ,   26.54    ]
 F             0.9699      0.9727       3.121      [ 0.8947    ,   1.051    ]
 KA2            2.774       2.782      0.9461      [  2.714    ,   2.849    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.46      1.00
 V           0.24     -0.01      1.00
 F           0.26     -0.04      1.00      1.00
 KA2        -0.27      0.14      0.10      0.09      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.270E-06
 KA1       -.136E-05 0.322E-04
 V         0.932E-04 -.373E-04 0.582    
 F         0.417E-05 -.719E-05 0.231E-01 0.921E-03
 KA2       -.364E-05 0.215E-04 0.191E-02 0.686E-04 0.693E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.73        13.74       -0.1301E-01   0.1930E-02
      3       1.000        18.72        18.73       -0.6343E-02   0.5571E-03
      4       1.500        19.76        19.74        0.1570E-01   0.3783E-03
      5       2.000        19.03        19.04       -0.8258E-02   0.4986E-03
      6       3.000        16.02        16.05       -0.3165E-01   0.1191E-02
      7       4.000        13.00        12.96        0.3976E-01   0.2221E-02
      8       6.000        8.240        8.230        0.9932E-02   0.4412E-02
      9       8.000        5.200        5.199        0.8005E-03   0.6208E-02
     10       10.00        3.290        3.283        0.6823E-02   0.7501E-02
     11       12.00        2.070        2.073       -0.3189E-02   0.8380E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.74       0.2333E-01  -0.2973    
                3       18.73       0.1701E-01  -0.2709    
                4       19.74       0.1195E-01   0.8056    
                5       19.04       0.1406E-01  -0.3715    
                6       16.05       0.1789E-01  -0.9180    
                7       12.96       0.1790E-01   0.8431    
                8       8.230       0.1655E-01   0.1493    
                9       5.199       0.1483E-01   0.1002E-01
               10       3.283       0.1245E-01   0.7870E-01
               11       2.073       0.9893E-02  -0.3488E-01

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.234    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2300      0.2299      0.2274      [ 0.2286    ,  0.2313    ]
 KA1            1.505       1.505      0.3885      [  1.490    ,   1.520    ]
 V              24.59       24.66       3.104      [  22.69    ,   26.62    ]
 F             0.9631      0.9656       3.121      [ 0.8881    ,   1.043    ]
 KA2            2.773       2.781      0.9462      [  2.713    ,   2.849    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.45      1.00
 V           0.24     -0.00      1.00
 F           0.27     -0.04      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.273E-06
 KA1       -.139E-05 0.342E-04
 V         0.951E-04 -.173E-04 0.586    
 F         0.421E-05 -.663E-05 0.230E-01 0.908E-03
 KA2       -.366E-05 0.218E-04 0.179E-02 0.631E-04 0.692E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1752E-01   0.1983E-02
      3       1.000        18.52        18.53       -0.7227E-02   0.5961E-03
      4       1.500        19.55        19.53        0.1653E-01   0.4125E-03
      5       2.000        18.83        18.83       -0.4126E-02   0.5365E-03
      6       3.000        15.84        15.88       -0.3815E-01   0.1241E-02
      7       4.000        12.86        12.82        0.4093E-01   0.2275E-02
      8       6.000        8.140        8.139        0.9621E-03   0.4462E-02
      9       8.000        5.130        5.141       -0.1082E-01   0.6245E-02
     10       10.00        3.230        3.246       -0.1577E-01   0.7527E-02
     11       12.00        2.030        2.049       -0.1922E-01   0.8398E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.2392E-01  -0.3946    
                3       18.53       0.1753E-01  -0.2981    
                4       19.53       0.1237E-01   0.8124    
                5       18.83       0.1447E-01  -0.1797    
                6       15.88       0.1830E-01   -1.084    
                7       12.82       0.1821E-01   0.8575    
                8       8.139       0.1663E-01   0.1415E-01
                9       5.141       0.1480E-01  -0.1371    
               10       3.246       0.1239E-01  -0.1818    
               11       2.049       0.9840E-02  -0.2098    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -28.767    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2300      0.2300      0.2253      [ 0.2286    ,  0.2313    ]
 KA1            1.504       1.504      0.3688      [  1.490    ,   1.519    ]
 V              24.50       24.56       3.099      [  22.61    ,   26.52    ]
 F             0.9783      0.9808       3.116      [ 0.9022    ,   1.059    ]
 KA2            2.772       2.780      0.9472      [  2.712    ,   2.848    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.47      1.00
 V           0.23     -0.01      1.00
 F           0.26     -0.05      1.00      1.00
 KA2        -0.27      0.15      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.268E-06
 KA1       -.135E-05 0.308E-04
 V         0.921E-04 -.529E-04 0.579    
 F         0.416E-05 -.768E-05 0.232E-01 0.934E-03
 KA2       -.363E-05 0.213E-04 0.185E-02 0.671E-04 0.693E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.84        13.86       -0.1923E-01   0.1889E-02
      3       1.000        18.88        18.89       -0.6559E-02   0.5266E-03
      4       1.500        19.93        19.91        0.1556E-01   0.3517E-03
      5       2.000        19.20        19.20       -0.2892E-02   0.4691E-03
      6       3.000        16.15        16.19       -0.4038E-01   0.1152E-02
      7       4.000        13.11        13.07        0.3845E-01   0.2178E-02
      8       6.000        8.300        8.299        0.5703E-03   0.4375E-02
      9       8.000        5.230        5.242       -0.1210E-01   0.6180E-02
     10       10.00        3.300        3.310       -0.9680E-02   0.7482E-02
     11       12.00        2.070        2.090       -0.1955E-01   0.8368E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.86       0.2287E-01  -0.4436    
                3       18.89       0.1660E-01  -0.2879    
                4       19.91       0.1160E-01   0.8281    
                5       19.20       0.1372E-01  -0.1352    
                6       16.19       0.1753E-01   -1.191    
                7       13.07       0.1762E-01   0.8232    
                8       8.299       0.1646E-01   0.8370E-02
                9       5.242       0.1482E-01  -0.1540    
               10       3.310       0.1247E-01  -0.1120    
               11       2.090       0.9922E-02  -0.2138    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.180    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2300      0.2300      0.2273      [ 0.2286    ,  0.2313    ]
 KA1            1.505       1.505      0.3884      [  1.490    ,   1.520    ]
 V              24.59       24.66       3.104      [  22.69    ,   26.63    ]
 F             0.9633      0.9658       3.122      [ 0.8882    ,   1.043    ]
 KA2            2.773       2.781      0.9471      [  2.713    ,   2.848    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.45      1.00
 V           0.24     -0.00      1.00
 F           0.27     -0.04      1.00      1.00
 KA2        -0.27      0.14      0.09      0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.273E-06
 KA1       -.139E-05 0.342E-04
 V         0.944E-04 -.135E-04 0.586    
 F         0.418E-05 -.648E-05 0.231E-01 0.909E-03
 KA2       -.367E-05 0.221E-04 0.183E-02 0.646E-04 0.694E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1751E-01   0.1983E-02
      3       1.000        18.52        18.53       -0.7221E-02   0.5961E-03
      4       1.500        19.55        19.53        0.1655E-01   0.4125E-03
      5       2.000        18.83        18.83       -0.4070E-02   0.5365E-03
      6       3.000        15.84        15.88       -0.3803E-01   0.1241E-02
      7       4.000        12.86        12.82        0.4112E-01   0.2276E-02
      8       6.000        8.140        8.139        0.1192E-02   0.4462E-02
      9       8.000        5.130        5.141       -0.1060E-01   0.6245E-02
     10       10.00        3.220        3.246       -0.2558E-01   0.7527E-02
     11       12.00        2.030        2.049       -0.1907E-01   0.8398E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.2393E-01  -0.3945    
                3       18.53       0.1754E-01  -0.2979    
                4       19.53       0.1239E-01   0.8136    
                5       18.83       0.1448E-01  -0.1773    
                6       15.88       0.1831E-01   -1.081    
                7       12.82       0.1822E-01   0.8614    
                8       8.139       0.1663E-01   0.1760E-01
                9       5.141       0.1480E-01  -0.1343    
               10       3.246       0.1239E-01  -0.2949    
               11       2.049       0.9838E-02  -0.2082    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.990    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.2088      [ 0.2286    ,  0.2311    ]
 KA1            1.582       1.574       2.104      [  1.489    ,   1.659    ]
 V              26.28       26.29      0.8366E-01  [  26.23    ,   26.34    ]
 F             0.9538      0.9579       4.700      [ 0.8421    ,   1.074    ]
 KA2            2.800       2.800      0.3251      [  2.777    ,   2.823    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.24      1.00
 V          -0.75      0.19      1.00
 F           0.09     -0.31     -0.07      1.00
 KA2        -0.47      0.13      0.71     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.230E-06
 KA1       -.379E-05 0.110E-02
 V         -.793E-05 0.142E-03 0.484E-03
 F         0.186E-05 -.468E-03 -.670E-04 0.203E-02
 KA2       -.207E-05 0.401E-04 0.142E-03 -.199E-04 0.829E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.70        18.71       -0.7836E-02   0.5606E-03
      3       1.000        21.30        21.29        0.9533E-02   0.1727E-03
      4       1.500        20.10        20.12       -0.1702E-01   0.3214E-03
      5       2.000        18.20        18.21       -0.1382E-01   0.6601E-03
      6       3.000        14.60        14.55        0.4717E-01   0.1651E-02
      7       4.000        11.60        11.57        0.3042E-01   0.2788E-02
      8       6.000        7.310        7.307        0.3438E-02   0.4927E-02
      9       8.000        4.610        4.614       -0.4177E-02   0.6589E-02
     10       10.00        2.910        2.914       -0.3907E-02   0.7764E-02
     11       12.00        1.830        1.840       -0.1017E-01   0.8555E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.71       0.1980E-01  -0.3338    
                3       21.29       0.9601E-02   0.7233    
                4       20.12       0.1116E-01  -0.9510    
                5       18.21       0.1212E-01  -0.5386    
                6       14.55       0.1278E-01    1.161    
                7       11.57       0.1405E-01   0.5759    
                8       7.307       0.1507E-01   0.4880E-01
                9       4.614       0.1374E-01  -0.5157E-01
               10       2.914       0.1141E-01  -0.4441E-01
               11       1.840       0.8947E-02  -0.1100    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.741    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.2037      [ 0.2285    ,  0.2309    ]
 KA1            1.546       1.541       2.143      [  1.456    ,   1.626    ]
 V              25.28       25.28      0.7341E-01  [  25.23    ,   25.33    ]
 F             0.9426      0.9453       4.762      [ 0.8296    ,   1.061    ]
 KA2            2.802       2.802      0.2811      [  2.782    ,   2.823    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.80      0.20      1.00
 F           0.08     -0.32     -0.07      1.00
 KA2        -0.51      0.14      0.75     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.219E-06
 KA1       -.360E-05 0.109E-02
 V         -.696E-05 0.121E-03 0.344E-03
 F         0.175E-05 -.472E-03 -.564E-04 0.203E-02
 KA2       -.189E-05 0.354E-04 0.109E-03 -.174E-04 0.620E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.45        19.46       -0.9919E-02   0.4247E-03
      3       1.000        22.15        22.14        0.8882E-02   0.9352E-04
      4       1.500        20.90        20.92       -0.1895E-01   0.2148E-03
      5       2.000        18.93        18.94       -0.9684E-02   0.5167E-03
      6       3.000        15.18        15.13        0.4630E-01   0.1464E-02
      7       4.000        12.06        12.03        0.2763E-01   0.2592E-02
      8       6.000        7.600        7.600       -0.1440E-03   0.4760E-02
      9       8.000        4.790        4.800       -0.1041E-01   0.6467E-02
     10       10.00        3.030        3.032       -0.2038E-02   0.7679E-02
     11       12.00        1.900        1.915       -0.1510E-01   0.8498E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.46       0.1708E-01  -0.4841    
                3       22.14       0.7577E-02   0.9160    
                4       20.92       0.9215E-02   -1.295    
                5       18.94       0.1035E-01  -0.4269    
                6       15.13       0.1188E-01    1.210    
                7       12.03       0.1378E-01   0.5423    
                8       7.600       0.1522E-01  -0.2285E-02
                9       4.800       0.1396E-01  -0.1295    
               10       3.032       0.1161E-01  -0.2333E-01
               11       1.915       0.9109E-02  -0.1638    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.221    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2300      0.2299      0.2131      [ 0.2287    ,  0.2312    ]
 KA1            1.621       1.610       2.062      [  1.524    ,   1.695    ]
 V              27.37       27.37      0.9469E-01  [  27.31    ,   27.44    ]
 F             0.9662      0.9714       4.630      [ 0.8558    ,   1.087    ]
 KA2            2.797       2.798      0.3707      [  2.771    ,   2.825    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.71      0.19      1.00
 F           0.09     -0.31     -0.06      1.00
 KA2        -0.45      0.13      0.68     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.240E-06
 KA1       -.399E-05 0.110E-02
 V         -.900E-05 0.165E-03 0.672E-03
 F         0.194E-05 -.470E-03 -.743E-04 0.202E-02
 KA2       -.229E-05 0.455E-04 0.183E-03 -.224E-04 0.108E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.95        17.96       -0.7817E-02   0.7149E-03
      3       1.000        20.45        20.44        0.9406E-02   0.2758E-03
      4       1.500        19.30        19.32       -0.1506E-01   0.4494E-03
      5       2.000        17.47        17.49       -0.1758E-01   0.8212E-03
      6       3.000        14.02        13.97        0.4862E-01   0.1849E-02
      7       4.000        11.14        11.11        0.3384E-01   0.2991E-02
      8       6.000        7.020        7.012        0.7607E-02   0.5097E-02
      9       8.000        4.430        4.427        0.2545E-02   0.6714E-02
     10       10.00        2.790        2.795       -0.5389E-02   0.7849E-02
     11       12.00        1.760        1.765       -0.4944E-02   0.8612E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.96       0.2233E-01  -0.2952    
                3       20.44       0.1150E-01   0.5644    
                4       19.32       0.1302E-01  -0.7121    
                5       17.49       0.1382E-01  -0.6143    
                6       13.97       0.1369E-01    1.130    
                7       11.11       0.1430E-01   0.6185    
                8       7.012       0.1484E-01   0.1064    
                9       4.427       0.1344E-01   0.3096E-01
               10       2.795       0.1114E-01  -0.6089E-01
               11       1.765       0.8727E-02  -0.5331E-01

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -26.559    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2302      0.2301      0.2164      [ 0.2288    ,  0.2313    ]
 KA1            1.663       1.648       2.013      [  1.563    ,   1.734    ]
 V              28.56       28.56      0.1057      [  28.49    ,   28.64    ]
 F             0.9799      0.9862       4.572      [ 0.8702    ,   1.102    ]
 KA2            2.797       2.798      0.4155      [  2.769    ,   2.828    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.67      0.19      1.00
 F           0.09     -0.32     -0.06      1.00
 KA2        -0.43      0.14      0.65     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.248E-06
 KA1       -.417E-05 0.110E-02
 V         -.100E-04 0.194E-03 0.912E-03
 F         0.202E-05 -.475E-03 -.830E-04 0.203E-02
 KA2       -.248E-05 0.525E-04 0.228E-03 -.252E-04 0.135E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.20        17.21       -0.1104E-01   0.8871E-03
      3       1.000        19.60        19.59        0.1170E-01   0.4034E-03
      4       1.500        18.49        18.51       -0.1803E-01   0.5999E-03
      5       2.000        16.74        16.76       -0.1562E-01   0.1001E-02
      6       3.000        13.43        13.38        0.4528E-01   0.2061E-02
      7       4.000        10.67        10.64        0.3164E-01   0.3203E-02
      8       6.000        6.730        6.715        0.1480E-01   0.5271E-02
      9       8.000        4.240        4.239        0.1337E-02   0.6841E-02
     10       10.00        2.680        2.675        0.4536E-02   0.7936E-02
     11       12.00        1.680        1.689       -0.8767E-02   0.8670E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.21       0.2469E-01  -0.3735    
                3       19.59       0.1334E-01   0.5808    
                4       18.51       0.1475E-01  -0.7377    
                5       16.76       0.1543E-01  -0.4945    
                6       13.38       0.1464E-01   0.9970    
                7       10.64       0.1464E-01   0.5588    
                8       6.715       0.1463E-01   0.2037    
                9       4.239       0.1312E-01   0.1606E-01
               10       2.675       0.1083E-01   0.5086E-01
               11       1.689       0.8476E-02  -0.9419E-01

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.703    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2296      0.2296      0.1970      [ 0.2285    ,  0.2308    ]
 KA1            1.513       1.510       2.181      [  1.425    ,   1.595    ]
 V              24.35       24.34      0.6317E-01  [  24.31    ,   24.38    ]
 F             0.9320      0.9338       4.819      [ 0.8181    ,   1.050    ]
 KA2            2.803       2.803      0.2373      [  2.786    ,   2.820    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.22      1.00
 V          -0.85      0.20      1.00
 F           0.08     -0.31     -0.07      1.00
 KA2        -0.56      0.14      0.79     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.205E-06
 KA1       -.332E-05 0.108E-02
 V         -.593E-05 0.100E-03 0.236E-03
 F         0.162E-05 -.465E-03 -.472E-04 0.203E-02
 KA2       -.168E-05 0.301E-04 0.812E-04 -.144E-04 0.442E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.20        20.21       -0.1098E-01   0.3078E-03
      3       1.000        23.00        22.99        0.5277E-02   0.3829E-04
      4       1.500        21.71        21.73       -0.1553E-01   0.1292E-03
      5       2.000        19.66        19.67       -0.1048E-01   0.3901E-03
      6       3.000        15.77        15.72        0.5113E-01   0.1287E-02
      7       4.000        12.53        12.50        0.3130E-01   0.2402E-02
      8       6.000        7.890        7.896       -0.6065E-02   0.4595E-02
      9       8.000        4.980        4.988       -0.8182E-02   0.6344E-02
     10       10.00        3.140        3.151       -0.1119E-01   0.7594E-02
     11       12.00        1.970        1.991       -0.2070E-01   0.8442E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.21       0.1412E-01  -0.6282    
                3       22.99       0.5290E-02   0.8497    
                4       21.73       0.7153E-02   -1.368    
                5       19.67       0.8580E-02  -0.5315    
                6       15.72       0.1112E-01    1.425    
                7       12.50       0.1358E-01   0.6383    
                8       7.896       0.1533E-01  -0.8967E-01
                9       4.988       0.1410E-01  -0.1028    
               10       3.151       0.1173E-01  -0.1284    
               11       1.991       0.9199E-02  -0.2254    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.119    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2297      0.2021      [ 0.2286    ,  0.2309    ]
 KA1            1.537       1.532       2.158      [  1.447    ,   1.617    ]
 V              25.03       25.03      0.7062E-01  [  24.99    ,   25.08    ]
 F             0.9400      0.9426       4.781      [ 0.8267    ,   1.058    ]
 KA2            2.802       2.802      0.2693      [  2.783    ,   2.822    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.81      0.20      1.00
 F           0.08     -0.32     -0.07      1.00
 KA2        -0.52      0.13      0.76     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.216E-06
 KA1       -.352E-05 0.109E-02
 V         -.667E-05 0.116E-03 0.313E-03
 F         0.177E-05 -.473E-03 -.569E-04 0.203E-02
 KA2       -.182E-05 0.336E-04 0.101E-03 -.172E-04 0.569E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.64        19.65       -0.1279E-01   0.3929E-03
      3       1.000        22.37        22.36        0.9043E-02   0.7698E-04
      4       1.500        21.11        21.13       -0.1677E-01   0.1907E-03
      5       2.000        19.11        19.13       -0.1781E-01   0.4824E-03
      6       3.000        15.33        15.28        0.4613E-01   0.1417E-02
      7       4.000        12.18        12.15        0.2836E-01   0.2543E-02
      8       6.000        7.680        7.675        0.4705E-02   0.4718E-02
      9       8.000        4.840        4.848       -0.7761E-02   0.6436E-02
     10       10.00        3.060        3.062       -0.1876E-02   0.7658E-02
     11       12.00        1.920        1.934       -0.1390E-01   0.8484E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.65       0.1634E-01  -0.6478    
                3       22.36       0.7012E-02    1.028    
                4       21.13       0.8686E-02   -1.216    
                5       19.13       0.9895E-02  -0.8115    
                6       15.28       0.1170E-01    1.225    
                7       12.15       0.1375E-01   0.5622    
                8       7.675       0.1527E-01   0.6830E-01
                9       4.848       0.1402E-01  -0.9687E-01
               10       3.062       0.1165E-01  -0.2151E-01
               11       1.934       0.9140E-02  -0.1510    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.941    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2301      0.2300      0.2137      [ 0.2287    ,  0.2312    ]
 KA1            1.631       1.619       2.047      [  1.534    ,   1.704    ]
 V              27.66       27.66      0.9723E-01  [  27.59    ,   27.73    ]
 F             0.9695      0.9750       4.608      [ 0.8595    ,   1.091    ]
 KA2            2.799       2.800      0.3822      [  2.772    ,   2.827    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.70      0.19      1.00
 F           0.09     -0.31     -0.06      1.00
 KA2        -0.45      0.13      0.67     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.242E-06
 KA1       -.401E-05 0.110E-02
 V         -.922E-05 0.171E-03 0.723E-03
 F         0.190E-05 -.467E-03 -.729E-04 0.202E-02
 KA2       -.234E-05 0.471E-04 0.194E-03 -.221E-04 0.114E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.77        17.78       -0.7123E-02   0.7549E-03
      3       1.000        20.24        20.23        0.9072E-02   0.3050E-03
      4       1.500        19.10        19.11       -0.1494E-01   0.4847E-03
      5       2.000        17.29        17.31       -0.1541E-01   0.8643E-03
      6       3.000        13.87        13.82        0.4505E-01   0.1901E-02
      7       4.000        11.02        10.99        0.3079E-01   0.3043E-02
      8       6.000        6.940        6.938        0.2113E-02   0.5140E-02
      9       8.000        4.380        4.380        0.5182E-05   0.6745E-02
     10       10.00        2.760        2.765       -0.5160E-02   0.7871E-02
     11       12.00        1.740        1.746       -0.5691E-02   0.8626E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.78       0.2294E-01  -0.2621    
                3       20.23       0.1193E-01   0.5176    
                4       19.11       0.1344E-01  -0.6803    
                5       17.31       0.1422E-01  -0.5250    
                6       13.82       0.1391E-01    1.033    
                7       10.99       0.1437E-01   0.5578    
                8       6.938       0.1477E-01   0.2929E-01
                9       4.380       0.1335E-01  -0.4463E-04
               10       2.765       0.1105E-01  -0.5823E-01
               11       1.746       0.8656E-02  -0.6131E-01

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.130    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2297      0.2053      [ 0.2285    ,  0.2310    ]
 KA1            1.555       1.549       2.136      [  1.464    ,   1.634    ]
 V              25.52       25.52      0.7594E-01  [  25.47    ,   25.57    ]
 F             0.9452      0.9483       4.752      [ 0.8324    ,   1.064    ]
 KA2            2.801       2.801      0.2914      [  2.780    ,   2.822    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.79      0.19      1.00
 F           0.08     -0.32     -0.07      1.00
 KA2        -0.50      0.13      0.74     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.222E-06
 KA1       -.362E-05 0.109E-02
 V         -.721E-05 0.125E-03 0.376E-03
 F         0.178E-05 -.473E-03 -.599E-04 0.203E-02
 KA2       -.193E-05 0.360E-04 0.116E-03 -.181E-04 0.666E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.26        19.27       -0.1091E-01   0.4571E-03
      3       1.000        21.94        21.93        0.1029E-01   0.1109E-03
      4       1.500        20.70        20.72       -0.2076E-01   0.2392E-03
      5       2.000        18.75        18.76       -0.1076E-01   0.5504E-03
      6       3.000        15.04        14.99        0.4918E-01   0.1509E-02
      7       4.000        11.95        11.92        0.3133E-01   0.2639E-02
      8       6.000        7.530        7.528        0.1833E-02   0.4801E-02
      9       8.000        4.750        4.755       -0.4845E-02   0.6497E-02
     10       10.00        3.000        3.003       -0.3196E-02   0.7700E-02
     11       12.00        1.880        1.897       -0.1684E-01   0.8512E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.27       0.1775E-01  -0.5133    
                3       21.93       0.8110E-02   0.9741    
                4       20.72       0.9708E-02   -1.344    
                5       18.76       0.1079E-01  -0.4595    
                6       14.99       0.1211E-01    1.266    
                7       11.92       0.1386E-01   0.6095    
                8       7.528       0.1520E-01   0.2626E-01
                9       4.755       0.1393E-01  -0.6023E-01
               10       3.003       0.1158E-01  -0.3650E-01
               11       1.897       0.9084E-02  -0.1826    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.346    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2300      0.2299      0.2122      [ 0.2287    ,  0.2312    ]
 KA1            1.611       1.600       2.069      [  1.515    ,   1.686    ]
 V              27.09       27.10      0.9174E-01  [  27.03    ,   27.16    ]
 F             0.9631      0.9680       4.649      [ 0.8523    ,   1.084    ]
 KA2            2.799       2.799      0.3589      [  2.774    ,   2.825    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.72      0.20      1.00
 F           0.09     -0.32     -0.07      1.00
 KA2        -0.46      0.14      0.69     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.238E-06
 KA1       -.397E-05 0.110E-02
 V         -.871E-05 0.162E-03 0.618E-03
 F         0.194E-05 -.473E-03 -.749E-04 0.203E-02
 KA2       -.223E-05 0.450E-04 0.172E-03 -.227E-04 0.101E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.14        18.15       -0.6213E-02   0.6744E-03
      3       1.000        20.66        20.65        0.8189E-02   0.2480E-03
      4       1.500        19.50        19.51       -0.1333E-01   0.4158E-03
      5       2.000        17.65        17.67       -0.1669E-01   0.7798E-03
      6       3.000        14.16        14.11        0.4546E-01   0.1799E-02
      7       4.000        11.25        11.22        0.2985E-01   0.2940E-02
      8       6.000        7.090        7.085        0.5359E-02   0.5055E-02
      9       8.000        4.470        4.473       -0.3244E-02   0.6683E-02
     10       10.00        2.820        2.824       -0.4410E-02   0.7828E-02
     11       12.00        1.780        1.783       -0.3336E-02   0.8598E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.15       0.2170E-01  -0.2421    
                3       20.65       0.1103E-01   0.5181    
                4       19.51       0.1256E-01  -0.6553    
                5       17.67       0.1341E-01  -0.5988    
                6       14.11       0.1348E-01    1.071    
                7       11.22       0.1426E-01   0.5502    
                8       7.085       0.1492E-01   0.7520E-01
                9       4.473       0.1353E-01  -0.3980E-01
               10       2.824       0.1122E-01  -0.4990E-01
               11       1.783       0.8792E-02  -0.3601E-01

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.652    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.2033      [ 0.2286    ,  0.2310    ]
 KA1            1.545       1.540       2.145      [  1.455    ,   1.625    ]
 V              25.30       25.30      0.7350E-01  [  25.25    ,   25.35    ]
 F             0.9436      0.9464       4.756      [ 0.8307    ,   1.062    ]
 KA2            2.802       2.802      0.2819      [  2.782    ,   2.822    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.80      0.20      1.00
 F           0.08     -0.31     -0.07      1.00
 KA2        -0.51      0.13      0.74     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.218E-06
 KA1       -.357E-05 0.109E-02
 V         -.694E-05 0.120E-03 0.346E-03
 F         0.174E-05 -.465E-03 -.578E-04 0.203E-02
 KA2       -.188E-05 0.350E-04 0.109E-03 -.174E-04 0.624E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.43        19.44       -0.1137E-01   0.4279E-03
      3       1.000        22.13        22.12        0.9712E-02   0.9517E-04
      4       1.500        20.88        20.90       -0.1882E-01   0.2172E-03
      5       2.000        18.91        18.92       -0.1070E-01   0.5202E-03
      6       3.000        15.16        15.12        0.4294E-01   0.1469E-02
      7       4.000        12.04        12.02        0.2209E-01   0.2598E-02
      8       6.000        7.580        7.589       -0.9442E-02   0.4766E-02
      9       8.000        4.770        4.793       -0.2266E-01   0.6472E-02
     10       10.00        3.010        3.027       -0.1652E-01   0.7683E-02
     11       12.00        1.880        1.911       -0.3122E-01   0.8501E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.44       0.1716E-01  -0.5525    
                3       22.12       0.7633E-02   0.9931    
                4       20.90       0.9254E-02   -1.278    
                5       18.92       0.1038E-01  -0.4701    
                6       15.12       0.1189E-01    1.120    
                7       12.02       0.1376E-01   0.4330    
                8       7.589       0.1518E-01  -0.1370    
                9       4.793       0.1392E-01  -0.2818    
               10       3.027       0.1157E-01  -0.1885    
               11       1.911       0.9075E-02  -0.3386    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.521    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1972      [ 0.2286    ,  0.2309    ]
 KA1            1.512       1.509       2.186      [  1.424    ,   1.594    ]
 V              24.36       24.36      0.6343E-01  [  24.32    ,   24.40    ]
 F             0.9330      0.9351       4.814      [ 0.8193    ,   1.051    ]
 KA2            2.803       2.803      0.2381      [  2.785    ,   2.820    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.22      1.00
 V          -0.85      0.20      1.00
 F           0.08     -0.31     -0.07      1.00
 KA2        -0.55      0.14      0.79     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.205E-06
 KA1       -.334E-05 0.109E-02
 V         -.596E-05 0.101E-03 0.239E-03
 F         0.167E-05 -.467E-03 -.506E-04 0.203E-02
 KA2       -.167E-05 0.302E-04 0.817E-04 -.158E-04 0.445E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.18        20.19       -0.1250E-01   0.3105E-03
      3       1.000        22.98        22.97        0.5837E-02   0.3934E-04
      4       1.500        21.69        21.71       -0.1564E-01   0.1310E-03
      5       2.000        19.64        19.65       -0.1163E-01   0.3931E-03
      6       3.000        15.75        15.70        0.4787E-01   0.1292E-02
      7       4.000        12.51        12.48        0.2604E-01   0.2408E-02
      8       6.000        7.870        7.885       -0.1494E-01   0.4601E-02
      9       8.000        4.960        4.980       -0.2001E-01   0.6349E-02
     10       10.00        3.120        3.145       -0.2530E-01   0.7598E-02
     11       12.00        1.950        1.987       -0.3653E-01   0.8445E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.19       0.1420E-01  -0.7119    
                3       22.97       0.5349E-02   0.9277    
                4       21.71       0.7203E-02   -1.368    
                5       19.65       0.8630E-02  -0.5875    
                6       15.70       0.1116E-01    1.332    
                7       12.48       0.1361E-01   0.5303    
                8       7.885       0.1534E-01  -0.2205    
                9       4.980       0.1411E-01  -0.2513    
               10       3.145       0.1173E-01  -0.2903    
               11       1.987       0.9197E-02  -0.3975    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.295    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2301      0.2300      0.2129      [ 0.2288    ,  0.2313    ]
 KA1            1.620       1.609       2.058      [  1.524    ,   1.694    ]
 V              27.40       27.40      0.9488E-01  [  27.33    ,   27.47    ]
 F             0.9672      0.9723       4.626      [ 0.8567    ,   1.088    ]
 KA2            2.797       2.798      0.3709      [  2.771    ,   2.824    ]


 SDslope       -.4080E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.71      0.19      1.00
 F           0.09     -0.32     -0.06      1.00
 KA2        -0.45      0.13      0.68     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.240E-06
 KA1       -.400E-05 0.110E-02
 V         -.901E-05 0.167E-03 0.676E-03
 F         0.194E-05 -.472E-03 -.748E-04 0.202E-02
 KA2       -.229E-05 0.461E-04 0.183E-03 -.221E-04 0.108E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.93        17.94       -0.9281E-02   0.7189E-03
      3       1.000        20.43        20.42        0.1073E-01   0.2787E-03
      4       1.500        19.28        19.29       -0.1436E-01   0.4530E-03
      5       2.000        17.45        17.47       -0.1819E-01   0.8257E-03
      6       3.000        14.00        13.95        0.4527E-01   0.1855E-02
      7       4.000        11.12        11.09        0.2803E-01   0.2997E-02
      8       6.000        7.000        7.002       -0.2225E-02   0.5103E-02
      9       8.000        4.410        4.420       -0.1027E-01   0.6719E-02
     10       10.00        2.770        2.790       -0.2037E-01   0.7853E-02
     11       12.00        1.740        1.761       -0.2147E-01   0.8614E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.94       0.2235E-01  -0.3490    
                3       20.42       0.1155E-01   0.6410    
                4       19.29       0.1304E-01  -0.6764    
                5       17.47       0.1384E-01  -0.6339    
                6       13.95       0.1368E-01    1.051    
                7       11.09       0.1428E-01   0.5117    
                8       7.002       0.1481E-01  -0.3132E-01
                9       4.420       0.1341E-01  -0.1254    
               10       2.790       0.1111E-01  -0.2300    
               11       1.761       0.8703E-02  -0.2314    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 14:54:11 2018

 Data file name: data_null.csv

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    3000

 Total number of EM iterations:   30

 Normal distribution option

 -2logLikelihood:   -710.427    

 Model Selection Criteria
  AIC:       -668.427    
  BIC:       -593.333    


  ** Standard Errors can not be calculated **

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KE          0.230         --          0.510E-03   0.222         --
  KA1          1.54         --          0.510E-01    3.32         --
  V            25.4         --           1.33        5.23         --
  F           0.952         --          0.482E-01    5.07         --
  KA2          2.79         --          0.218E-01   0.782         --

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KE        KA1       V         F         KA2       
 KE        0.260E-06
 KA1       -.850E-06 0.260E-02
 V         0.102E-03 0.542E-01  1.77    
 F         0.389E-05 0.275E-03 0.229E-01 0.233E-02
 KA2       -.322E-05 0.294E-03 0.690E-02 0.227E-04 0.477E-03

  As Correlation Matrix:

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.03      1.00
 V           0.15      0.80      1.00
 F           0.16      0.11      0.36      1.00
 KA2        -0.29      0.26      0.24      0.02      1.00

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope    -0.408E-02
  SDinter     0.100      Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  1) =  0.2298749         ! KE        
       Pmean(  2) =   1.537546         ! KA1       
       Pmean(  3) =   25.43654         ! V         
       Pmean(  4) =  0.9523077         ! F         
       Pmean(  5) =   2.791260         ! KA2       
 
       Pcov(  1,  1) =  0.2595917E-06  ! KE         & KE        
       Pcov(  2,  1) = -0.8500068E-06  ! KA1        & KE        
       Pcov(  2,  2) =  0.2604956E-02  ! KA1        & KA1       
       Pcov(  3,  1) =  0.1024713E-03  ! V          & KE        
       Pcov(  3,  2) =  0.5419460E-01  ! V          & KA1       
       Pcov(  3,  3) =   1.769166      ! V          & V         
       Pcov(  4,  1) =  0.3888479E-05  ! F          & KE        
       Pcov(  4,  2) =  0.2750976E-03  ! F          & KA1       
       Pcov(  4,  3) =  0.2293766E-01  ! F          & V         
       Pcov(  4,  4) =  0.2326906E-02  ! F          & F         
       Pcov(  5,  1) = -0.3221255E-05  ! KA2        & KE        
       Pcov(  5,  2) =  0.2941387E-03  ! KA2        & KA1       
       Pcov(  5,  3) =  0.6903791E-02  ! KA2        & V         
       Pcov(  5,  4) =  0.2271066E-04  ! KA2        & F         
       Pcov(  5,  5) =  0.4767864E-03  ! KA2        & KA2       

      ________________________________________


 List of Files Created

  Record of program run and all results:
    A.run
  Summary of population estimates at each iteration:
    AIT.csv
  Individual subject estimates at final iteration:
    AIND.csv
  Table of predictions and residuals for each subject:
    ARSD.csv
  Information for plotting model predictions for each subject:
    APLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    A.eps
  Command file for subsequent Batch runs:
    A.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:54:12 2018

