
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 13:59:54 2018


 Enter file name for storing session run (*.run): B.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Enter the data file name (*.dat): data_null.csv

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Enter parameter file name (*.prm or *IND.csv):  param_null.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           y
 KA1         2.000           y
 V           21.00           y
 F          0.8000           y
 KA2         2.000           y
 SDinter    0.1000           n
 SDslope    0.1000           y

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  1

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  2

 Enter number of samples/EM iteration (1000 -   3000):      3000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.516    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1799      [ 0.2287    ,  0.2309    ]
 KA1            1.505       1.505      0.2963      [  1.493    ,   1.516    ]
 V              26.14       26.17       2.919      [  24.20    ,   28.13    ]
 F             0.9948      0.9958       2.919      [ 0.9211    ,   1.071    ]
 KA2            2.800       2.801      0.5124      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.28      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.171E-06
 KA1       -.510E-06 0.199E-04
 V         -.419E-05 0.480E-04 0.583    
 F         0.111E-06 -.139E-05 0.222E-01 0.845E-03
 KA2       -.340E-08 -.448E-08 -.135E-04 -.496E-06 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.20        13.21       -0.1287E-01   0.2097E-02
      3       1.000        18.00        18.00       -0.4798E-02   0.6834E-03
      4       1.500        19.00        18.98        0.1566E-01   0.4894E-03
      5       2.000        18.30        18.31       -0.6207E-02   0.6202E-03
      6       3.000        15.40        15.44       -0.3559E-01   0.1345E-02
      7       4.000        12.50        12.46        0.3629E-01   0.2388E-02
      8       6.000        7.920        7.916        0.4144E-02   0.4560E-02
      9       8.000        5.000        5.001       -0.1388E-02   0.6318E-02
     10       10.00        3.160        3.159        0.1305E-02   0.7576E-02
     11       12.00        1.990        1.995       -0.4856E-02   0.8430E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.21       0.1974E-01  -0.2817    
                3       18.00       0.1634E-01  -0.1851    
                4       18.98       0.1322E-01   0.7063    
                5       18.31       0.1420E-01  -0.2506    
                6       15.44       0.1657E-01  -0.9710    
                7       12.46       0.1646E-01   0.7420    
                8       7.916       0.1471E-01   0.6117E-01
                9       5.001       0.1263E-01  -0.1756E-01
               10       3.159       0.1032E-01   0.1493E-01
               11       1.995       0.8058E-02  -0.5292E-01

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.160    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1790      [ 0.2287    ,  0.2309    ]
 KA1            1.505       1.505      0.2836      [  1.494    ,   1.516    ]
 V              25.69       25.70       2.919      [  23.77    ,   27.63    ]
 F              1.007       1.007       2.919      [ 0.9318    ,   1.083    ]
 KA2            2.800       2.801      0.5137      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.169E-06
 KA1       -.532E-06 0.182E-04
 V         -.442E-05 0.449E-04 0.563    
 F         0.989E-07 -.130E-05 0.220E-01 0.865E-03
 KA2       -.303E-08 0.346E-07 0.818E-05 0.306E-06 0.207E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.60        13.61       -0.1055E-01   0.1951E-02
      3       1.000        18.54        18.55       -0.6165E-02   0.5722E-03
      4       1.500        19.57        19.55        0.1526E-01   0.3914E-03
      5       2.000        18.85        18.86       -0.5944E-02   0.5130E-03
      6       3.000        15.86        15.90       -0.3885E-01   0.1210E-02
      7       4.000        12.88        12.84        0.4229E-01   0.2241E-02
      8       6.000        8.160        8.153        0.6624E-02   0.4429E-02
      9       8.000        5.150        5.151       -0.1469E-02   0.6220E-02
     10       10.00        3.250        3.253       -0.3489E-02   0.7509E-02
     11       12.00        2.050        2.055       -0.4728E-02   0.8385E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.61       0.1902E-01  -0.2396    
                3       18.55       0.1534E-01  -0.2594    
                4       19.55       0.1207E-01   0.7698    
                5       18.86       0.1317E-01  -0.2638    
                6       15.90       0.1579E-01   -1.118    
                7       12.84       0.1591E-01   0.8929    
                8       8.153       0.1457E-01   0.9934E-01
                9       5.151       0.1270E-01  -0.1873E-01
               10       3.253       0.1044E-01  -0.4033E-01
               11       2.055       0.8188E-02  -0.5166E-01

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.948    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1806      [ 0.2287    ,  0.2309    ]
 KA1            1.504       1.505      0.3082      [  1.493    ,   1.516    ]
 V              26.60       26.64       2.919      [  24.64    ,   28.64    ]
 F             0.9819      0.9835       2.918      [ 0.9098    ,   1.057    ]
 KA2            2.800       2.801      0.5128      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.25      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00      0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.172E-06
 KA1       -.478E-06 0.215E-04
 V         -.423E-05 0.540E-04 0.605    
 F         0.111E-06 -.135E-05 0.223E-01 0.824E-03
 KA2       0.154E-07 0.275E-07 -.677E-05 -.232E-06 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.80        12.81       -0.1480E-01   0.2250E-02
      3       1.000        17.46        17.46       -0.3454E-02   0.8044E-03
      4       1.500        18.43        18.41        0.1557E-01   0.5983E-03
      5       2.000        17.75        17.76       -0.7278E-02   0.7375E-03
      6       3.000        14.94        14.97       -0.3340E-01   0.1488E-02
      7       4.000        12.13        12.09        0.3919E-01   0.2540E-02
      8       6.000        7.680        7.679        0.7643E-03   0.4692E-02
      9       8.000        4.850        4.852       -0.1990E-02   0.6415E-02
     10       10.00        3.070        3.064        0.5595E-02   0.7644E-02
     11       12.00        1.930        1.935       -0.5347E-02   0.8475E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.81       0.2041E-01  -0.3127    
                3       17.46       0.1734E-01  -0.1233    
                4       18.41       0.1436E-01   0.6352    
                5       17.76       0.1521E-01  -0.2693    
                6       14.97       0.1731E-01  -0.8667    
                7       12.09       0.1697E-01   0.7770    
                8       7.679       0.1484E-01   0.1096E-01
                9       4.852       0.1257E-01  -0.2495E-01
               10       3.064       0.1019E-01   0.6394E-01
               11       1.935       0.7928E-02  -0.5811E-01

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.359    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1816      [ 0.2287    ,  0.2309    ]
 KA1            1.504       1.504      0.3164      [  1.492    ,   1.517    ]
 V              26.90       26.96       2.917      [  24.94    ,   28.98    ]
 F             0.9728      0.9748       2.917      [ 0.9017    ,   1.048    ]
 KA2            2.800       2.801      0.5133      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.174E-06
 KA1       -.466E-06 0.227E-04
 V         -.378E-05 0.571E-04 0.619    
 F         0.131E-06 -.137E-05 0.223E-01 0.809E-03
 KA2       -.109E-07 0.667E-08 0.116E-04 0.372E-06 0.207E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.54        12.55       -0.1141E-01   0.2353E-02
      3       1.000        17.10        17.10       -0.4728E-02   0.8900E-03
      4       1.500        18.05        18.04        0.1370E-01   0.6766E-03
      5       2.000        17.39        17.39       -0.2719E-02   0.8209E-03
      6       3.000        14.63        14.67       -0.3601E-01   0.1587E-02
      7       4.000        11.88        11.84        0.3746E-01   0.2644E-02
      8       6.000        7.520        7.521       -0.1437E-02   0.4781E-02
      9       8.000        4.750        4.752       -0.2206E-02   0.6481E-02
     10       10.00        3.000        3.001       -0.1331E-02   0.7689E-02
     11       12.00        1.890        1.895       -0.5479E-02   0.8505E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.55       0.2086E-01  -0.2360    
                3       17.10       0.1801E-01  -0.1600    
                4       18.04       0.1509E-01   0.5252    
                5       17.39       0.1583E-01  -0.9617E-01
                6       14.67       0.1772E-01  -0.9048    
                7       11.84       0.1725E-01   0.7280    
                8       7.521       0.1490E-01  -0.2097E-01
                9       4.752       0.1253E-01  -0.2751E-01
               10       3.001       0.1011E-01  -0.1523E-01
               11       1.895       0.7847E-02  -0.5944E-01

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.940    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1782      [ 0.2287    ,  0.2308    ]
 KA1            1.505       1.505      0.2737      [  1.494    ,   1.515    ]
 V              25.39       25.39       2.918      [  23.48    ,   27.29    ]
 F              1.015       1.015       2.918      [ 0.9385    ,   1.091    ]
 KA2            2.800       2.801      0.5135      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.32      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.168E-06
 KA1       -.545E-06 0.170E-04
 V         -.454E-05 0.466E-04 0.549    
 F         0.906E-07 -.106E-05 0.219E-01 0.876E-03
 KA2       0.179E-08 -.415E-07 0.270E-04 0.111E-05 0.207E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.86        13.87       -0.1411E-01   0.1856E-02
      3       1.000        18.90        18.91       -0.6554E-02   0.5036E-03
      4       1.500        19.95        19.94        0.1429E-01   0.3320E-03
      5       2.000        19.22        19.22       -0.3980E-02   0.4469E-03
      6       3.000        16.17        16.21       -0.3984E-01   0.1123E-02
      7       4.000        13.13        13.09        0.4094E-01   0.2144E-02
      8       6.000        8.320        8.313        0.6879E-02   0.4343E-02
      9       8.000        5.250        5.252       -0.2431E-02   0.6155E-02
     10       10.00        3.320        3.317        0.2728E-02   0.7464E-02
     11       12.00        2.090        2.095       -0.5020E-02   0.8355E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.87       0.1842E-01  -0.3282    
                3       18.91       0.1461E-01  -0.2938    
                4       19.94       0.1130E-01   0.7826    
                5       19.22       0.1247E-01  -0.1897    
                6       16.21       0.1522E-01   -1.190    
                7       13.09       0.1550E-01   0.8837    
                8       8.313       0.1445E-01   0.1042    
                9       5.252       0.1272E-01  -0.3110E-01
               10       3.317       0.1051E-01   0.3152E-01
               11       2.095       0.8265E-02  -0.5496E-01

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.723    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1770      [ 0.2288    ,  0.2309    ]
 KA1            1.506       1.506      0.2595      [  1.496    ,   1.516    ]
 V              24.95       24.93       2.921      [  23.06    ,   26.81    ]
 F              1.025       1.025       2.920      [ 0.9478    ,   1.102    ]
 KA2            2.800       2.801      0.5126      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.35      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.165E-06
 KA1       -.562E-06 0.153E-04
 V         -.444E-05 0.414E-04 0.530    
 F         0.889E-07 -.105E-05 0.218E-01 0.896E-03
 KA2       -.629E-08 -.120E-08 -.212E-04 -.911E-06 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        14.26        14.27       -0.1341E-01   0.1718E-02
      3       1.000        19.44        19.45       -0.7337E-02   0.4090E-03
      4       1.500        20.52        20.50        0.1674E-01   0.2525E-03
      5       2.000        19.76        19.77       -0.9375E-02   0.3573E-03
      6       3.000        16.63        16.67       -0.3775E-01   0.1000E-02
      7       4.000        13.50        13.46        0.4202E-01   0.2006E-02
      8       6.000        8.550        8.547        0.3132E-02   0.4217E-02
      9       8.000        5.400        5.400        0.1388E-03   0.6060E-02
     10       10.00        3.410        3.410       -0.2285E-03   0.7398E-02
     11       12.00        2.150        2.154       -0.3630E-02   0.8311E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       14.27       0.1748E-01  -0.3242    
                3       19.45       0.1347E-01  -0.3646    
                4       20.50       0.1013E-01    1.052    
                5       19.77       0.1145E-01  -0.4975    
                6       16.67       0.1441E-01   -1.195    
                7       13.46       0.1491E-01   0.9377    
                8       8.547       0.1429E-01   0.4803E-01
                9       5.400       0.1276E-01   0.1673E-02
               10       3.410       0.1062E-01  -0.2719E-02
               11       2.154       0.8375E-02  -0.3985E-01

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.027    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1825      [ 0.2287    ,  0.2309    ]
 KA1            1.504       1.504      0.3270      [  1.492    ,   1.517    ]
 V              27.37       27.44       2.924      [  25.38    ,   29.50    ]
 F             0.9583      0.9609       2.923      [ 0.8887    ,   1.033    ]
 KA2            2.800       2.801      0.5126      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.21      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.176E-06
 KA1       -.435E-06 0.242E-04
 V         -.340E-05 0.643E-04 0.644    
 F         0.146E-06 -.129E-05 0.225E-01 0.789E-03
 KA2       0.756E-08 -.816E-07 0.227E-04 0.821E-06 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.14        12.15       -0.1397E-01   0.2514E-02
      3       1.000        16.56        16.56       -0.3691E-02   0.1027E-02
      4       1.500        17.48        17.47        0.1372E-01   0.8037E-03
      5       2.000        16.84        16.84       -0.3374E-02   0.9551E-03
      6       3.000        14.17        14.20       -0.3315E-01   0.1742E-02
      7       4.000        11.50        11.47        0.3105E-01   0.2804E-02
      8       6.000        7.290        7.284        0.5728E-02   0.4917E-02
      9       8.000        4.600        4.602       -0.2414E-02   0.6580E-02
     10       10.00        2.910        2.907        0.3240E-02   0.7757E-02
     11       12.00        1.830        1.836       -0.5774E-02   0.8551E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.15       0.2136E-01  -0.2793    
                3       16.56       0.1890E-01  -0.1166    
                4       17.47       0.1617E-01   0.4827    
                5       16.84       0.1679E-01  -0.1104    
                6       14.20       0.1839E-01  -0.7950    
                7       11.47       0.1769E-01   0.5860    
                8       7.284       0.1499E-01   0.8151E-01
                9       4.602       0.1245E-01  -0.2986E-01
               10       2.907       0.9977E-02   0.3673E-01
               11       1.836       0.7713E-02  -0.6247E-01

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.604    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1811      [ 0.2287    ,  0.2309    ]
 KA1            1.505       1.505      0.3125      [  1.493    ,   1.517    ]
 V              26.75       26.80       2.919      [  24.79    ,   28.81    ]
 F             0.9774      0.9792       2.919      [ 0.9057    ,   1.053    ]
 KA2            2.800       2.801      0.5141      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.24      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.173E-06
 KA1       -.475E-06 0.221E-04
 V         -.471E-05 0.483E-04 0.612    
 F         0.961E-07 -.162E-05 0.223E-01 0.817E-03
 KA2       -.489E-08 0.904E-07 -.267E-04 -.997E-06 0.207E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.67        12.68       -0.1369E-01   0.2301E-02
      3       1.000        17.28        17.28       -0.4032E-02   0.8467E-03
      4       1.500        18.24        18.22        0.1539E-01   0.6370E-03
      5       2.000        17.57        17.57       -0.3756E-02   0.7789E-03
      6       3.000        14.78        14.82       -0.3809E-01   0.1538E-02
      7       4.000        12.00        11.97        0.3491E-01   0.2593E-02
      8       6.000        7.600        7.599        0.9035E-03   0.4737E-02
      9       8.000        4.800        4.801       -0.1190E-02   0.6449E-02
     10       10.00        3.030        3.032       -0.2217E-02   0.7667E-02
     11       12.00        1.910        1.915       -0.4953E-02   0.8491E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.68       0.2068E-01  -0.2862    
                3       17.28       0.1772E-01  -0.1401    
                4       18.22       0.1475E-01   0.6085    
                5       17.57       0.1552E-01  -0.1359    
                6       14.82       0.1750E-01  -0.9722    
                7       11.97       0.1709E-01   0.6851    
                8       7.599       0.1485E-01   0.1294E-01
                9       4.801       0.1253E-01  -0.1492E-01
               10       3.032       0.1014E-01  -0.2537E-01
               11       1.915       0.7881E-02  -0.5379E-01

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.428    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1783      [ 0.2287    ,  0.2308    ]
 KA1            1.505       1.505      0.2783      [  1.494    ,   1.516    ]
 V              25.54       25.54       2.917      [  23.63    ,   27.46    ]
 F              1.011       1.011       2.917      [ 0.9352    ,   1.087    ]
 KA2            2.800       2.801      0.5126      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.31      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.168E-06
 KA1       -.534E-06 0.175E-04
 V         -.411E-05 0.436E-04 0.555    
 F         0.108E-06 -.126E-05 0.220E-01 0.870E-03
 KA2       0.264E-08 0.133E-07 0.347E-04 0.138E-05 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.73        13.74       -0.1228E-01   0.1903E-02
      3       1.000        18.72        18.73       -0.5735E-02   0.5375E-03
      4       1.500        19.76        19.74        0.1586E-01   0.3612E-03
      5       2.000        19.03        19.04       -0.8638E-02   0.4796E-03
      6       3.000        16.02        16.05       -0.3299E-01   0.1166E-02
      7       4.000        13.00        12.96        0.3776E-01   0.2193E-02
      8       6.000        8.240        8.233        0.7449E-02   0.4386E-02
      9       8.000        5.200        5.202       -0.1547E-02   0.6188E-02
     10       10.00        3.290        3.285        0.4849E-02   0.7486E-02
     11       12.00        2.070        2.075       -0.4745E-02   0.8370E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.74       0.1869E-01  -0.2822    
                3       18.73       0.1495E-01  -0.2491    
                4       19.74       0.1169E-01   0.8327    
                5       19.04       0.1284E-01  -0.3958    
                6       16.05       0.1554E-01  -0.9669    
                7       12.96       0.1573E-01   0.8060    
                8       8.233       0.1451E-01   0.1123    
                9       5.202       0.1270E-01  -0.1978E-01
               10       3.285       0.1047E-01   0.5598E-01
               11       2.075       0.8216E-02  -0.5190E-01

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.922    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.1791      [ 0.2288    ,  0.2309    ]
 KA1            1.505       1.505      0.2835      [  1.494    ,   1.516    ]
 V              25.70       25.71       2.918      [  23.79    ,   27.64    ]
 F              1.006       1.007       2.918      [ 0.9314    ,   1.082    ]
 KA2            2.800       2.801      0.5129      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.169E-06
 KA1       -.532E-06 0.182E-04
 V         -.392E-05 0.483E-04 0.563    
 F         0.119E-06 -.116E-05 0.220E-01 0.863E-03
 KA2       0.383E-08 -.823E-07 -.382E-04 -.148E-05 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1631E-01   0.1956E-02
      3       1.000        18.52        18.53       -0.6240E-02   0.5761E-03
      4       1.500        19.55        19.53        0.1680E-01   0.3949E-03
      5       2.000        18.83        18.83       -0.4663E-02   0.5170E-03
      6       3.000        15.84        15.88       -0.4007E-01   0.1215E-02
      7       4.000        12.86        12.82        0.3812E-01   0.2247E-02
      8       6.000        8.140        8.142       -0.2484E-02   0.4435E-02
      9       8.000        5.130        5.144       -0.1406E-01   0.6225E-02
     10       10.00        3.230        3.248       -0.1848E-01   0.7512E-02
     11       12.00        2.030        2.051       -0.2135E-01   0.8388E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.1902E-01  -0.3695    
                3       18.53       0.1536E-01  -0.2617    
                4       19.53       0.1212E-01   0.8441    
                5       18.83       0.1320E-01  -0.2065    
                6       15.88       0.1579E-01   -1.150    
                7       12.82       0.1590E-01   0.8037    
                8       8.142       0.1456E-01  -0.3749E-01
                9       5.144       0.1269E-01  -0.1783    
               10       3.248       0.1043E-01  -0.2132    
               11       2.051       0.8179E-02  -0.2332    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.682    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.1778      [ 0.2288    ,  0.2309    ]
 KA1            1.505       1.505      0.2744      [  1.494    ,   1.515    ]
 V              25.40       25.40       2.918      [  23.50    ,   27.31    ]
 F              1.014       1.014       2.918      [ 0.9381    ,   1.090    ]
 KA2            2.800       2.801      0.5130      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.32      1.00
 V          -0.02      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.167E-06
 KA1       -.543E-06 0.171E-04
 V         -.468E-05 0.477E-04 0.549    
 F         0.838E-07 -.104E-05 0.219E-01 0.876E-03
 KA2       -.288E-08 0.435E-08 0.162E-04 0.634E-06 0.206E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.84        13.86       -0.1989E-01   0.1861E-02
      3       1.000        18.88        18.89       -0.6700E-02   0.5073E-03
      4       1.500        19.93        19.91        0.1573E-01   0.3352E-03
      5       2.000        19.20        19.20       -0.2804E-02   0.4506E-03
      6       3.000        16.15        16.19       -0.4114E-01   0.1128E-02
      7       4.000        13.11        13.07        0.3672E-01   0.2150E-02
      8       6.000        8.300        8.302       -0.2231E-02   0.4348E-02
      9       8.000        5.230        5.245       -0.1500E-01   0.6160E-02
     10       10.00        3.300        3.312       -0.1223E-01   0.7467E-02
     11       12.00        2.070        2.092       -0.2162E-01   0.8358E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.86       0.1844E-01  -0.4618    
                3       18.89       0.1463E-01  -0.2992    
                4       19.91       0.1134E-01   0.8578    
                5       19.20       0.1253E-01  -0.1335    
                6       16.19       0.1529E-01   -1.226    
                7       13.07       0.1554E-01   0.7914    
                8       8.302       0.1445E-01  -0.3403E-01
                9       5.245       0.1270E-01  -0.1913    
               10       3.312       0.1049E-01  -0.1416    
               11       2.092       0.8242E-02  -0.2365    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.859    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1791      [ 0.2288    ,  0.2309    ]
 KA1            1.505       1.505      0.2836      [  1.494    ,   1.516    ]
 V              25.70       25.71       2.922      [  23.78    ,   27.65    ]
 F              1.007       1.007       2.922      [ 0.9313    ,   1.083    ]
 KA2            2.800       2.801      0.5131      [  2.764    ,   2.838    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.169E-06
 KA1       -.532E-06 0.182E-04
 V         -.437E-05 0.499E-04 0.565    
 F         0.101E-06 -.110E-05 0.221E-01 0.865E-03
 KA2       0.389E-08 -.229E-07 -.275E-04 -.107E-05 0.207E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1632E-01   0.1956E-02
      3       1.000        18.52        18.53       -0.6237E-02   0.5761E-03
      4       1.500        19.55        19.53        0.1684E-01   0.3949E-03
      5       2.000        18.83        18.83       -0.4599E-02   0.5170E-03
      6       3.000        15.84        15.88       -0.3996E-01   0.1215E-02
      7       4.000        12.86        12.82        0.3827E-01   0.2247E-02
      8       6.000        8.140        8.142       -0.2313E-02   0.4435E-02
      9       8.000        5.130        5.144       -0.1390E-01   0.6225E-02
     10       10.00        3.220        3.248       -0.2835E-01   0.7512E-02
     11       12.00        2.030        2.051       -0.2125E-01   0.8388E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.1902E-01  -0.3699    
                3       18.53       0.1537E-01  -0.2615    
                4       19.53       0.1213E-01   0.8457    
                5       18.83       0.1322E-01  -0.2037    
                6       15.88       0.1581E-01   -1.147    
                7       12.82       0.1592E-01   0.8069    
                8       8.142       0.1457E-01  -0.3492E-01
                9       5.144       0.1269E-01  -0.1763    
               10       3.248       0.1044E-01  -0.3271    
               11       2.051       0.8182E-02  -0.2321    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.807    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1739      [ 0.2287    ,  0.2307    ]
 KA1            1.504       1.504      0.4372      [  1.488    ,   1.521    ]
 V              26.29       26.29      0.7047E-01  [  26.24    ,   26.34    ]
 F             0.9948      0.9962       3.763      [ 0.8998    ,   1.093    ]
 KA2            2.801       2.801      0.2711      [  2.782    ,   2.821    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.67     -0.00      1.00
 F          -0.00      0.00     -0.00      1.00
 KA2        -0.32      0.00      0.62     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.160E-06
 KA1       0.290E-08 0.433E-04
 V         -.498E-05 -.332E-07 0.343E-03
 F         -.906E-09 0.501E-06 -.672E-06 0.141E-02
 KA2       -.981E-06 0.845E-08 0.874E-04 -.116E-06 0.577E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.70        18.71       -0.9784E-02   0.5405E-03
      3       1.000        21.30        21.29        0.9739E-02   0.1604E-03
      4       1.500        20.10        20.12       -0.1632E-01   0.3055E-03
      5       2.000        18.20        18.21       -0.1356E-01   0.6393E-03
      6       3.000        14.60        14.55        0.4607E-01   0.1624E-02
      7       4.000        11.60        11.57        0.2835E-01   0.2760E-02
      8       6.000        7.310        7.309        0.5955E-03   0.4902E-02
      9       8.000        4.610        4.617       -0.6943E-02   0.6571E-02
     10       10.00        2.910        2.916       -0.6266E-02   0.7751E-02
     11       12.00        1.830        1.842       -0.1204E-01   0.8546E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.71       0.1769E-01  -0.4232    
                3       21.29       0.9301E-02   0.7669    
                4       20.12       0.1045E-01  -0.9352    
                5       18.21       0.1145E-01  -0.5371    
                6       14.55       0.1215E-01    1.143    
                7       11.57       0.1296E-01   0.5395    
                8       7.309       0.1331E-01   0.8358E-02
                9       4.617       0.1191E-01  -0.8574E-01
               10       2.916       0.9790E-02  -0.7123E-01
               11       1.842       0.7631E-02  -0.1303    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.832    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1708      [ 0.2287    ,  0.2307    ]
 KA1            1.504       1.504      0.4366      [  1.488    ,   1.521    ]
 V              25.28       25.28      0.6160E-01  [  25.24    ,   25.32    ]
 F             0.9948      0.9961       3.758      [ 0.8999    ,   1.092    ]
 KA2            2.803       2.803      0.2392      [  2.786    ,   2.820    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.74      0.00      1.00
 F          -0.00     -0.00      0.00      1.00
 KA2        -0.38      0.00      0.68      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.154E-06
 KA1       -.309E-08 0.431E-04
 V         -.453E-05 0.744E-07 0.243E-03
 F         -.142E-07 -.714E-06 0.101E-05 0.140E-02
 KA2       -.101E-05 0.405E-07 0.709E-04 0.157E-06 0.449E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.45        19.46       -0.1173E-01   0.4066E-03
      3       1.000        22.15        22.14        0.8597E-02   0.8412E-04
      4       1.500        20.90        20.92       -0.1847E-01   0.2013E-03
      5       2.000        18.93        18.94       -0.8995E-02   0.4977E-03
      6       3.000        15.18        15.13        0.4689E-01   0.1438E-02
      7       4.000        12.06        12.03        0.2804E-01   0.2565E-02
      8       6.000        7.600        7.600        0.4278E-04   0.4737E-02
      9       8.000        4.790        4.800       -0.1034E-01   0.6449E-02
     10       10.00        3.030        3.032       -0.2024E-02   0.7667E-02
     11       12.00        1.900        1.915       -0.1511E-01   0.8490E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.46       0.1540E-01  -0.5839    
                3       22.14       0.7246E-02   0.9348    
                4       20.92       0.8623E-02   -1.303    
                5       18.94       0.9831E-02  -0.4040    
                6       15.13       0.1120E-01    1.236    
                7       12.03       0.1255E-01   0.5535    
                8       7.600       0.1335E-01   0.4673E-03
                9       4.800       0.1206E-01  -0.1288    
               10       3.032       0.9954E-02  -0.2317E-01
               11       1.915       0.7773E-02  -0.1640    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.656    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1764      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4372      [  1.488    ,   1.521    ]
 V              27.38       27.38      0.8012E-01  [  27.33    ,   27.44    ]
 F             0.9948      0.9962       3.758      [ 0.8999    ,   1.092    ]
 KA2            2.800       2.800      0.3014      [  2.778    ,   2.822    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.62     -0.00      1.00
 F           0.00      0.00     -0.00      1.00
 KA2        -0.28     -0.00      0.57     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.164E-06
 KA1       0.313E-09 0.433E-04
 V         -.547E-05 -.305E-06 0.481E-03
 F         0.449E-08 0.510E-06 -.438E-06 0.140E-02
 KA2       -.960E-06 -.741E-07 0.106E-03 -.468E-07 0.712E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.95        17.96       -0.9409E-02   0.6931E-03
      3       1.000        20.45        20.44        0.1026E-01   0.2609E-03
      4       1.500        19.30        19.31       -0.1419E-01   0.4314E-03
      5       2.000        17.47        17.49       -0.1787E-01   0.7987E-03
      6       3.000        14.02        13.97        0.4568E-01   0.1821E-02
      7       4.000        11.14        11.11        0.2914E-01   0.2962E-02
      8       6.000        7.020        7.018        0.1609E-02   0.5071E-02
      9       8.000        4.430        4.433       -0.3155E-02   0.6694E-02
     10       10.00        2.790        2.800       -0.1020E-01   0.7835E-02
     11       12.00        1.760        1.769       -0.8741E-02   0.8602E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.96       0.1968E-01  -0.3597    
                3       20.44       0.1123E-01   0.6331    
                4       19.31       0.1217E-01  -0.6847    
                5       17.49       0.1295E-01  -0.6333    
                6       13.97       0.1303E-01    1.070    
                7       11.11       0.1333E-01   0.5352    
                8       7.018       0.1322E-01   0.2246E-01
                9       4.433       0.1170E-01  -0.3864E-01
               10       2.800       0.9581E-02  -0.1152    
               11       1.769       0.7454E-02  -0.9427E-01

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.383    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1784      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4362      [  1.488    ,   1.521    ]
 V              28.57       28.57      0.8994E-01  [  28.51    ,   28.64    ]
 F             0.9948      0.9962       3.764      [ 0.8998    ,   1.093    ]
 KA2            2.800       2.800      0.3286      [  2.776    ,   2.824    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.56      0.00      1.00
 F           0.00     -0.00      0.00      1.00
 KA2        -0.24      0.00      0.52      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.168E-06
 KA1       -.248E-08 0.431E-04
 V         -.589E-05 0.230E-06 0.660E-03
 F         0.138E-07 -.275E-06 0.451E-06 0.141E-02
 KA2       -.898E-06 0.788E-07 0.124E-03 0.340E-06 0.847E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.20        17.21       -0.1044E-01   0.8643E-03
      3       1.000        19.60        19.59        0.1341E-01   0.3862E-03
      4       1.500        18.49        18.51       -0.1757E-01   0.5798E-03
      5       2.000        16.74        16.76       -0.1723E-01   0.9771E-03
      6       3.000        13.43        13.39        0.3992E-01   0.2031E-02
      7       4.000        10.67        10.65        0.2394E-01   0.3173E-02
      8       6.000        6.730        6.724        0.5566E-02   0.5244E-02
      9       8.000        4.240        4.247       -0.7253E-02   0.6819E-02
     10       10.00        2.680        2.683       -0.2630E-02   0.7920E-02
     11       12.00        1.680        1.694       -0.1439E-01   0.8658E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.21       0.2147E-01  -0.3573    
                3       19.59       0.1309E-01   0.6805    
                4       18.51       0.1378E-01  -0.7310    
                5       16.76       0.1434E-01  -0.5519    
                6       13.39       0.1391E-01   0.8853    
                7       10.65       0.1374E-01   0.4248    
                8       6.724       0.1315E-01   0.7673E-01
                9       4.247       0.1150E-01  -0.8791E-01
               10       2.683       0.9361E-02  -0.2960E-01
               11       1.694       0.7262E-02  -0.1547    

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.992    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1666      [ 0.2287    ,  0.2307    ]
 KA1            1.504       1.504      0.4364      [  1.488    ,   1.521    ]
 V              24.34       24.34      0.5281E-01  [  24.31    ,   24.38    ]
 F             0.9948      0.9961       3.761      [ 0.8998    ,   1.092    ]
 KA2            2.803       2.803      0.2050      [  2.789    ,   2.818    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.81     -0.00      1.00
 F          -0.00      0.00      0.00      1.00
 KA2        -0.45      0.00      0.75      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.146E-06
 KA1       0.143E-08 0.431E-04
 V         -.399E-05 -.359E-07 0.165E-03
 F         -.163E-07 0.177E-06 0.123E-05 0.140E-02
 KA2       -.994E-06 0.327E-08 0.555E-04 0.393E-06 0.330E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.20        20.21       -0.1272E-01   0.2919E-03
      3       1.000        23.00        23.00        0.4721E-02   0.3214E-04
      4       1.500        21.71        21.73       -0.1500E-01   0.1184E-03
      5       2.000        19.66        19.67       -0.9193E-02   0.3730E-03
      6       3.000        15.77        15.72        0.5333E-01   0.1262E-02
      7       4.000        12.53        12.50        0.3396E-01   0.2375E-02
      8       6.000        7.890        7.893       -0.3240E-02   0.4573E-02
      9       8.000        4.980        4.986       -0.5674E-02   0.6328E-02
     10       10.00        3.140        3.149       -0.9145E-02   0.7583E-02
     11       12.00        1.970        1.989       -0.1912E-01   0.8435E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.21       0.1276E-01  -0.7470    
                3       23.00       0.4908E-02   0.8297    
                4       21.73       0.6669E-02   -1.381    
                5       19.67       0.8165E-02  -0.4767    
                6       15.72       0.1034E-01    1.501    
                7       12.50       0.1220E-01   0.6965    
                8       7.893       0.1338E-01  -0.4807E-01
                9       4.986       0.1217E-01  -0.7142E-01
               10       3.149       0.1007E-01  -0.1051    
               11       1.989       0.7870E-02  -0.2082    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.980    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1699      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4371      [  1.488    ,   1.521    ]
 V              25.03       25.03      0.5921E-01  [  24.99    ,   25.07    ]
 F             0.9948      0.9961       3.763      [ 0.8998    ,   1.093    ]
 KA2            2.803       2.803      0.2303      [  2.786    ,   2.820    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.76      0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.39      0.00      0.69     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.152E-06
 KA1       0.406E-09 0.432E-04
 V         -.438E-05 0.855E-07 0.220E-03
 F         0.180E-07 -.407E-06 -.670E-06 0.141E-02
 KA2       -.994E-06 0.737E-08 0.664E-04 -.234E-06 0.417E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.64        19.65       -0.1487E-01   0.3753E-03
      3       1.000        22.37        22.36        0.8626E-02   0.6838E-04
      4       1.500        21.11        21.13       -0.1626E-01   0.1779E-03
      5       2.000        19.11        19.13       -0.1698E-01   0.4639E-03
      6       3.000        15.33        15.28        0.4701E-01   0.1392E-02
      7       4.000        12.18        12.15        0.2916E-01   0.2516E-02
      8       6.000        7.680        7.675        0.5314E-02   0.4695E-02
      9       8.000        4.840        4.847       -0.7310E-02   0.6418E-02
     10       10.00        3.060        3.062       -0.1548E-02   0.7646E-02
     11       12.00        1.920        1.934       -0.1367E-01   0.8476E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.65       0.1476E-01  -0.7697    
                3       22.36       0.6672E-02    1.040    
                4       21.13       0.8128E-02   -1.221    
                5       19.13       0.9415E-02  -0.7892    
                6       15.28       0.1100E-01    1.260    
                7       12.15       0.1248E-01   0.5812    
                8       7.675       0.1338E-01   0.7740E-01
                9       4.847       0.1211E-01  -0.9133E-01
               10       3.062       0.9995E-02  -0.1776E-01
               11       1.934       0.7806E-02  -0.1485    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.453    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1768      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4365      [  1.488    ,   1.521    ]
 V              27.67       27.67      0.8236E-01  [  27.61    ,   27.73    ]
 F             0.9948      0.9962       3.757      [ 0.9000    ,   1.092    ]
 KA2            2.801       2.801      0.3086      [  2.779    ,   2.823    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.60     -0.00      1.00
 F          -0.00      0.00      0.00      1.00
 KA2        -0.27     -0.00      0.56      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.165E-06
 KA1       0.151E-08 0.431E-04
 V         -.556E-05 -.199E-06 0.519E-03
 F         -.297E-07 0.776E-06 0.259E-05 0.140E-02
 KA2       -.947E-06 -.743E-07 0.111E-03 0.512E-06 0.747E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.77        17.78       -0.7607E-02   0.7329E-03
      3       1.000        20.24        20.23        0.1014E-01   0.2895E-03
      4       1.500        19.10        19.11       -0.1441E-01   0.4661E-03
      5       2.000        17.29        17.31       -0.1629E-01   0.8414E-03
      6       3.000        13.87        13.83        0.4136E-01   0.1872E-02
      7       4.000        11.02        10.99        0.2530E-01   0.3014E-02
      8       6.000        6.940        6.945       -0.4609E-02   0.5114E-02
      9       8.000        4.380        4.386       -0.6295E-02   0.6725E-02
     10       10.00        2.760        2.770       -0.1044E-01   0.7856E-02
     11       12.00        1.740        1.750       -0.9841E-02   0.8616E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.78       0.2015E-01  -0.2833    
                3       20.23       0.1167E-01   0.5943    
                4       19.11       0.1256E-01  -0.6688    
                5       17.31       0.1329E-01  -0.5626    
                6       13.83       0.1324E-01   0.9554    
                7       10.99       0.1342E-01   0.4606    
                8       6.945       0.1319E-01  -0.6459E-01
                9       4.386       0.1164E-01  -0.7684E-01
               10       2.770       0.9518E-02  -0.1178    
               11       1.750       0.7399E-02  -0.1060    

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.343    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1719      [ 0.2287    ,  0.2307    ]
 KA1            1.504       1.504      0.4375      [  1.488    ,   1.521    ]
 V              25.52       25.52      0.6379E-01  [  25.48    ,   25.57    ]
 F             0.9948      0.9961       3.763      [ 0.8997    ,   1.092    ]
 KA2            2.802       2.802      0.2467      [  2.784    ,   2.820    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.72     -0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.37     -0.00      0.66     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.156E-06
 KA1       0.377E-08 0.433E-04
 V         -.465E-05 -.195E-06 0.265E-03
 F         0.741E-08 -.525E-06 -.619E-06 0.140E-02
 KA2       -.100E-05 -.289E-07 0.746E-04 -.177E-06 0.478E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.26        19.27       -0.1310E-01   0.4384E-03
      3       1.000        21.94        21.93        0.1008E-01   0.1008E-03
      4       1.500        20.70        20.72       -0.2014E-01   0.2251E-03
      5       2.000        18.75        18.76       -0.1007E-01   0.5310E-03
      6       3.000        15.04        14.99        0.4941E-01   0.1483E-02
      7       4.000        11.95        11.92        0.3114E-01   0.2612E-02
      8       6.000        7.530        7.529        0.1217E-02   0.4777E-02
      9       8.000        4.750        4.756       -0.5546E-02   0.6479E-02
     10       10.00        3.000        3.004       -0.3836E-02   0.7687E-02
     11       12.00        1.880        1.897       -0.1737E-01   0.8504E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.27       0.1598E-01  -0.6279    
                3       21.93       0.7790E-02    1.001    
                4       20.72       0.9091E-02   -1.344    
                5       18.76       0.1024E-01  -0.4378    
                6       14.99       0.1144E-01    1.283    
                7       11.92       0.1266E-01   0.6090    
                8       7.529       0.1336E-01   0.1745E-01
                9       4.756       0.1204E-01  -0.6899E-01
               10       3.004       0.9930E-02  -0.4380E-01
               11       1.897       0.7751E-02  -0.1884    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.636    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1759      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4362      [  1.488    ,   1.521    ]
 V              27.10       27.10      0.7753E-01  [  27.05    ,   27.16    ]
 F             0.9948      0.9962       3.756      [ 0.9000    ,   1.092    ]
 KA2            2.801       2.801      0.2938      [  2.780    ,   2.822    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.63      0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.29      0.00      0.58     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.163E-06
 KA1       -.412E-08 0.431E-04
 V         -.533E-05 0.480E-06 0.442E-03
 F         0.274E-08 -.277E-06 -.112E-05 0.140E-02
 KA2       -.960E-06 0.604E-07 0.101E-03 -.291E-06 0.677E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.14        18.15       -0.7517E-02   0.6531E-03
      3       1.000        20.66        20.65        0.8885E-02   0.2336E-03
      4       1.500        19.50        19.51       -0.1266E-01   0.3982E-03
      5       2.000        17.65        17.67       -0.1703E-01   0.7577E-03
      6       3.000        14.16        14.12        0.4289E-01   0.1771E-02
      7       4.000        11.25        11.22        0.2578E-01   0.2911E-02
      8       6.000        7.090        7.090        0.2101E-03   0.5029E-02
      9       8.000        4.470        4.478       -0.8126E-02   0.6663E-02
     10       10.00        2.820        2.829       -0.8521E-02   0.7814E-02
     11       12.00        1.780        1.787       -0.6582E-02   0.8588E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.15       0.1919E-01  -0.2965    
                3       20.65       0.1075E-01   0.5793    
                4       19.51       0.1175E-01  -0.6357    
                5       17.67       0.1259E-01  -0.6194    
                6       14.12       0.1283E-01    1.019    
                7       11.22       0.1326E-01   0.4776    
                8       7.090       0.1326E-01   0.2819E-02
                9       4.478       0.1177E-01  -0.9963E-01
               10       2.829       0.9645E-02  -0.9645E-01
               11       1.787       0.7506E-02  -0.7105E-01

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.735    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1705      [ 0.2288    ,  0.2308    ]
 KA1            1.504       1.504      0.4368      [  1.488    ,   1.521    ]
 V              25.30       25.30      0.6170E-01  [  25.26    ,   25.34    ]
 F             0.9948      0.9961       3.765      [ 0.8997    ,   1.092    ]
 KA2            2.803       2.803      0.2400      [  2.786    ,   2.820    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.74     -0.00      1.00
 F          -0.00      0.00     -0.00      1.00
 KA2        -0.38     -0.00      0.68     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.154E-06
 KA1       0.654E-09 0.432E-04
 V         -.452E-05 -.924E-07 0.244E-03
 F         -.108E-07 0.693E-06 -.360E-06 0.141E-02
 KA2       -.100E-05 -.201E-07 0.710E-04 -.464E-08 0.452E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.43        19.44       -0.1364E-01   0.4096E-03
      3       1.000        22.13        22.12        0.9450E-02   0.8570E-04
      4       1.500        20.88        20.90       -0.1823E-01   0.2037E-03
      5       2.000        18.91        18.92       -0.1004E-01   0.5012E-03
      6       3.000        15.16        15.12        0.4314E-01   0.1443E-02
      7       4.000        12.04        12.02        0.2186E-01   0.2570E-02
      8       6.000        7.580        7.590       -0.1008E-01   0.4742E-02
      9       8.000        4.770        4.793       -0.2338E-01   0.6454E-02
     10       10.00        3.010        3.027       -0.1717E-01   0.7671E-02
     11       12.00        1.880        1.912       -0.3176E-01   0.8493E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.44       0.1548E-01  -0.6763    
                3       22.12       0.7303E-02    1.018    
                4       20.90       0.8662E-02   -1.279    
                5       18.92       0.9863E-02  -0.4495    
                6       15.12       0.1121E-01    1.135    
                7       12.02       0.1254E-01   0.4310    
                8       7.590       0.1332E-01  -0.1466    
                9       4.793       0.1203E-01  -0.2911    
               10       3.027       0.9923E-02  -0.1961    
               11       1.912       0.7747E-02  -0.3446    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.872    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1669      [ 0.2288    ,  0.2308    ]
 KA1            1.504       1.504      0.4371      [  1.488    ,   1.521    ]
 V              24.36       24.36      0.5305E-01  [  24.33    ,   24.40    ]
 F             0.9948      0.9962       3.763      [ 0.8998    ,   1.093    ]
 KA2            2.803       2.803      0.2058      [  2.788    ,   2.818    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.81     -0.00      1.00
 F           0.00      0.00     -0.00      1.00
 KA2        -0.45      0.00      0.75     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.147E-06
 KA1       0.103E-08 0.432E-04
 V         -.402E-05 -.370E-07 0.167E-03
 F         0.979E-08 0.501E-07 -.999E-06 0.141E-02
 KA2       -.991E-06 0.206E-07 0.557E-04 -.438E-06 0.333E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.18        20.19       -0.1472E-01   0.2944E-03
      3       1.000        22.98        22.97        0.5277E-02   0.3310E-04
      4       1.500        21.69        21.71       -0.1506E-01   0.1202E-03
      5       2.000        19.64        19.65       -0.1044E-01   0.3760E-03
      6       3.000        15.75        15.70        0.4959E-01   0.1267E-02
      7       4.000        12.51        12.48        0.2795E-01   0.2381E-02
      8       6.000        7.870        7.883       -0.1306E-01   0.4578E-02
      9       8.000        4.960        4.978       -0.1840E-01   0.6333E-02
     10       10.00        3.120        3.144       -0.2401E-01   0.7587E-02
     11       12.00        1.950        1.986       -0.3554E-01   0.8437E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.19       0.1283E-01  -0.8603    
                3       22.97       0.4966E-02   0.9141    
                4       21.71       0.6718E-02   -1.375    
                5       19.65       0.8214E-02  -0.5392    
                6       15.70       0.1037E-01    1.393    
                7       12.48       0.1223E-01   0.5725    
                8       7.883       0.1339E-01  -0.1932    
                9       4.978       0.1218E-01  -0.2313    
               10       3.144       0.1008E-01  -0.2757    
               11       1.986       0.7874E-02  -0.3870    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.579    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1763      [ 0.2287    ,  0.2308    ]
 KA1            1.504       1.504      0.4362      [  1.488    ,   1.521    ]
 V              27.41       27.41      0.8032E-01  [  27.35    ,   27.47    ]
 F             0.9948      0.9961       3.755      [ 0.8999    ,   1.092    ]
 KA2            2.800       2.800      0.3015      [  2.778    ,   2.822    ]


 SDslope       -.4102E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.61      0.00      1.00
 F          -0.00     -0.00      0.00      1.00
 KA2        -0.28     -0.00      0.57      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.164E-06
 KA1       -.349E-08 0.431E-04
 V         -.548E-05 0.123E-06 0.485E-03
 F         -.119E-08 -.251E-06 0.108E-06 0.140E-02
 KA2       -.956E-06 -.518E-08 0.106E-03 0.175E-06 0.712E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.93        17.94       -0.1124E-01   0.6971E-03
      3       1.000        20.43        20.42        0.1163E-01   0.2637E-03
      4       1.500        19.28        19.29       -0.1336E-01   0.4349E-03
      5       2.000        17.45        17.47       -0.1846E-01   0.8032E-03
      6       3.000        14.00        13.96        0.4207E-01   0.1827E-02
      7       4.000        11.12        11.10        0.2286E-01   0.2968E-02
      8       6.000        7.000        7.009       -0.8847E-02   0.5076E-02
      9       8.000        4.410        4.427       -0.1657E-01   0.6698E-02
     10       10.00        2.770        2.796       -0.2569E-01   0.7838E-02
     11       12.00        1.740        1.766       -0.2567E-01   0.8604E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.94       0.1971E-01  -0.4282    
                3       20.42       0.1128E-01   0.7143    
                4       19.29       0.1220E-01  -0.6423    
                5       17.47       0.1297E-01  -0.6522    
                6       13.96       0.1303E-01   0.9839    
                7       11.10       0.1332E-01   0.4194    
                8       7.009       0.1320E-01  -0.1243    
                9       4.427       0.1168E-01  -0.2026    
               10       2.796       0.9561E-02  -0.2902    
               11       1.766       0.7436E-02  -0.2768    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 14:02:16 2018

 Data file name: data_null.csv

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    3000

 Total number of EM iterations:   30

 Normal distribution option

 -2logLikelihood:   -778.435    

 Model Selection Criteria
  AIC:       -756.435    
  BIC:       -717.100    

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KE          0.230       0.594         0.407E-03   0.177       0.199E+04
  KA1          1.50        3.91         0.560E-02   0.372       0.572E+04
  V            26.1        20.3          1.21        4.64        55.2    
  F           0.997        19.1         0.361E-01    3.62        131.    
  KA2          2.80        3.01         0.115E-01   0.411       0.381E+04

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KE        KA1       V         F         KA2       
 KE        0.166E-06
 KA1        0.00     0.313E-04
 V          0.00      0.00      1.47    
 F          0.00      0.00      0.00     0.130E-02
 KA2        0.00      0.00      0.00      0.00     0.132E-03

  Standard Errors of Estimated Covariance Matrix:

           KE        KA1       V         F         KA2       
 KE         0.66E-05
 KA1        -1.0      0.36E-02
 V          -1.0      -1.0       1.6    
 F          -1.0      -1.0      -1.0      0.34E-02
 KA2        -1.0      -1.0      -1.0      -1.0      0.10E-01

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope    -0.411E-02   18.4    
  SDinter     0.100      Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  1) =  0.2297765         ! KE        
       Pmean(  2) =   1.504670         ! KA1       
       Pmean(  3) =   26.11166         ! V         
       Pmean(  4) =  0.9972486         ! F         
       Pmean(  5) =   2.801321         ! KA2       
 
       Pcov(  1,  1) =  0.1658122E-06  ! KE         & KE        
       Pcov(  2,  1) =   0.000000      ! KA1        & KE        
       Pcov(  2,  2) =  0.3134285E-04  ! KA1        & KA1       
       Pcov(  3,  1) =   0.000000      ! V          & KE        
       Pcov(  3,  2) =   0.000000      ! V          & KA1       
       Pcov(  3,  3) =   1.468457      ! V          & V         
       Pcov(  4,  1) =   0.000000      ! F          & KE        
       Pcov(  4,  2) =   0.000000      ! F          & KA1       
       Pcov(  4,  3) =   0.000000      ! F          & V         
       Pcov(  4,  4) =  0.1300578E-02  ! F          & F         
       Pcov(  5,  1) =   0.000000      ! KA2        & KE        
       Pcov(  5,  2) =   0.000000      ! KA2        & KA1       
       Pcov(  5,  3) =   0.000000      ! KA2        & V         
       Pcov(  5,  4) =   0.000000      ! KA2        & F         
       Pcov(  5,  5) =  0.1323745E-03  ! KA2        & KA2       

      ________________________________________


 List of Files Created

  Record of program run and all results:
    B.run
  Summary of population estimates at each iteration:
    BIT.csv
  Individual subject estimates at final iteration:
    BIND.csv
  Table of predictions and residuals for each subject:
    BRSD.csv
  Information for plotting model predictions for each subject:
    BPLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    B.eps
  Command file for subsequent Batch runs:
    B.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:02:18 2018

