
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:59:45 2018


 Enter file name for storing session run (*.run): E.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Enter the data file name (*.dat): data_null.csv

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Enter parameter file name (*.prm or *IND.csv):  param_null.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           y
 KA1         2.000           y
 V           21.00           y
 F          0.8000           y
 KA2         2.000           y
 SDinter    0.1000           n
 SDslope    0.1000           y

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  2

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  1

 Enter number of samples/EM iteration (1000 -   3000):      3000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.263    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1911      [ 0.2287    ,  0.2310    ]
 KA1            1.506       1.506      0.3662      [  1.492    ,   1.520    ]
 V              25.76       25.87       4.457      [  22.91    ,   28.84    ]
 F             0.9801      0.9845       4.461      [ 0.8716    ,   1.097    ]
 KA2            2.798       2.799      0.4876      [  2.764    ,   2.835    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.43      1.00
 V           0.16      0.08      1.00
 F           0.18      0.05      1.00      1.00
 KA2        -0.33      0.14     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.193E-06
 KA1       -.103E-05 0.304E-04
 V         0.804E-04 0.485E-03  1.33    
 F         0.342E-05 0.133E-04 0.506E-01 0.193E-02
 KA2       -.196E-05 0.105E-04 -.108E-02 -.449E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.20        13.22       -0.1719E-01   0.2103E-02
      3       1.000        18.00        18.01       -0.7486E-02   0.6882E-03
      4       1.500        19.00        18.98        0.1539E-01   0.4942E-03
      5       2.000        18.30        18.30       -0.4635E-02   0.6258E-03
      6       3.000        15.40        15.43       -0.3232E-01   0.1353E-02
      7       4.000        12.50        12.46        0.3979E-01   0.2397E-02
      8       6.000        7.920        7.913        0.7011E-02   0.4568E-02
      9       8.000        5.000        4.999        0.7399E-03   0.6324E-02
     10       10.00        3.160        3.157        0.2841E-02   0.7581E-02
     11       12.00        1.990        1.994       -0.3764E-02   0.8433E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.22       0.2270E-01  -0.3759    
                3       18.01       0.1748E-01  -0.2872    
                4       18.98       0.1327E-01   0.6908    
                5       18.30       0.1491E-01  -0.1868    
                6       15.43       0.1783E-01  -0.8796    
                7       12.46       0.1717E-01   0.8123    
                8       7.913       0.1463E-01   0.1035    
                9       4.999       0.1252E-01   0.9203E-02
               10       3.157       0.1030E-01   0.3258E-01
               11       1.994       0.8117E-02  -0.4102E-01

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.842    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1903      [ 0.2287    ,  0.2310    ]
 KA1            1.505       1.506      0.3446      [  1.492    ,   1.519    ]
 V              25.57       25.68       4.448      [  22.74    ,   28.62    ]
 F              1.002       1.007       4.453      [ 0.8913    ,   1.122    ]
 KA2            2.798       2.799      0.4882      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.44      1.00
 V           0.16      0.06      1.00
 F           0.18      0.04      1.00      1.00
 KA2        -0.33      0.14     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.191E-06
 KA1       -.101E-05 0.269E-04
 V         0.792E-04 0.373E-03  1.30    
 F         0.347E-05 0.984E-05 0.512E-01 0.201E-02
 KA2       -.195E-05 0.103E-04 -.105E-02 -.450E-04 0.187E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.60        13.61       -0.1310E-01   0.1957E-02
      3       1.000        18.54        18.55       -0.7781E-02   0.5770E-03
      4       1.500        19.57        19.55        0.1509E-01   0.3958E-03
      5       2.000        18.85        18.85       -0.4956E-02   0.5181E-03
      6       3.000        15.86        15.90       -0.3667E-01   0.1217E-02
      7       4.000        12.88        12.84        0.4478E-01   0.2249E-02
      8       6.000        8.160        8.151        0.8891E-02   0.4437E-02
      9       8.000        5.150        5.150        0.3518E-03   0.6226E-02
     10       10.00        3.250        3.252       -0.2098E-02   0.7513E-02
     11       12.00        2.050        2.054       -0.3697E-02   0.8388E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.61       0.2166E-01  -0.2972    
                3       18.55       0.1636E-01  -0.3259    
                4       19.55       0.1213E-01   0.7571    
                5       18.85       0.1382E-01  -0.2192    
                6       15.90       0.1684E-01   -1.052    
                7       12.84       0.1643E-01   0.9438    
                8       8.151       0.1445E-01   0.1333    
                9       5.150       0.1261E-01   0.4354E-02
               10       3.252       0.1047E-01  -0.2426E-01
               11       2.054       0.8281E-02  -0.4040E-01

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.421    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1919      [ 0.2287    ,  0.2309    ]
 KA1            1.506       1.506      0.3872      [  1.491    ,   1.521    ]
 V              25.94       26.07       4.461      [  23.08    ,   29.06    ]
 F             0.9573      0.9622       4.464      [ 0.8517    ,   1.073    ]
 KA2            2.798       2.800      0.4874      [  2.765    ,   2.835    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.41      1.00
 V           0.16      0.09      1.00
 F           0.18      0.07      1.00      1.00
 KA2        -0.33      0.13     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.194E-06
 KA1       -.106E-05 0.340E-04
 V         0.810E-04 0.620E-03  1.35    
 F         0.335E-05 0.174E-04 0.499E-01 0.184E-02
 KA2       -.196E-05 0.107E-04 -.106E-02 -.428E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.80        12.82       -0.2102E-01   0.2254E-02
      3       1.000        17.46        17.47       -0.7314E-02   0.8092E-03
      4       1.500        18.43        18.41        0.1515E-01   0.6034E-03
      5       2.000        17.75        17.76       -0.5122E-02   0.7435E-03
      6       3.000        14.94        14.97       -0.2898E-01   0.1496E-02
      7       4.000        12.13        12.09        0.4382E-01   0.2549E-02
      8       6.000        7.680        7.676        0.4357E-02   0.4700E-02
      9       8.000        4.850        4.849        0.5586E-03   0.6422E-02
     10       10.00        3.070        3.063        0.7371E-02   0.7648E-02
     11       12.00        1.930        1.934       -0.4121E-02   0.8478E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.82       0.2367E-01  -0.4437    
                3       17.47       0.1856E-01  -0.2589    
                4       18.41       0.1439E-01   0.6155    
                5       17.76       0.1595E-01  -0.1892    
                6       14.97       0.1872E-01  -0.7501    
                7       12.09       0.1784E-01   0.8674    
                8       7.676       0.1480E-01   0.6337E-01
                9       4.849       0.1243E-01   0.6872E-02
               10       3.063       0.1014E-01   0.8423E-01
               11       1.934       0.7952E-02  -0.4479E-01

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.506    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1926      [ 0.2287    ,  0.2310    ]
 KA1            1.506       1.506      0.4015      [  1.491    ,   1.522    ]
 V              26.08       26.21       4.462      [  23.21    ,   29.22    ]
 F             0.9428      0.9477       4.465      [ 0.8389    ,   1.056    ]
 KA2            2.799       2.800      0.4888      [  2.765    ,   2.835    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.40      1.00
 V           0.16      0.10      1.00
 F           0.18      0.08      1.00      1.00
 KA2        -0.33      0.13     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.196E-06
 KA1       -.107E-05 0.366E-04
 V         0.820E-04 0.704E-03  1.37    
 F         0.333E-05 0.197E-04 0.495E-01 0.179E-02
 KA2       -.200E-05 0.109E-04 -.107E-02 -.425E-04 0.187E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.54        12.56       -0.1927E-01   0.2357E-02
      3       1.000        17.10        17.11       -0.9586E-02   0.8947E-03
      4       1.500        18.05        18.04        0.1317E-01   0.6819E-03
      5       2.000        17.39        17.39       -0.4661E-04   0.8273E-03
      6       3.000        14.63        14.66       -0.3060E-01   0.1596E-02
      7       4.000        11.88        11.84        0.4302E-01   0.2653E-02
      8       6.000        7.520        7.517        0.2712E-02   0.4789E-02
      9       8.000        4.750        4.749        0.6325E-03   0.6487E-02
     10       10.00        3.000        2.999        0.5860E-03   0.7694E-02
     11       12.00        1.890        1.894       -0.4191E-02   0.8508E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.56       0.2433E-01  -0.3979    
                3       17.11       0.1932E-01  -0.3222    
                4       18.04       0.1514E-01   0.5029    
                5       17.39       0.1660E-01  -0.2986E-02
                6       14.66       0.1926E-01  -0.7670    
                7       11.84       0.1824E-01   0.8347    
                8       7.517       0.1490E-01   0.3900E-01
                9       4.749       0.1238E-01   0.7756E-02
               10       2.999       0.1004E-01   0.6628E-02
               11       1.894       0.7848E-02  -0.4547E-01

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.389    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.1895      [ 0.2287    ,  0.2310    ]
 KA1            1.505       1.505      0.3290      [  1.492    ,   1.517    ]
 V              25.43       25.53       4.443      [  22.62    ,   28.45    ]
 F              1.017       1.021       4.449      [ 0.9038    ,   1.137    ]
 KA2            2.797       2.799      0.4879      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.46      1.00
 V           0.16      0.05      1.00
 F           0.18      0.03      1.00      1.00
 KA2        -0.32      0.15     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.190E-06
 KA1       -.982E-06 0.245E-04
 V         0.787E-04 0.301E-03  1.29    
 F         0.350E-05 0.754E-05 0.515E-01 0.206E-02
 KA2       -.193E-05 0.995E-05 -.102E-02 -.443E-04 0.187E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.86        13.87       -0.1498E-01   0.1863E-02
      3       1.000        18.90        18.91       -0.7201E-02   0.5084E-03
      4       1.500        19.95        19.94        0.1416E-01   0.3361E-03
      5       2.000        19.22        19.22       -0.3585E-02   0.4516E-03
      6       3.000        16.17        16.21       -0.3864E-01   0.1129E-02
      7       4.000        13.13        13.09        0.4260E-01   0.2152E-02
      8       6.000        8.320        8.311        0.8811E-02   0.4350E-02
      9       8.000        5.250        5.251       -0.6569E-03   0.6161E-02
     10       10.00        3.320        3.316        0.4199E-02   0.7468E-02
     11       12.00        2.090        2.094       -0.3871E-02   0.8358E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.87       0.2084E-01  -0.3480    
                3       18.91       0.1556E-01  -0.3213    
                4       19.94       0.1135E-01   0.7706    
                5       19.22       0.1307E-01  -0.1702    
                6       16.21       0.1615E-01   -1.151    
                7       13.09       0.1592E-01   0.9179    
                8       8.311       0.1433E-01   0.1334    
                9       5.251       0.1266E-01  -0.8476E-02
               10       3.316       0.1057E-01   0.4853E-01
               11       2.094       0.8386E-02  -0.4238E-01

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -30.672    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1880      [ 0.2287    ,  0.2310    ]
 KA1            1.506       1.506      0.3064      [  1.494    ,   1.518    ]
 V              25.31       25.40       4.433      [  22.50    ,   28.29    ]
 F              1.040       1.044       4.440      [ 0.9246    ,   1.163    ]
 KA2            2.797       2.799      0.4871      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.48      1.00
 V           0.16      0.04      1.00
 F           0.18      0.02      1.00      1.00
 KA2        -0.32      0.15     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.187E-06
 KA1       -.947E-06 0.213E-04
 V         0.776E-04 0.200E-03  1.27    
 F         0.355E-05 0.411E-05 0.522E-01 0.215E-02
 KA2       -.190E-05 0.957E-05 -.105E-02 -.469E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        14.26        14.27       -0.1400E-01   0.1725E-02
      3       1.000        19.44        19.45       -0.7766E-02   0.4135E-03
      4       1.500        20.52        20.50        0.1668E-01   0.2563E-03
      5       2.000        19.76        19.77       -0.9045E-02   0.3617E-03
      6       3.000        16.63        16.67       -0.3682E-01   0.1007E-02
      7       4.000        13.50        13.46        0.4331E-01   0.2014E-02
      8       6.000        8.550        8.545        0.4634E-02   0.4224E-02
      9       8.000        5.400        5.398        0.1521E-02   0.6066E-02
     10       10.00        3.410        3.409        0.9183E-03   0.7402E-02
     11       12.00        2.150        2.153       -0.2733E-02   0.8314E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       14.27       0.1957E-01  -0.3380    
                3       19.45       0.1430E-01  -0.3840    
                4       20.50       0.1018E-01    1.040    
                5       19.77       0.1197E-01  -0.4772    
                6       16.67       0.1514E-01   -1.161    
                7       13.46       0.1517E-01   0.9647    
                8       8.545       0.1416E-01   0.7110E-01
                9       5.398       0.1275E-01   0.1942E-01
               10       3.409       0.1073E-01   0.1061E-01
               11       2.153       0.8534E-02  -0.3000E-01

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.372    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1934      [ 0.2287    ,  0.2309    ]
 KA1            1.507       1.507      0.4220      [  1.491    ,   1.523    ]
 V              26.29       26.44       4.478      [  23.39    ,   29.48    ]
 F             0.9202      0.9255       4.479      [ 0.8189    ,   1.032    ]
 KA2            2.799       2.800      0.4881      [  2.765    ,   2.835    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.39      1.00
 V           0.16      0.11      1.00
 F           0.18      0.09      1.00      1.00
 KA2        -0.33      0.13     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.198E-06
 KA1       -.109E-05 0.404E-04
 V         0.837E-04 0.855E-03  1.40    
 F         0.329E-05 0.238E-04 0.491E-01 0.172E-02
 KA2       -.200E-05 0.110E-04 -.107E-02 -.412E-04 0.187E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.14        12.16       -0.2453E-01   0.2517E-02
      3       1.000        16.56        16.57       -0.1022E-01   0.1032E-02
      4       1.500        17.48        17.47        0.1299E-01   0.8093E-03
      5       2.000        16.84        16.84        0.1406E-03   0.9620E-03
      6       3.000        14.17        14.20       -0.2609E-01   0.1751E-02
      7       4.000        11.50        11.46        0.3819E-01   0.2814E-02
      8       6.000        7.290        7.279        0.1086E-01   0.4925E-02
      9       8.000        4.600        4.599        0.9691E-03   0.6587E-02
     10       10.00        2.910        2.905        0.5448E-02   0.7762E-02
     11       12.00        1.830        1.834       -0.4336E-02   0.8554E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.16       0.2511E-01  -0.4900    
                3       16.57       0.2028E-01  -0.3198    
                4       17.47       0.1620E-01   0.4552    
                5       16.84       0.1760E-01   0.3213E-02
                6       14.20       0.2008E-01  -0.6245    
                7       11.46       0.1885E-01   0.7194    
                8       7.279       0.1507E-01   0.1545    
                9       4.599       0.1230E-01   0.1185E-01
               10       2.905       0.9881E-02   0.6179E-01
               11       1.834       0.7690E-02  -0.4691E-01

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.987    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1922      [ 0.2287    ,  0.2310    ]
 KA1            1.506       1.507      0.3947      [  1.491    ,   1.522    ]
 V              26.03       26.16       4.461      [  23.16    ,   29.16    ]
 F             0.9507      0.9555       4.464      [ 0.8458    ,   1.065    ]
 KA2            2.798       2.800      0.4893      [  2.764    ,   2.835    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.41      1.00
 V           0.16      0.09      1.00
 F           0.18      0.07      1.00      1.00
 KA2        -0.33      0.13     -0.07     -0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.195E-06
 KA1       -.107E-05 0.354E-04
 V         0.805E-04 0.653E-03  1.36    
 F         0.330E-05 0.182E-04 0.498E-01 0.182E-02
 KA2       -.198E-05 0.109E-04 -.110E-02 -.438E-04 0.188E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.67        12.69       -0.2110E-01   0.2305E-02
      3       1.000        17.28        17.29       -0.8593E-02   0.8514E-03
      4       1.500        18.24        18.23        0.1493E-01   0.6422E-03
      5       2.000        17.57        17.57       -0.1192E-02   0.7852E-03
      6       3.000        14.78        14.81       -0.3295E-01   0.1546E-02
      7       4.000        12.00        11.96        0.4017E-01   0.2602E-02
      8       6.000        7.600        7.595        0.4805E-02   0.4745E-02
      9       8.000        4.800        4.799        0.1465E-02   0.6455E-02
     10       10.00        3.030        3.030       -0.4318E-03   0.7671E-02
     11       12.00        1.910        1.914       -0.3759E-02   0.8494E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.69       0.2405E-01  -0.4406    
                3       17.29       0.1899E-01  -0.2963    
                4       18.23       0.1479E-01   0.5879    
                5       17.57       0.1628E-01  -0.4390E-01
                6       14.81       0.1898E-01  -0.8391    
                7       11.96       0.1802E-01   0.7870    
                8       7.595       0.1484E-01   0.6956E-01
                9       4.799       0.1239E-01   0.1814E-01
               10       3.030       0.1008E-01  -0.4985E-02
               11       1.914       0.7893E-02  -0.4082E-01

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.012    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1898      [ 0.2287    ,  0.2310    ]
 KA1            1.505       1.505      0.3364      [  1.492    ,   1.518    ]
 V              25.51       25.61       4.448      [  22.68    ,   28.54    ]
 F              1.010       1.014       4.454      [ 0.8976    ,   1.130    ]
 KA2            2.798       2.799      0.4870      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.45      1.00
 V           0.16      0.06      1.00
 F           0.18      0.04      1.00      1.00
 KA2        -0.32      0.15     -0.07     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.190E-06
 KA1       -.992E-06 0.257E-04
 V         0.798E-04 0.330E-03  1.30    
 F         0.352E-05 0.845E-05 0.514E-01 0.204E-02
 KA2       -.193E-05 0.100E-04 -.102E-02 -.439E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.73        13.74       -0.1423E-01   0.1909E-02
      3       1.000        18.72        18.73       -0.6996E-02   0.5422E-03
      4       1.500        19.76        19.74        0.1571E-01   0.3655E-03
      5       2.000        19.03        19.04       -0.7857E-02   0.4846E-03
      6       3.000        16.02        16.05       -0.3117E-01   0.1173E-02
      7       4.000        13.00        12.96        0.3992E-01   0.2201E-02
      8       6.000        8.240        8.230        0.9545E-02   0.4394E-02
      9       8.000        5.200        5.200        0.2050E-03   0.6194E-02
     10       10.00        3.290        3.284        0.6223E-02   0.7491E-02
     11       12.00        2.070        2.074       -0.3709E-02   0.8373E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.74       0.2122E-01  -0.3266    
                3       18.73       0.1594E-01  -0.3024    
                4       19.74       0.1175E-01   0.8203    
                5       19.04       0.1347E-01  -0.3585    
                6       16.05       0.1652E-01  -0.9112    
                7       12.96       0.1620E-01   0.8506    
                8       8.230       0.1440E-01   0.1438    
                9       5.200       0.1264E-01   0.2500E-02
               10       3.284       0.1052E-01   0.7184E-01
               11       2.074       0.8332E-02  -0.4056E-01

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.652    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1903      [ 0.2288    ,  0.2310    ]
 KA1            1.505       1.506      0.3448      [  1.492    ,   1.519    ]
 V              25.61       25.72       4.447      [  22.78    ,   28.66    ]
 F              1.003       1.007       4.452      [ 0.8917    ,   1.122    ]
 KA2            2.797       2.799      0.4877      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.44      1.00
 V           0.16      0.06      1.00
 F           0.18      0.04      1.00      1.00
 KA2        -0.33      0.14     -0.07     -0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.191E-06
 KA1       -.101E-05 0.270E-04
 V         0.798E-04 0.380E-03  1.31    
 F         0.349E-05 0.101E-04 0.512E-01 0.201E-02
 KA2       -.194E-05 0.102E-04 -.111E-02 -.471E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1874E-01   0.1962E-02
      3       1.000        18.52        18.53       -0.7785E-02   0.5809E-03
      4       1.500        19.55        19.53        0.1665E-01   0.3993E-03
      5       2.000        18.83        18.83       -0.3710E-02   0.5221E-03
      6       3.000        15.84        15.88       -0.3796E-01   0.1222E-02
      7       4.000        12.86        12.82        0.4055E-01   0.2255E-02
      8       6.000        8.140        8.140       -0.2529E-03   0.4443E-02
      9       8.000        5.130        5.142       -0.1226E-01   0.6231E-02
     10       10.00        3.230        3.247       -0.1709E-01   0.7517E-02
     11       12.00        2.030        2.050       -0.2032E-01   0.8391E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.2166E-01  -0.4242    
                3       18.53       0.1638E-01  -0.3249    
                4       19.53       0.1217E-01   0.8315    
                5       18.83       0.1385E-01  -0.1639    
                6       15.88       0.1686E-01   -1.087    
                7       12.82       0.1644E-01   0.8534    
                8       8.140       0.1444E-01  -0.3986E-02
                9       5.142       0.1259E-01  -0.1554    
               10       3.247       0.1046E-01  -0.1972    
               11       2.050       0.8270E-02  -0.2219    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.187    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1893      [ 0.2288    ,  0.2310    ]
 KA1            1.505       1.505      0.3300      [  1.492    ,   1.518    ]
 V              25.48       25.57       4.439      [  22.65    ,   28.49    ]
 F              1.017       1.021       4.444      [ 0.9043    ,   1.138    ]
 KA2            2.797       2.799      0.4870      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.46      1.00
 V           0.16      0.06      1.00
 F           0.18      0.04      1.00      1.00
 KA2        -0.32      0.15     -0.06     -0.07      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.189E-06
 KA1       -.984E-06 0.247E-04
 V         0.780E-04 0.314E-03  1.29    
 F         0.347E-05 0.801E-05 0.515E-01 0.206E-02
 KA2       -.192E-05 0.998E-05 -.998E-03 -.435E-04 0.186E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.84        13.86       -0.2064E-01   0.1868E-02
      3       1.000        18.88        18.89       -0.7273E-02   0.5121E-03
      4       1.500        19.93        19.91        0.1561E-01   0.3394E-03
      5       2.000        19.20        19.20       -0.2451E-02   0.4553E-03
      6       3.000        16.15        16.19       -0.4002E-01   0.1134E-02
      7       4.000        13.11        13.07        0.3831E-01   0.2158E-02
      8       6.000        8.300        8.300       -0.3321E-03   0.4356E-02
      9       8.000        5.230        5.243       -0.1324E-01   0.6166E-02
     10       10.00        3.300        3.311       -0.1076E-01   0.7471E-02
     11       12.00        2.070        2.090       -0.2047E-01   0.8361E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.86       0.2088E-01  -0.4785    
                3       18.89       0.1559E-01  -0.3233    
                4       19.91       0.1140E-01   0.8457    
                5       19.20       0.1313E-01  -0.1164    
                6       16.19       0.1622E-01   -1.189    
                7       13.07       0.1597E-01   0.8243    
                8       8.300       0.1433E-01  -0.5225E-02
                9       5.243       0.1265E-01  -0.1687    
               10       3.311       0.1055E-01  -0.1246    
               11       2.090       0.8368E-02  -0.2239    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.593    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1904      [ 0.2288    ,  0.2310    ]
 KA1            1.505       1.506      0.3448      [  1.492    ,   1.519    ]
 V              25.62       25.72       4.448      [  22.78    ,   28.66    ]
 F              1.003       1.007       4.453      [ 0.8918    ,   1.122    ]
 KA2            2.797       2.799      0.4880      [  2.764    ,   2.834    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.44      1.00
 V           0.16      0.06      1.00
 F           0.18      0.04      1.00      1.00
 KA2        -0.33      0.14     -0.07     -0.08      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.192E-06
 KA1       -.101E-05 0.270E-04
 V         0.802E-04 0.373E-03  1.31    
 F         0.350E-05 0.981E-05 0.513E-01 0.201E-02
 KA2       -.194E-05 0.102E-04 -.109E-02 -.465E-04 0.187E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1874E-01   0.1962E-02
      3       1.000        18.52        18.53       -0.7772E-02   0.5809E-03
      4       1.500        19.55        19.53        0.1667E-01   0.3993E-03
      5       2.000        18.83        18.83       -0.3662E-02   0.5221E-03
      6       3.000        15.84        15.88       -0.3786E-01   0.1222E-02
      7       4.000        12.86        12.82        0.4068E-01   0.2255E-02
      8       6.000        8.140        8.140       -0.8825E-04   0.4443E-02
      9       8.000        5.130        5.142       -0.1210E-01   0.6231E-02
     10       10.00        3.220        3.247       -0.2696E-01   0.7517E-02
     11       12.00        2.030        2.050       -0.2022E-01   0.8391E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.2167E-01  -0.4240    
                3       18.53       0.1639E-01  -0.3244    
                4       19.53       0.1218E-01   0.8328    
                5       18.83       0.1386E-01  -0.1618    
                6       15.88       0.1687E-01   -1.084    
                7       12.82       0.1645E-01   0.8562    
                8       8.140       0.1446E-01  -0.1517E-02
                9       5.142       0.1261E-01  -0.1534    
               10       3.247       0.1046E-01  -0.3110    
               11       2.050       0.8276E-02  -0.2208    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.769    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1806      [ 0.2287    ,  0.2308    ]
 KA1            1.512       1.510      0.6920      [  1.483    ,   1.537    ]
 V              26.29       26.29      0.7479E-01  [  26.24    ,   26.34    ]
 F             0.9942      0.9981       4.612      [ 0.8798    ,   1.116    ]
 KA2            2.801       2.801      0.2817      [  2.781    ,   2.821    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V          -0.72      0.22      1.00
 F           0.09     -0.18     -0.06      1.00
 KA2        -0.46      0.14      0.68     -0.04      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.172E-06
 KA1       -.127E-05 0.109E-03
 V         -.587E-05 0.444E-04 0.387E-03
 F         0.164E-05 -.843E-04 -.558E-04 0.212E-02
 KA2       -.151E-05 0.116E-04 0.105E-03 -.161E-04 0.622E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.70        18.71       -0.9097E-02   0.5457E-03
      3       1.000        21.30        21.29        0.9642E-02   0.1635E-03
      4       1.500        20.10        20.12       -0.1658E-01   0.3095E-03
      5       2.000        18.20        18.21       -0.1365E-01   0.6446E-03
      6       3.000        14.60        14.55        0.4650E-01   0.1631E-02
      7       4.000        11.60        11.57        0.2915E-01   0.2767E-02
      8       6.000        7.310        7.308        0.1679E-02   0.4909E-02
      9       8.000        4.610        4.616       -0.5890E-02   0.6576E-02
     10       10.00        2.910        2.915       -0.5369E-02   0.7754E-02
     11       12.00        1.830        1.841       -0.1133E-01   0.8548E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.71       0.1763E-01  -0.3918    
                3       21.29       0.9341E-02   0.7520    
                4       20.12       0.1049E-01  -0.9441    
                5       18.21       0.1117E-01  -0.5383    
                6       14.55       0.1156E-01    1.151    
                7       11.57       0.1248E-01   0.5539    
                8       7.308       0.1318E-01   0.2382E-01
                9       4.616       0.1197E-01  -0.7272E-01
               10       2.915       0.9915E-02  -0.6102E-01
               11       1.841       0.7766E-02  -0.1226    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.174    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1772      [ 0.2287    ,  0.2308    ]
 KA1            1.508       1.507      0.6905      [  1.481    ,   1.534    ]
 V              25.28       25.28      0.6548E-01  [  25.24    ,   25.32    ]
 F             0.9691      0.9718       4.607      [ 0.8567    ,   1.087    ]
 KA2            2.803       2.803      0.2499      [  2.785    ,   2.821    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V          -0.78      0.23      1.00
 F           0.08     -0.18     -0.06      1.00
 KA2        -0.49      0.15      0.73     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.166E-06
 KA1       -.123E-05 0.108E-03
 V         -.522E-05 0.393E-04 0.274E-03
 F         0.153E-05 -.838E-04 -.469E-04 0.200E-02
 KA2       -.141E-05 0.108E-04 0.843E-04 -.142E-04 0.491E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.45        19.46       -0.1127E-01   0.4112E-03
      3       1.000        22.15        22.14        0.8723E-02   0.8649E-04
      4       1.500        20.90        20.92       -0.1862E-01   0.2047E-03
      5       2.000        18.93        18.94       -0.9313E-02   0.5025E-03
      6       3.000        15.18        15.13        0.4638E-01   0.1444E-02
      7       4.000        12.06        12.03        0.2745E-01   0.2571E-02
      8       6.000        7.600        7.601       -0.5789E-03   0.4742E-02
      9       8.000        4.790        4.801       -0.1088E-01   0.6453E-02
     10       10.00        3.030        3.032       -0.2467E-02   0.7670E-02
     11       12.00        1.900        1.915       -0.1545E-01   0.8492E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.46       0.1550E-01  -0.5582    
                3       22.14       0.7305E-02   0.9354    
                4       20.92       0.8661E-02   -1.303    
                5       18.94       0.9598E-02  -0.4162    
                6       15.13       0.1075E-01    1.220    
                7       12.03       0.1225E-01   0.5410    
                8       7.601       0.1335E-01  -0.8561E-02
                9       4.801       0.1220E-01  -0.1356    
               10       3.032       0.1013E-01  -0.2822E-01
               11       1.915       0.7941E-02  -0.1677    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.425    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1834      [ 0.2287    ,  0.2309    ]
 KA1            1.517       1.513      0.6936      [  1.486    ,   1.540    ]
 V              27.38       27.38      0.8477E-01  [  27.32    ,   27.44    ]
 F              1.021       1.026       4.605      [ 0.9047    ,   1.148    ]
 KA2            2.799       2.799      0.3114      [  2.776    ,   2.821    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.67      0.20      1.00
 F           0.09     -0.18     -0.06      1.00
 KA2        -0.44      0.14      0.64     -0.04      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.178E-06
 KA1       -.132E-05 0.110E-03
 V         -.656E-05 0.496E-04 0.539E-03
 F         0.173E-05 -.872E-04 -.610E-04 0.223E-02
 KA2       -.162E-05 0.124E-04 0.129E-03 -.175E-04 0.760E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.95        17.96       -0.8453E-02   0.6988E-03
      3       1.000        20.45        20.44        0.9907E-02   0.2647E-03
      4       1.500        19.30        19.31       -0.1466E-01   0.4359E-03
      5       2.000        17.47        17.49       -0.1784E-01   0.8044E-03
      6       3.000        14.02        13.97        0.4690E-01   0.1828E-02
      7       4.000        11.14        11.11        0.3117E-01   0.2970E-02
      8       6.000        7.020        7.016        0.4253E-02   0.5078E-02
      9       8.000        4.430        4.431       -0.6252E-03   0.6699E-02
     10       10.00        2.790        2.798       -0.8056E-02   0.7839E-02
     11       12.00        1.760        1.767       -0.7046E-02   0.8605E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.96       0.1946E-01  -0.3220    
                3       20.44       0.1125E-01   0.6070    
                4       19.31       0.1221E-01  -0.7034    
                5       17.49       0.1265E-01  -0.6300    
                6       13.97       0.1233E-01    1.097    
                7       11.11       0.1270E-01   0.5718    
                8       7.016       0.1297E-01   0.5955E-01
                9       4.431       0.1168E-01  -0.7721E-02
               10       2.798       0.9651E-02  -0.9103E-01
               11       1.767       0.7552E-02  -0.7599E-01

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.402    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1855      [ 0.2288    ,  0.2310    ]
 KA1            1.521       1.516      0.6928      [  1.489    ,   1.543    ]
 V              28.57       28.57      0.9480E-01  [  28.50    ,   28.64    ]
 F              1.050       1.057       4.620      [ 0.9311    ,   1.182    ]
 KA2            2.798       2.798      0.3374      [  2.774    ,   2.823    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.62      0.20      1.00
 F           0.09     -0.18     -0.05      1.00
 KA2        -0.42      0.14      0.59     -0.04      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.182E-06
 KA1       -.136E-05 0.110E-03
 V         -.720E-05 0.558E-04 0.734E-03
 F         0.186E-05 -.924E-04 -.671E-04 0.238E-02
 KA2       -.169E-05 0.134E-04 0.152E-03 -.197E-04 0.891E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.20        17.21       -0.8765E-02   0.8706E-03
      3       1.000        19.60        19.59        0.1291E-01   0.3906E-03
      4       1.500        18.49        18.51       -0.1839E-01   0.5848E-03
      5       2.000        16.74        16.76       -0.1739E-01   0.9831E-03
      6       3.000        13.43        13.39        0.4144E-01   0.2039E-02
      7       4.000        10.67        10.64        0.2665E-01   0.3181E-02
      8       6.000        6.730        6.721        0.9196E-02   0.5252E-02
      9       8.000        4.240        4.244       -0.3749E-02   0.6825E-02
     10       10.00        2.680        2.680        0.3480E-03   0.7925E-02
     11       12.00        1.680        1.692       -0.1203E-01   0.8662E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.21       0.2107E-01  -0.2991    
                3       19.59       0.1309E-01   0.6516    
                4       18.51       0.1381E-01  -0.7618    
                5       16.76       0.1401E-01  -0.5556    
                6       13.39       0.1312E-01   0.9175    
                7       10.64       0.1298E-01   0.4723    
                8       6.721       0.1278E-01   0.1268    
                9       4.244       0.1139E-01  -0.4546E-01
               10       2.680       0.9375E-02   0.3864E-02
               11       1.692       0.7324E-02  -0.1293    

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.727    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1724      [ 0.2286    ,  0.2307    ]
 KA1            1.504       1.505      0.6884      [  1.478    ,   1.531    ]
 V              24.34       24.34      0.5612E-01  [  24.31    ,   24.38    ]
 F             0.9454      0.9471       4.606      [ 0.8349    ,   1.059    ]
 KA2            2.804       2.804      0.2149      [  2.788    ,   2.819    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.28      1.00
 V          -0.83      0.24      1.00
 F           0.08     -0.18     -0.07      1.00
 KA2        -0.54      0.16      0.79     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.157E-06
 KA1       -.115E-05 0.107E-03
 V         -.451E-05 0.336E-04 0.187E-03
 F         0.140E-05 -.792E-04 -.396E-04 0.190E-02
 KA2       -.128E-05 0.967E-05 0.646E-04 -.119E-04 0.363E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.20        20.21       -0.1270E-01   0.2958E-03
      3       1.000        23.00        23.00        0.4915E-02   0.3367E-04
      4       1.500        21.71        21.73       -0.1506E-01   0.1211E-03
      5       2.000        19.66        19.67       -0.9650E-02   0.3773E-03
      6       3.000        15.77        15.72        0.5217E-01   0.1268E-02
      7       4.000        12.53        12.50        0.3236E-01   0.2382E-02
      8       6.000        7.890        7.895       -0.5101E-02   0.4578E-02
      9       8.000        4.980        4.987       -0.7389E-02   0.6331E-02
     10       10.00        3.140        3.151       -0.1057E-01   0.7585E-02
     11       12.00        1.970        1.990       -0.2024E-01   0.8436E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.21       0.1298E-01  -0.7406    
                3       23.00       0.4994E-02   0.8440    
                4       21.73       0.6695E-02   -1.370    
                5       19.67       0.7973E-02  -0.4975    
                6       15.72       0.1005E-01    1.465    
                7       12.50       0.1208E-01   0.6629    
                8       7.895       0.1350E-01  -0.7556E-01
                9       4.987       0.1238E-01  -0.9296E-01
               10       3.151       0.1029E-01  -0.1214    
               11       1.990       0.8064E-02  -0.2204    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.430    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1761      [ 0.2287    ,  0.2308    ]
 KA1            1.507       1.506      0.6907      [  1.480    ,   1.533    ]
 V              25.03       25.03      0.6293E-01  [  24.99    ,   25.07    ]
 F             0.9631      0.9655       4.613      [ 0.8510    ,   1.080    ]
 KA2            2.803       2.803      0.2407      [  2.786    ,   2.820    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V          -0.79      0.23      1.00
 F           0.09     -0.18     -0.07      1.00
 KA2        -0.50      0.15      0.74     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.164E-06
 KA1       -.121E-05 0.108E-03
 V         -.503E-05 0.378E-04 0.248E-03
 F         0.154E-05 -.829E-04 -.472E-04 0.198E-02
 KA2       -.136E-05 0.104E-04 0.786E-04 -.141E-04 0.455E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.64        19.65       -0.1440E-01   0.3797E-03
      3       1.000        22.37        22.36        0.8793E-02   0.7054E-04
      4       1.500        21.11        21.13       -0.1640E-01   0.1811E-03
      5       2.000        19.11        19.13       -0.1735E-01   0.4686E-03
      6       3.000        15.33        15.28        0.4634E-01   0.1398E-02
      7       4.000        12.18        12.15        0.2833E-01   0.2522E-02
      8       6.000        7.680        7.676        0.4418E-02   0.4700E-02
      9       8.000        4.840        4.848       -0.8111E-02   0.6422E-02
     10       10.00        3.060        3.062       -0.2203E-02   0.7649E-02
     11       12.00        1.920        1.934       -0.1417E-01   0.8478E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.65       0.1488E-01  -0.7415    
                3       22.36       0.6737E-02    1.044    
                4       21.13       0.8161E-02   -1.220    
                5       19.13       0.9189E-02  -0.8023    
                6       15.28       0.1059E-01    1.239    
                7       12.15       0.1222E-01   0.5639    
                8       7.676       0.1341E-01   0.6428E-01
                9       4.848       0.1227E-01  -0.1013    
               10       3.062       0.1018E-01  -0.2524E-01
               11       1.934       0.7981E-02  -0.1540    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.237    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2298      0.1837      [ 0.2288    ,  0.2309    ]
 KA1            1.518       1.514      0.6919      [  1.487    ,   1.541    ]
 V              27.66       27.66      0.8706E-01  [  27.60    ,   27.73    ]
 F              1.028       1.034       4.601      [ 0.9113    ,   1.156    ]
 KA2            2.800       2.800      0.3185      [  2.777    ,   2.823    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.66      0.20      1.00
 F           0.08     -0.17     -0.05      1.00
 KA2        -0.44      0.14      0.63     -0.04      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.178E-06
 KA1       -.132E-05 0.110E-03
 V         -.670E-05 0.509E-04 0.580E-03
 F         0.170E-05 -.870E-04 -.590E-04 0.226E-02
 KA2       -.164E-05 0.127E-04 0.135E-03 -.175E-04 0.795E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.77        17.78       -0.6184E-02   0.7388E-03
      3       1.000        20.24        20.23        0.9831E-02   0.2934E-03
      4       1.500        19.10        19.12       -0.1505E-01   0.4707E-03
      5       2.000        17.29        17.31       -0.1651E-01   0.8471E-03
      6       3.000        13.87        13.83        0.4235E-01   0.1880E-02
      7       4.000        11.02        10.99        0.2715E-01   0.3022E-02
      8       6.000        6.940        6.942       -0.2079E-02   0.5121E-02
      9       8.000        4.380        4.384       -0.3837E-02   0.6731E-02
     10       10.00        2.760        2.768       -0.8341E-02   0.7861E-02
     11       12.00        1.740        1.748       -0.8175E-02   0.8619E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.78       0.1987E-01  -0.2297    
                3       20.23       0.1168E-01   0.5721    
                4       19.12       0.1259E-01  -0.6952    
                5       17.31       0.1298E-01  -0.5679    
                6       13.83       0.1252E-01   0.9766    
                7       10.99       0.1276E-01   0.4937    
                8       6.942       0.1291E-01  -0.2919E-01
                9       4.384       0.1159E-01  -0.4685E-01
               10       2.768       0.9572E-02  -0.9412E-01
               11       1.748       0.7487E-02  -0.8808E-01

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.603    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1783      [ 0.2287    ,  0.2308    ]
 KA1            1.509       1.508      0.6915      [  1.481    ,   1.535    ]
 V              25.52       25.52      0.6778E-01  [  25.48    ,   25.57    ]
 F             0.9751      0.9781       4.614      [ 0.8620    ,   1.094    ]
 KA2            2.802       2.802      0.2575      [  2.783    ,   2.820    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V          -0.76      0.22      1.00
 F           0.09     -0.18     -0.06      1.00
 KA2        -0.48      0.14      0.71     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.168E-06
 KA1       -.123E-05 0.109E-03
 V         -.539E-05 0.402E-04 0.299E-03
 F         0.158E-05 -.845E-04 -.504E-04 0.204E-02
 KA2       -.143E-05 0.109E-04 0.890E-04 -.147E-04 0.520E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.26        19.27       -0.1268E-01   0.4431E-03
      3       1.000        21.94        21.93        0.1013E-01   0.1033E-03
      4       1.500        20.70        20.72       -0.2025E-01   0.2286E-03
      5       2.000        18.75        18.76       -0.1022E-01   0.5359E-03
      6       3.000        15.04        14.99        0.4932E-01   0.1489E-02
      7       4.000        11.95        11.92        0.3110E-01   0.2619E-02
      8       6.000        7.530        7.529        0.1252E-02   0.4783E-02
      9       8.000        4.750        4.755       -0.5489E-02   0.6483E-02
     10       10.00        3.000        3.004       -0.3778E-02   0.7690E-02
     11       12.00        1.880        1.897       -0.1732E-01   0.8506E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.27       0.1603E-01  -0.6047    
                3       21.93       0.7843E-02   0.9941    
                4       20.72       0.9126E-02   -1.341    
                5       18.76       0.9993E-02  -0.4420    
                6       14.99       0.1095E-01    1.278    
                7       11.92       0.1231E-01   0.6076    
                8       7.529       0.1333E-01   0.1795E-01
                9       4.755       0.1216E-01  -0.6826E-01
               10       3.004       0.1009E-01  -0.4313E-01
               11       1.897       0.7910E-02  -0.1878    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.423    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1828      [ 0.2287    ,  0.2309    ]
 KA1            1.516       1.512      0.6920      [  1.486    ,   1.539    ]
 V              27.10       27.10      0.8208E-01  [  27.04    ,   27.16    ]
 F              1.014       1.019       4.611      [ 0.8983    ,   1.140    ]
 KA2            2.800       2.800      0.3039      [  2.778    ,   2.822    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.68      0.21      1.00
 F           0.09     -0.18     -0.06      1.00
 KA2        -0.44      0.14      0.65     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.176E-06
 KA1       -.132E-05 0.110E-03
 V         -.636E-05 0.491E-04 0.495E-03
 F         0.172E-05 -.880E-04 -.611E-04 0.221E-02
 KA2       -.158E-05 0.124E-04 0.122E-03 -.180E-04 0.724E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.14        18.15       -0.6456E-02   0.6587E-03
      3       1.000        20.66        20.65        0.8645E-02   0.2373E-03
      4       1.500        19.50        19.51       -0.1313E-01   0.4026E-03
      5       2.000        17.65        17.67       -0.1714E-01   0.7633E-03
      6       3.000        14.16        14.12        0.4373E-01   0.1779E-02
      7       4.000        11.25        11.22        0.2728E-01   0.2919E-02
      8       6.000        7.090        7.088        0.2235E-02   0.5036E-02
      9       8.000        4.470        4.476       -0.6166E-02   0.6669E-02
     10       10.00        2.820        2.827       -0.6854E-02   0.7818E-02
     11       12.00        1.780        1.785       -0.5257E-02   0.8591E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.15       0.1901E-01  -0.2538    
                3       20.65       0.1078E-01   0.5592    
                4       19.51       0.1178E-01  -0.6555    
                5       17.67       0.1229E-01  -0.6214    
                6       14.12       0.1216E-01    1.036    
                7       11.22       0.1267E-01   0.5048    
                8       7.088       0.1304E-01   0.3136E-01
                9       4.476       0.1177E-01  -0.7559E-01
               10       2.827       0.9729E-02  -0.7756E-01
               11       1.785       0.7614E-02  -0.5675E-01

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.054    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1769      [ 0.2287    ,  0.2308    ]
 KA1            1.508       1.507      0.6904      [  1.480    ,   1.534    ]
 V              25.30       25.30      0.6558E-01  [  25.26    ,   25.35    ]
 F             0.9704      0.9731       4.611      [ 0.8577    ,   1.088    ]
 KA2            2.803       2.803      0.2506      [  2.785    ,   2.821    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V          -0.77      0.23      1.00
 F           0.08     -0.17     -0.06      1.00
 KA2        -0.49      0.15      0.72     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.165E-06
 KA1       -.122E-05 0.108E-03
 V         -.521E-05 0.390E-04 0.275E-03
 F         0.152E-05 -.813E-04 -.483E-04 0.201E-02
 KA2       -.140E-05 0.107E-04 0.844E-04 -.142E-04 0.493E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.43        19.44       -0.1278E-01   0.4143E-03
      3       1.000        22.13        22.12        0.9606E-02   0.8808E-04
      4       1.500        20.88        20.90       -0.1851E-01   0.2071E-03
      5       2.000        18.91        18.92       -0.1053E-01   0.5059E-03
      6       3.000        15.16        15.12        0.4251E-01   0.1449E-02
      7       4.000        12.04        12.02        0.2121E-01   0.2577E-02
      8       6.000        7.580        7.591       -0.1068E-01   0.4748E-02
      9       8.000        4.770        4.794       -0.2388E-01   0.6458E-02
     10       10.00        3.010        3.028       -0.1756E-01   0.7673E-02
     11       12.00        1.880        1.912       -0.3205E-01   0.8495E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.44       0.1557E-01  -0.6302    
                3       22.12       0.7361E-02    1.021    
                4       20.90       0.8697E-02   -1.288    
                5       18.92       0.9627E-02  -0.4690    
                6       15.12       0.1076E-01    1.116    
                7       12.02       0.1223E-01   0.4176    
                8       7.591       0.1332E-01  -0.1552    
                9       4.794       0.1217E-01  -0.2972    
               10       3.028       0.1010E-01  -0.2005    
               11       1.912       0.7916E-02  -0.3478    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.546    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1728      [ 0.2287    ,  0.2308    ]
 KA1            1.503       1.504      0.6895      [  1.477    ,   1.531    ]
 V              24.36       24.36      0.5640E-01  [  24.33    ,   24.40    ]
 F             0.9467      0.9486       4.611      [ 0.8361    ,   1.061    ]
 KA2            2.803       2.803      0.2157      [  2.788    ,   2.819    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.28      1.00
 V          -0.83      0.24      1.00
 F           0.08     -0.18     -0.07      1.00
 KA2        -0.53      0.15      0.78     -0.05      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.158E-06
 KA1       -.116E-05 0.108E-03
 V         -.455E-05 0.338E-04 0.189E-03
 F         0.144E-05 -.799E-04 -.426E-04 0.191E-02
 KA2       -.128E-05 0.970E-05 0.650E-04 -.130E-04 0.365E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.18        20.19       -0.1436E-01   0.2984E-03
      3       1.000        22.98        22.97        0.5496E-02   0.3465E-04
      4       1.500        21.69        21.71       -0.1522E-01   0.1229E-03
      5       2.000        19.64        19.65       -0.1102E-01   0.3803E-03
      6       3.000        15.75        15.70        0.4837E-01   0.1273E-02
      7       4.000        12.51        12.48        0.2635E-01   0.2387E-02
      8       6.000        7.870        7.885       -0.1485E-01   0.4583E-02
      9       8.000        4.960        4.980       -0.2003E-01   0.6336E-02
     10       10.00        3.120        3.145       -0.2536E-01   0.7589E-02
     11       12.00        1.950        1.987       -0.3659E-01   0.8439E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.19       0.1304E-01  -0.8337    
                3       22.97       0.5052E-02   0.9306    
                4       21.71       0.6745E-02   -1.375    
                5       19.65       0.8020E-02  -0.5659    
                6       15.70       0.1008E-01    1.355    
                7       12.48       0.1210E-01   0.5391    
                8       7.885       0.1351E-01  -0.2196    
                9       4.980       0.1240E-01  -0.2517    
               10       3.145       0.1030E-01  -0.2911    
               11       1.987       0.8069E-02  -0.3983    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.416    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2299      0.2299      0.1833      [ 0.2288    ,  0.2310    ]
 KA1            1.516       1.513      0.6922      [  1.486    ,   1.540    ]
 V              27.40       27.41      0.8499E-01  [  27.35    ,   27.47    ]
 F              1.023       1.027       4.607      [ 0.9058    ,   1.149    ]
 KA2            2.798       2.799      0.3116      [  2.776    ,   2.821    ]


 SDslope       -.4096E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.30      1.00
 V          -0.67      0.21      1.00
 F           0.09     -0.18     -0.06      1.00
 KA2        -0.44      0.14      0.64     -0.04      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.178E-06
 KA1       -.132E-05 0.110E-03
 V         -.658E-05 0.504E-04 0.543E-03
 F         0.174E-05 -.892E-04 -.609E-04 0.224E-02
 KA2       -.162E-05 0.126E-04 0.129E-03 -.176E-04 0.760E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.93        17.94       -0.9761E-02   0.7028E-03
      3       1.000        20.43        20.42        0.1133E-01   0.2675E-03
      4       1.500        19.28        19.29       -0.1402E-01   0.4395E-03
      5       2.000        17.45        17.47       -0.1868E-01   0.8089E-03
      6       3.000        14.00        13.96        0.4308E-01   0.1834E-02
      7       4.000        11.12        11.10        0.2474E-01   0.2976E-02
      8       6.000        7.000        7.006       -0.6273E-02   0.5084E-02
      9       8.000        4.410        4.424       -0.1407E-01   0.6704E-02
     10       10.00        2.770        2.794       -0.2356E-01   0.7842E-02
     11       12.00        1.740        1.764       -0.2398E-01   0.8607E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.94       0.1948E-01  -0.3704    
                3       20.42       0.1130E-01   0.6908    
                4       19.29       0.1224E-01  -0.6700    
                5       17.47       0.1267E-01  -0.6575    
                6       13.96       0.1233E-01    1.006    
                7       11.10       0.1269E-01   0.4534    
                8       7.006       0.1295E-01  -0.8811E-01
                9       4.424       0.1166E-01  -0.1720    
               10       2.794       0.9633E-02  -0.2661    
               11       1.764       0.7538E-02  -0.2585    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 15:02:11 2018

 Data file name: data_null.csv

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    3000

 Total number of EM iterations:   30

 Lognormal distribution option

 -2logLikelihood:   -773.100    

 Model Selection Criteria
  AIC:       -731.100    
  BIC:       -656.005    

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KE          0.230        6.74         0.430E-03   0.187       0.844E+04
  KA1          1.51        49.6         0.897E-02   0.595       0.993E+04
  V            26.0        406.          1.28        4.91       0.845E+04
  F           0.992        457.         0.568E-01    5.72       0.464E+05
  KA2          2.80        25.0         0.112E-01   0.401       0.130E+05

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KE        KA1       V         F         KA2       
 KE        0.185E-06
 KA1       -.111E-05 0.805E-04
 V         0.657E-04 0.324E-02  1.63    
 F         0.381E-05 0.252E-04 0.436E-01 0.322E-02
 KA2       -.181E-05 0.943E-05 -.146E-02 -.658E-04 0.126E-03

  As Covariance Matrix for ln(parameters):

           KE        KA1       V         F         KA2       
 KE        0.350E-05
 KA1       -.319E-05 0.354E-04
 V         0.110E-04 0.828E-04 0.241E-02
 F         0.167E-04 0.168E-04 0.169E-02 0.328E-02
 KA2       -.281E-05 0.223E-05 -.201E-04 -.237E-04 0.161E-04

  As Correlation Matrix:

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.29      1.00
 V           0.12      0.28      1.00
 F           0.16      0.05      0.60      1.00
 KA2        -0.37      0.09     -0.10     -0.10      1.00

  Standard Errors of Estimated Covariance Matrix for ln(parameters):

           KE        KA1       V         F         KA2       
 KE         0.59E-03
 KA1        0.32E-02  0.71E-02
 V          0.54E-02  0.14      0.39    
 F          0.44E-02  0.14       1.5       3.0    
 KA2        0.13E-02  0.83E-02  0.13E-01  0.14      0.42E-02

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope    -0.410E-02   41.1    
  SDinter     0.100      Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  1) =  0.2298098         ! KE        
       Pmean(  2) =   1.507702         ! KA1       
       Pmean(  3) =   25.97819         ! V         
       Pmean(  4) =  0.9917180         ! F         
       Pmean(  5) =   2.800224         ! KA2       
 
       Pcov(  1,  1) =  0.1847040E-06  ! KE         & KE        
       Pcov(  2,  1) = -0.1106224E-05  ! KA1        & KE        
       Pcov(  2,  2) =  0.8054665E-04  ! KA1        & KA1       
       Pcov(  3,  1) =  0.6565844E-04  ! V          & KE        
       Pcov(  3,  2) =  0.3242813E-02  ! V          & KA1       
       Pcov(  3,  3) =   1.629727      ! V          & V         
       Pcov(  4,  1) =  0.3805608E-05  ! F          & KE        
       Pcov(  4,  2) =  0.2518679E-04  ! F          & KA1       
       Pcov(  4,  3) =  0.4355128E-01  ! F          & V         
       Pcov(  4,  4) =  0.3221709E-02  ! F          & F         
       Pcov(  5,  1) = -0.1808110E-05  ! KA2        & KE        
       Pcov(  5,  2) =  0.9433353E-05  ! KA2        & KA1       
       Pcov(  5,  3) = -0.1459354E-02  ! KA2        & V         
       Pcov(  5,  4) = -0.6583161E-04  ! KA2        & F         
       Pcov(  5,  5) =  0.1262660E-03  ! KA2        & KA2       

      ________________________________________


 List of Files Created

  Record of program run and all results:
    E.run
  Summary of population estimates at each iteration:
    EIT.csv
  Individual subject estimates at final iteration:
    EIND.csv
  Table of predictions and residuals for each subject:
    ERSD.csv
  Information for plotting model predictions for each subject:
    EPLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    E.eps
  Command file for subsequent Batch runs:
    E.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 15:02:13 2018

