
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 13:51:23 2018


 Enter file name for storing session run (*.run): C.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Enter the data file name (*.dat): data_null.csv

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Enter parameter file name (*.prm or *IND.csv):  param_null.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           n
 KA1         2.000           y
 V           21.00           n
 F          0.8000           y
 KA2         2.000           y
 SDinter    0.1000           n
 SDslope    0.1000           y

 Fix non estimated system parameters to subject specific values (Y/N)?  n

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  1

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  2

 Enter number of samples/EM iteration (1000 -   3000):      3000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    22.324    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.542       1.541       6.136      [  1.317    ,   1.764    ]
 F             0.7897      0.7897       2.929      [ 0.7350    ,  0.8444    ]
 KA2            2.411       2.413       9.397      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.893E-02
 F         -.111E-03 0.535E-03
 KA2       -.359E-05 0.148E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.20        13.24       -0.4464E-01    3.555    
      3       1.000        18.00        17.93        0.6779E-01    6.332    
      4       1.500        19.00        18.82        0.1757        6.948    
      5       2.000        18.30        18.10        0.2011        6.442    
      6       3.000        15.40        15.21        0.1854        4.621    
      7       4.000        12.50        12.27        0.2291        3.073    
      8       6.000        7.920        7.787        0.1327        1.320    
      9       8.000        5.000        4.918        0.8193E-01   0.5815    
     10       10.00        3.160        3.105        0.5519E-01   0.2686    
     11       12.00        1.990        1.960        0.2998E-01   0.1325    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.24       0.6445      -0.7927E-02
                3       17.93       0.6651       0.3643E-01
                4       18.82       0.5886       0.7348E-01
                5       18.10       0.5319       0.8525E-01
                6       15.21       0.4559       0.9241E-01
                7       12.27       0.3804       0.1372    
                8       7.787       0.2468       0.1218    
                9       4.918       0.1563       0.1132    
               10       3.105       0.9873E-01   0.1115    
               11       1.960       0.6233E-01   0.8637E-01

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    22.942    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.545       1.543       6.092      [  1.321    ,   1.766    ]
 F             0.7996      0.7991       2.872      [ 0.7449    ,  0.8534    ]
 KA2            2.412       2.413       9.399      [  1.877    ,   2.950    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.884E-02
 F         -.112E-03 0.527E-03
 KA2       -.260E-04 -.394E-05 0.515E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.60        13.42        0.1802        3.644    
      3       1.000        18.54        18.16        0.3797        6.487    
      4       1.500        19.57        19.06        0.5132        7.114    
      5       2.000        18.85        18.32        0.5323        6.592    
      6       3.000        15.86        15.39        0.4659        4.725    
      7       4.000        12.88        12.41        0.4658        3.141    
      8       6.000        8.160        7.878        0.2823        1.349    
      9       8.000        5.150        4.975        0.1749       0.5932    
     10       10.00        3.250        3.141        0.1092       0.2736    
     11       12.00        2.050        1.983        0.6724E-01   0.1348    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.42       0.6451       0.1102    
                3       18.16       0.6630       0.1585    
                4       19.06       0.5848       0.1992    
                5       18.32       0.5278       0.2133    
                6       15.39       0.4527       0.2204    
                7       12.41       0.3779       0.2693    
                8       7.878       0.2453       0.2494    
                9       4.975       0.1553       0.2328    
               10       3.141       0.9810E-01   0.2137    
               11       1.983       0.6193E-01   0.1872    

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    22.200    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.539       1.537       6.178      [  1.313    ,   1.762    ]
 F             0.7796      0.7802       2.993      [ 0.7250    ,  0.8354    ]
 KA2            2.412       2.413       9.392      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.902E-02
 F         -.109E-03 0.545E-03
 KA2       0.163E-04 0.298E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.80        13.07       -0.2683        3.466    
      3       1.000        17.46        17.70       -0.2426        6.177    
      4       1.500        18.43        18.59       -0.1604        6.784    
      5       2.000        17.75        17.88       -0.1289        6.293    
      6       3.000        14.94        15.03       -0.9428E-01    4.517    
      7       4.000        12.13        12.13        0.2965E-02    3.006    
      8       6.000        7.680        7.697       -0.1654E-01    1.292    
      9       8.000        4.850        4.861       -0.1076E-01   0.5698    
     10       10.00        3.070        3.069        0.1371E-02   0.2636    
     11       12.00        1.930        1.937       -0.7181E-02   0.1303    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.07       0.6446      -0.1283    
                3       17.70       0.6681      -0.8804E-01
                4       18.59       0.5933      -0.5467E-01
                5       17.88       0.5368      -0.4526E-01
                6       15.03       0.4598      -0.3811E-01
                7       12.13       0.3835       0.8306E-02
                8       7.697       0.2488      -0.8116E-02
                9       4.861       0.1576      -0.8410E-02
               10       3.069       0.9951E-01   0.7731E-02
               11       1.937       0.6282E-01  -0.1583E-01

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.997    

 -2LogLikelihood:    22.402    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.537       1.536       6.210      [  1.310    ,   1.761    ]
 F             0.7727      0.7737       3.033      [ 0.7182    ,  0.8292    ]
 KA2            2.412       2.413       9.389      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.910E-02
 F         -.110E-03 0.551E-03
 KA2       0.133E-04 0.314E-05 0.513E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.54        12.95       -0.4090        3.407    
      3       1.000        17.10        17.55       -0.4462        6.073    
      4       1.500        18.05        18.43       -0.3802        6.672    
      5       2.000        17.39        17.73       -0.3375        6.191    
      6       3.000        14.63        14.91       -0.2797        4.446    
      7       4.000        11.88        12.03       -0.1474        2.960    
      8       6.000        7.520        7.634       -0.1136        1.273    
      9       8.000        4.750        4.821       -0.7104E-01   0.5617    
     10       10.00        3.000        3.044       -0.4356E-01   0.2601    
     11       12.00        1.890        1.921       -0.3135E-01   0.1288    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.95       0.6440      -0.2058    
                3       17.55       0.6693      -0.1715    
                4       18.43       0.5957      -0.1402    
                5       17.73       0.5395      -0.1295    
                6       14.91       0.4620      -0.1263    
                7       12.03       0.3852      -0.7905E-01
                8       7.634       0.2498      -0.9421E-01
                9       4.821       0.1582      -0.8890E-01
               10       3.044       0.9992E-01  -0.8032E-01
               11       1.921       0.6308E-01  -0.8329E-01

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    23.626    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.547       1.545       6.062      [  1.324    ,   1.767    ]
 F             0.8063      0.8055       2.834      [ 0.7515    ,  0.8595    ]
 KA2            2.412       2.414       9.392      [  1.878    ,   2.950    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.878E-02
 F         -.111E-03 0.521E-03
 KA2       -.546E-05 -.415E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.86        13.54        0.3227        3.705    
      3       1.000        18.90        18.31        0.5861        6.593    
      4       1.500        19.95        19.21        0.7365        7.227    
      5       2.000        19.22        18.47        0.7546        6.695    
      6       3.000        16.17        15.52        0.6546        4.796    
      7       4.000        13.13        12.51        0.6189        3.188    
      8       6.000        8.320        7.939        0.3811        1.368    
      9       8.000        5.250        5.014        0.2362       0.6013    
     10       10.00        3.320        3.165        0.1548       0.2771    
     11       12.00        2.090        1.998        0.9185E-01   0.1363    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.54       0.6454       0.1834    
                3       18.31       0.6616       0.2377    
                4       19.21       0.5822       0.2806    
                5       18.47       0.5251       0.2975    
                6       15.52       0.4504       0.3049    
                7       12.51       0.3761       0.3531    
                8       7.939       0.2441       0.3321    
                9       5.014       0.1546       0.3104    
               10       3.165       0.9764E-01   0.2990    
               11       1.998       0.6164E-01   0.2528    

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    25.009    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.550       1.548       6.011      [  1.328    ,   1.768    ]
 F             0.8161      0.8148       2.783      [ 0.7611    ,  0.8684    ]
 KA2            2.412       2.413       9.398      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.866E-02
 F         -.110E-03 0.514E-03
 KA2       -.160E-04 0.287E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        14.26        13.71        0.5498        3.795    
      3       1.000        19.44        18.54        0.9015        6.749    
      4       1.500        20.52        19.44         1.078        7.394    
      5       2.000        19.76        18.68         1.080        6.845    
      6       3.000        16.63        15.69        0.9387        4.901    
      7       4.000        13.50        12.65        0.8486        3.255    
      8       6.000        8.550        8.027        0.5225        1.396    
      9       8.000        5.400        5.070        0.3304       0.6130    
     10       10.00        3.410        3.200        0.2095       0.2821    
     11       12.00        2.150        2.020        0.1296       0.1385    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.71       0.6456       0.2980    
                3       18.54       0.6595       0.3563    
                4       19.44       0.5788       0.4030    
                5       18.68       0.5214       0.4185    
                6       15.69       0.4475       0.4300    
                7       12.65       0.3739       0.4767    
                8       8.027       0.2427       0.4485    
                9       5.070       0.1537       0.4276    
               10       3.200       0.9707E-01   0.3993    
               11       2.020       0.6128E-01   0.3521    

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    23.142    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.534       1.533       6.260      [  1.306    ,   1.760    ]
 F             0.7626      0.7641       3.103      [ 0.7081    ,  0.8202    ]
 KA2            2.412       2.413       9.403      [  1.876    ,   2.950    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.920E-02
 F         -.104E-03 0.562E-03
 KA2       0.202E-04 0.234E-06 0.515E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.14        12.77       -0.6323        3.319    
      3       1.000        16.56        17.32       -0.7557        5.921    
      4       1.500        17.48        18.20       -0.7151        6.509    
      5       2.000        16.84        17.51       -0.6662        6.044    
      6       3.000        14.17        14.73       -0.5581        4.344    
      7       4.000        11.50        11.88       -0.3825        2.893    
      8       6.000        7.290        7.542       -0.2521        1.246    
      9       8.000        4.600        4.763       -0.1633       0.5501    
     10       10.00        2.910        3.007       -0.9711E-01   0.2551    
     11       12.00        1.830        1.898       -0.6835E-01   0.1265    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.77       0.6451      -0.3312    
                3       17.32       0.6736      -0.3009    
                4       18.20       0.6016      -0.2732    
                5       17.51       0.5453      -0.2647    
                6       14.73       0.4663      -0.2614    
                7       11.88       0.3884      -0.2182    
                8       7.542       0.2518      -0.2194    
                9       4.763       0.1595      -0.2142    
               10       3.007       0.1007      -0.1871    
               11       1.898       0.6358E-01  -0.1880    

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.996    

 -2LogLikelihood:    22.273    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.538       1.537       6.196      [  1.312    ,   1.762    ]
 F             0.7761      0.7769       3.016      [ 0.7215    ,  0.8323    ]
 KA2            2.412       2.413       9.391      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.907E-02
 F         -.112E-03 0.549E-03
 KA2       -.566E-05 -.896E-06 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.67        13.01       -0.3384        3.436    
      3       1.000        17.28        17.62       -0.3437        6.124    
      4       1.500        18.24        18.51       -0.2692        6.727    
      5       2.000        17.57        17.80       -0.2320        6.241    
      6       3.000        14.78        14.97       -0.1908        4.481    
      7       4.000        12.00        12.08       -0.7618E-01    2.982    
      8       6.000        7.600        7.664       -0.6439E-01    1.283    
      9       8.000        4.800        4.840       -0.4047E-01   0.5657    
     10       10.00        3.030        3.056       -0.2582E-01   0.2618    
     11       12.00        1.910        1.929       -0.1910E-01   0.1295    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.01       0.6442      -0.1668    
                3       17.62       0.6688      -0.1293    
                4       18.51       0.5948      -0.9685E-01
                5       17.80       0.5386      -0.8670E-01
                6       14.97       0.4615      -0.8383E-01
                7       12.08       0.3848      -0.3748E-01
                8       7.664       0.2496      -0.5039E-01
                9       4.840       0.1581      -0.4793E-01
               10       3.056       0.9985E-01  -0.4539E-01
               11       1.929       0.6304E-01  -0.4898E-01

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    23.260    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.544       6.080      [  1.322    ,   1.766    ]
 F             0.8030      0.8024       2.853      [ 0.7482    ,  0.8565    ]
 KA2            2.412       2.413       9.390      [  1.878    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.881E-02
 F         -.109E-03 0.524E-03
 KA2       0.468E-05 -.339E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.73        13.48        0.2510        3.675    
      3       1.000        18.72        18.24        0.4822        6.540    
      4       1.500        19.76        19.14        0.6240        7.171    
      5       2.000        19.03        18.39        0.6375        6.644    
      6       3.000        16.02        15.46        0.5644        4.761    
      7       4.000        13.00        12.46        0.5367        3.165    
      8       6.000        8.240        7.909        0.3312        1.358    
      9       8.000        5.200        4.995        0.2053       0.5973    
     10       10.00        3.290        3.153        0.1368       0.2754    
     11       12.00        2.070        1.991        0.7944E-01   0.1355    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.48       0.6457       0.1467    
                3       18.24       0.6626       0.1980    
                4       19.14       0.5836       0.2397    
                5       18.39       0.5265       0.2532    
                6       15.46       0.4514       0.2647    
                7       12.46       0.3769       0.3081    
                8       7.909       0.2446       0.2905    
                9       4.995       0.1549       0.2713    
               10       3.153       0.9784E-01   0.2656    
               11       1.991       0.6177E-01   0.2197    

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    22.865    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.544       6.087      [  1.322    ,   1.766    ]
 F             0.7987      0.7983       2.874      [ 0.7440    ,  0.8526    ]
 KA2            2.412       2.413       9.393      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2        -0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.883E-02
 F         -.112E-03 0.527E-03
 KA2       -.147E-04 0.278E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.41        0.1703        3.639    
      3       1.000        18.52        18.14        0.3754        6.476    
      4       1.500        19.55        19.04        0.5112        7.101    
      5       2.000        18.83        18.30        0.5307        6.580    
      6       3.000        15.84        15.38        0.4623        4.716    
      7       4.000        12.86        12.40        0.4594        3.135    
      8       6.000        8.140        7.869        0.2710        1.346    
      9       8.000        5.130        4.970        0.1604       0.5921    
     10       10.00        3.230        3.137        0.9265E-01   0.2731    
     11       12.00        2.030        1.981        0.4944E-01   0.1345    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.41       0.6443       0.1050    
                3       18.14       0.6623       0.1569    
                4       19.04       0.5844       0.1986    
                5       18.30       0.5276       0.2128    
                6       15.38       0.4525       0.2190    
                7       12.40       0.3777       0.2659    
                8       7.869       0.2451       0.2399    
                9       4.970       0.1552       0.2141    
               10       3.137       0.9804E-01   0.1822    
               11       1.981       0.6189E-01   0.1387    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    23.521    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.547       1.546       6.057      [  1.324    ,   1.767    ]
 F             0.8054      0.8047       2.840      [ 0.7506    ,  0.8587    ]
 KA2            2.412       2.413       9.397      [  1.877    ,   2.949    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.877E-02
 F         -.112E-03 0.522E-03
 KA2       0.248E-05 0.164E-05 0.514E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.84        13.53        0.3138        3.699    
      3       1.000        18.88        18.30        0.5829        6.581    
      4       1.500        19.93        19.19        0.7354        7.214    
      5       2.000        19.20        18.45        0.7536        6.682    
      6       3.000        16.15        15.50        0.6514        4.787    
      7       4.000        13.11        12.50        0.6128        3.181    
      8       6.000        8.300        7.930        0.3699        1.365    
      9       8.000        5.230        5.008        0.2219       0.6001    
     10       10.00        3.300        3.162        0.1383       0.2766    
     11       12.00        2.070        1.996        0.7409E-01   0.1361    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.53       0.6447       0.1789    
                3       18.30       0.6611       0.2366    
                4       19.19       0.5823       0.2805    
                5       18.45       0.5254       0.2975    
                6       15.50       0.4508       0.3038    
                7       12.50       0.3765       0.3500    
                8       7.930       0.2443       0.3229    
                9       5.008       0.1547       0.2921    
               10       3.162       0.9772E-01   0.2680    
               11       1.996       0.6169E-01   0.2048    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.998    

 -2LogLikelihood:    22.858    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.544       6.091      [  1.322    ,   1.767    ]
 F             0.7987      0.7982       2.876      [ 0.7439    ,  0.8525    ]
 KA2            2.412       2.413       9.403      [  1.877    ,   2.950    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.05      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.885E-02
 F         -.112E-03 0.527E-03
 KA2       0.737E-05 0.806E-06 0.515E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.41        0.1707        3.639    
      3       1.000        18.52        18.14        0.3765        6.475    
      4       1.500        19.55        19.04        0.5129        7.100    
      5       2.000        18.83        18.30        0.5326        6.578    
      6       3.000        15.84        15.38        0.4643        4.714    
      7       4.000        12.86        12.40        0.4611        3.134    
      8       6.000        8.140        7.868        0.2720        1.345    
      9       8.000        5.130        4.969        0.1611       0.5919    
     10       10.00        3.220        3.137        0.8309E-01   0.2731    
     11       12.00        2.030        1.980        0.4971E-01   0.1345    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.41       0.6446       0.1052    
                3       18.14       0.6625       0.1574    
                4       19.04       0.5846       0.1992    
                5       18.30       0.5278       0.2136    
                6       15.38       0.4527       0.2199    
                7       12.40       0.3780       0.2669    
                8       7.868       0.2453       0.2408    
                9       4.969       0.1553       0.2151    
               10       3.137       0.9810E-01   0.1639    
               11       1.980       0.6193E-01   0.1395    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.992    

 -2LogLikelihood:    44.917    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.598      [  1.304    ,   1.786    ]
 F             0.7926      0.7925       3.771      [ 0.7218    ,  0.8632    ]
 KA2            2.413       2.414       9.100      [  1.895    ,   2.934    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.272E-05 0.893E-03
 KA2       0.332E-04 0.443E-05 0.483E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.70        21.77        -3.066        9.205    
      3       1.000        21.30        25.92        -4.617        12.89    
      4       1.500        20.10        25.07        -4.975        12.09    
      5       2.000        18.20        22.96        -4.755        10.18    
      6       3.000        14.60        18.46        -3.865        6.690    
      7       4.000        11.60        14.69        -3.094        4.321    
      8       6.000        7.310        9.278        -1.968        1.821    
      9       8.000        4.610        5.857        -1.247       0.7898    
     10       10.00        2.910        3.697       -0.7875       0.3575    
     11       12.00        1.830        2.334       -0.5042       0.1717    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.77        1.007      -0.9985    
                3       25.92       0.4936       -1.284    
                4       25.07       0.1070       -1.431    
                5       22.96       0.8494E-01   -1.490    
                6       18.46       0.1608       -1.494    
                7       14.69       0.1425       -1.488    
                8       9.278       0.9198E-01   -1.458    
                9       5.857       0.5810E-01   -1.403    
               10       3.697       0.3668E-01   -1.317    
               11       2.334       0.2316E-01   -1.217    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    39.495    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.544       6.602      [  1.303    ,   1.786    ]
 F             0.7925      0.7925       3.769      [ 0.7219    ,  0.8631    ]
 KA2            2.421       2.422       8.983      [  1.908    ,   2.937    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.00      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         -.159E-05 0.892E-03
 KA2       -.247E-04 -.704E-05 0.473E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.45        21.80        -2.354        9.235    
      3       1.000        22.15        25.94        -3.785        12.91    
      4       1.500        20.90        25.08        -4.179        12.09    
      5       2.000        18.93        22.95        -4.023        10.18    
      6       3.000        15.18        18.46        -3.279        6.686    
      7       4.000        12.06        14.69        -2.628        4.318    
      8       6.000        7.600        9.275        -1.675        1.820    
      9       8.000        4.790        5.855        -1.065       0.7893    
     10       10.00        3.030        3.696       -0.6661       0.3573    
     11       12.00        1.900        2.333       -0.4333       0.1716    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.80       0.9933      -0.7621    
                3       25.94       0.4837       -1.052    
                4       25.08       0.1029       -1.202    
                5       22.95       0.8483E-01   -1.261    
                6       18.46       0.1583       -1.268    
                7       14.69       0.1401       -1.264    
                8       9.275       0.9030E-01   -1.241    
                9       5.855       0.5704E-01   -1.198    
               10       3.696       0.3601E-01   -1.114    
               11       2.333       0.2273E-01   -1.046    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    51.292    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.602      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.775      [ 0.7217    ,  0.8632    ]
 KA2            2.405       2.406       9.224      [  1.881    ,   2.931    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.213E-06 0.895E-03
 KA2       -.379E-04 -.683E-05 0.493E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.95        21.73        -3.778        9.175    
      3       1.000        20.45        25.90        -5.447        12.87    
      4       1.500        19.30        25.07        -5.770        12.08    
      5       2.000        17.47        22.96        -5.488        10.19    
      6       3.000        14.02        18.47        -4.451        6.694    
      7       4.000        11.14        14.70        -3.559        4.324    
      8       6.000        7.020        9.282        -2.262        1.822    
      9       8.000        4.430        5.859        -1.429       0.7904    
     10       10.00        2.790        3.699       -0.9089       0.3577    
     11       12.00        1.760        2.335       -0.5751       0.1718    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.73        1.024       -1.236    
                3       25.90       0.5056       -1.516    
                4       25.07       0.1124       -1.660    
                5       22.96       0.8494E-01   -1.720    
                6       18.47       0.1636       -1.720    
                7       14.70       0.1455       -1.711    
                8       9.282       0.9399E-01   -1.675    
                9       5.859       0.5938E-01   -1.607    
               10       3.699       0.3749E-01   -1.519    
               11       2.335       0.2366E-01   -1.387    

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.998    

 -2LogLikelihood:    58.725    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.604      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.769      [ 0.7218    ,  0.8631    ]
 KA2            2.397       2.399       9.340      [  1.869    ,   2.929    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.153E-06 0.892E-03
 KA2       0.474E-04 0.340E-05 0.502E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.20        21.69        -4.493        9.147    
      3       1.000        19.60        25.88        -6.279        12.86    
      4       1.500        18.49        25.07        -6.576        12.08    
      5       2.000        16.74        22.96        -6.221        10.19    
      6       3.000        13.43        18.48        -5.047        6.698    
      7       4.000        10.67        14.70        -4.034        4.327    
      8       6.000        6.730        9.285        -2.555        1.823    
      9       8.000        4.240        5.861        -1.621       0.7909    
     10       10.00        2.680        3.700        -1.020       0.3579    
     11       12.00        1.680        2.336       -0.6559       0.1719    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.69        1.038       -1.474    
                3       25.88       0.5153       -1.749    
                4       25.07       0.1162       -1.892    
                5       22.96       0.8497E-01   -1.949    
                6       18.48       0.1660       -1.950    
                7       14.70       0.1480       -1.939    
                8       9.285       0.9564E-01   -1.892    
                9       5.861       0.6042E-01   -1.823    
               10       3.700       0.3814E-01   -1.705    
               11       2.336       0.2408E-01   -1.582    

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    35.011    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.598      [  1.304    ,   1.786    ]
 F             0.7926      0.7925       3.767      [ 0.7219    ,  0.8631    ]
 KA2            2.430       2.430       8.853      [  1.921    ,   2.939    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.00      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         -.740E-06 0.891E-03
 KA2       -.220E-04 -.390E-05 0.463E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.20        21.84        -1.641        9.265    
      3       1.000        23.00        25.95        -2.954        12.93    
      4       1.500        21.71        25.08        -3.373        12.09    
      5       2.000        19.66        22.95        -3.290        10.18    
      6       3.000        15.77        18.45        -2.683        6.682    
      7       4.000        12.53        14.68        -2.153        4.315    
      8       6.000        7.890        9.271        -1.381        1.818    
      9       8.000        4.980        5.853       -0.8727       0.7888    
     10       10.00        3.140        3.695       -0.5547       0.3570    
     11       12.00        1.970        2.332       -0.3624       0.1715    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.84       0.9778      -0.5266    
                3       25.95       0.4732      -0.8197    
                4       25.08       0.9858E-01  -0.9698    
                5       22.95       0.8461E-01   -1.031    
                6       18.45       0.1557       -1.038    
                7       14.68       0.1374       -1.036    
                8       9.271       0.8851E-01   -1.024    
                9       5.853       0.5591E-01  -0.9822    
               10       3.695       0.3529E-01  -0.9280    
               11       2.332       0.2228E-01  -0.8749    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    38.230    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.599      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.772      [ 0.7218    ,  0.8632    ]
 KA2            2.423       2.424       8.953      [  1.911    ,   2.938    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2         0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.320E-06 0.893E-03
 KA2       0.217E-05 -.116E-06 0.471E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.64        21.81        -2.173        9.243    
      3       1.000        22.37        25.94        -3.570        12.91    
      4       1.500        21.11        25.08        -3.970        12.09    
      5       2.000        19.11        22.95        -3.842        10.18    
      6       3.000        15.33        18.46        -3.127        6.685    
      7       4.000        12.18        14.69        -2.507        4.317    
      8       6.000        7.680        9.274        -1.594        1.819    
      9       8.000        4.840        5.854        -1.014       0.7892    
     10       10.00        3.060        3.696       -0.6358       0.3572    
     11       12.00        1.920        2.333       -0.4131       0.1715    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.81       0.9891      -0.7024    
                3       25.94       0.4805      -0.9915    
                4       25.08       0.1015       -1.142    
                5       22.95       0.8488E-01   -1.204    
                6       18.46       0.1576       -1.209    
                7       14.69       0.1393       -1.206    
                8       9.274       0.8978E-01   -1.181    
                9       5.854       0.5671E-01   -1.141    
               10       3.696       0.3580E-01   -1.063    
               11       2.333       0.2260E-01  -0.9970    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.997    

 -2LogLikelihood:    53.093    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.597      [  1.304    ,   1.785    ]
 F             0.7926      0.7925       3.769      [ 0.7218    ,  0.8631    ]
 KA2            2.403       2.405       9.246      [  1.879    ,   2.931    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2         0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.375E-06 0.892E-03
 KA2       0.276E-04 -.177E-05 0.494E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.77        21.72        -3.952        9.169    
      3       1.000        20.24        25.89        -5.654        12.87    
      4       1.500        19.10        25.07        -5.969        12.08    
      5       2.000        17.29        22.96        -5.669        10.19    
      6       3.000        13.87        18.47        -4.602        6.695    
      7       4.000        11.02        14.70        -3.680        4.325    
      8       6.000        6.940        9.282        -2.342        1.822    
      9       8.000        4.380        5.860        -1.480       0.7905    
     10       10.00        2.760        3.699       -0.9392       0.3578    
     11       12.00        1.740        2.335       -0.5952       0.1718    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.72        1.026       -1.293    
                3       25.89       0.5069       -1.574    
                4       25.07       0.1127       -1.717    
                5       22.96       0.8498E-01   -1.776    
                6       18.47       0.1640       -1.778    
                7       14.70       0.1458       -1.769    
                8       9.282       0.9421E-01   -1.735    
                9       5.860       0.5952E-01   -1.664    
               10       3.699       0.3757E-01   -1.570    
               11       2.335       0.2372E-01   -1.436    

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.999    

 -2LogLikelihood:    40.743    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.605      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.771      [ 0.7218    ,  0.8632    ]
 KA2            2.419       2.420       9.003      [  1.904    ,   2.935    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.309E-05 0.893E-03
 KA2       -.237E-04 -.122E-05 0.475E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.26        21.79        -2.531        9.225    
      3       1.000        21.94        25.93        -3.989        12.90    
      4       1.500        20.70        25.08        -4.377        12.09    
      5       2.000        18.75        22.95        -4.204        10.18    
      6       3.000        15.04        18.46        -3.421        6.687    
      7       4.000        11.95        14.69        -2.740        4.319    
      8       6.000        7.530        9.276        -1.746        1.820    
      9       8.000        4.750        5.856        -1.106       0.7895    
     10       10.00        3.000        3.697       -0.6966       0.3573    
     11       12.00        1.880        2.334       -0.4536       0.1716    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.79       0.9970      -0.8211    
                3       25.93       0.4871       -1.109    
                4       25.08       0.1047       -1.259    
                5       22.95       0.8462E-01   -1.317    
                6       18.46       0.1590       -1.323    
                7       14.69       0.1408       -1.318    
                8       9.276       0.9085E-01   -1.294    
                9       5.856       0.5739E-01   -1.244    
               10       3.697       0.3623E-01   -1.165    
               11       2.334       0.2287E-01   -1.095    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.976    

 -2LogLikelihood:    49.633    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.544       6.604      [  1.303    ,   1.786    ]
 F             0.7926      0.7924       3.771      [ 0.7218    ,  0.8631    ]
 KA2            2.407       2.408       9.205      [  1.884    ,   2.933    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.00      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         -.414E-05 0.893E-03
 KA2       0.527E-04 0.116E-04 0.491E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.14        21.74        -3.597        9.182    
      3       1.000        20.66        25.90        -5.242        12.88    
      4       1.500        19.50        25.07        -5.571        12.08    
      5       2.000        17.65        22.96        -5.308        10.18    
      6       3.000        14.16        18.47        -4.310        6.693    
      7       4.000        11.25        14.70        -3.448        4.323    
      8       6.000        7.090        9.281        -2.191        1.822    
      9       8.000        4.470        5.859        -1.389       0.7903    
     10       10.00        2.820        3.699       -0.8786       0.3577    
     11       12.00        1.780        2.335       -0.5549       0.1717    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.74        1.021       -1.175    
                3       25.90       0.5026       -1.459    
                4       25.07       0.1106       -1.603    
                5       22.96       0.8508E-01   -1.663    
                6       18.47       0.1630       -1.665    
                7       14.70       0.1448       -1.658    
                8       9.281       0.9350E-01   -1.623    
                9       5.859       0.5907E-01   -1.562    
               10       3.699       0.3729E-01   -1.469    
               11       2.335       0.2354E-01   -1.339    

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.991    

 -2LogLikelihood:    39.860    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.596      [  1.304    ,   1.785    ]
 F             0.7926      0.7925       3.767      [ 0.7219    ,  0.8631    ]
 KA2            2.422       2.423       8.974      [  1.909    ,   2.937    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.00      1.00
 KA2        -0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         -.438E-07 0.891E-03
 KA2       -.126E-04 0.898E-06 0.473E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.43        21.81        -2.376        9.237    
      3       1.000        22.13        25.94        -3.806        12.91    
      4       1.500        20.88        25.08        -4.199        12.09    
      5       2.000        18.91        22.95        -4.042        10.18    
      6       3.000        15.16        18.46        -3.299        6.686    
      7       4.000        12.04        14.69        -2.648        4.318    
      8       6.000        7.580        9.274        -1.694        1.820    
      9       8.000        4.770        5.855        -1.085       0.7893    
     10       10.00        3.010        3.696       -0.6860       0.3573    
     11       12.00        1.880        2.333       -0.4532       0.1716    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.81       0.9921      -0.7693    
                3       25.94       0.4829       -1.057    
                4       25.08       0.1025       -1.208    
                5       22.95       0.8483E-01   -1.267    
                6       18.46       0.1581       -1.275    
                7       14.69       0.1398       -1.274    
                8       9.274       0.9016E-01   -1.256    
                9       5.855       0.5695E-01   -1.221    
               10       3.696       0.3596E-01   -1.147    
               11       2.333       0.2270E-01   -1.094    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)          0.996    

 -2LogLikelihood:    35.313    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.605      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.773      [ 0.7218    ,  0.8632    ]
 KA2            2.431       2.431       8.849      [  1.923    ,   2.940    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F          -0.00      1.00
 KA2         0.00      0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         -.295E-05 0.894E-03
 KA2       0.253E-05 0.251E-05 0.463E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.18        21.85        -1.666        9.269    
      3       1.000        22.98        25.96        -2.977        12.93    
      4       1.500        21.69        25.08        -3.393        12.09    
      5       2.000        19.64        22.95        -3.309        10.18    
      6       3.000        15.75        18.45        -2.702        6.681    
      7       4.000        12.51        14.68        -2.172        4.314    
      8       6.000        7.870        9.271        -1.401        1.818    
      9       8.000        4.960        5.852       -0.8924       0.7887    
     10       10.00        3.120        3.695       -0.5745       0.3570    
     11       12.00        1.950        2.332       -0.3823       0.1715    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.85       0.9771      -0.5347    
                3       25.96       0.4724      -0.8258    
                4       25.08       0.9822E-01  -0.9756    
                5       22.95       0.8470E-01   -1.037    
                6       18.45       0.1556       -1.045    
                7       14.68       0.1372       -1.045    
                8       9.271       0.8840E-01   -1.038    
                9       5.852       0.5584E-01   -1.004    
               10       3.695       0.3525E-01  -0.9612    
               11       2.332       0.2225E-01  -0.9230    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:    51.787    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KA1            1.546       1.545       6.603      [  1.303    ,   1.786    ]
 F             0.7926      0.7925       3.770      [ 0.7218    ,  0.8631    ]
 KA2            2.405       2.407       9.214      [  1.882    ,   2.931    ]
 KE            0.2300       Not estimated
 V              21.00       Not estimated


 SDslope       0.1347    
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KA1       F         KA2       
 KA1         1.00
 F           0.00      1.00
 KA2        -0.00     -0.00      1.00


  Covariance Matrix

           KA1       F         KA2       
 KA1       0.104E-01
 F         0.270E-05 0.893E-03
 KA2       -.275E-04 -.454E-05 0.492E-01


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.93        21.73        -3.800        9.176    
      3       1.000        20.43        25.90        -5.468        12.87    
      4       1.500        19.28        25.07        -5.790        12.08    
      5       2.000        17.45        22.96        -5.508        10.19    
      6       3.000        14.00        18.47        -4.471        6.694    
      7       4.000        11.12        14.70        -3.579        4.324    
      8       6.000        7.000        9.281        -2.281        1.822    
      9       8.000        4.410        5.859        -1.449       0.7904    
     10       10.00        2.770        3.699       -0.9288       0.3577    
     11       12.00        1.740        2.335       -0.5950       0.1718    

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       21.73        1.023       -1.243    
                3       25.90       0.5053       -1.522    
                4       25.07       0.1123       -1.666    
                5       22.96       0.8480E-01   -1.726    
                6       18.47       0.1635       -1.728    
                7       14.70       0.1454       -1.721    
                8       9.281       0.9393E-01   -1.690    
                9       5.859       0.5934E-01   -1.630    
               10       3.699       0.3746E-01   -1.553    
               11       2.335       0.2365E-01   -1.435    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 13:53:58 2018

 Data file name: data_null.csv

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    3000

 Total number of EM iterations:   30

 Normal distribution option

 -2logLikelihood:    814.522    

 Model Selection Criteria
  AIC:        828.522    
  BIC:        853.553    

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KA1          1.54        445.         0.983E-01    6.37       0.107E+05
  F           0.792        28.8         0.286E-01    3.62        135.    
  KA2          2.41        519.         0.223        9.24       0.144E+05
  KE          0.230      Not estimated
  V            21.0      Not estimated

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KA1       F         KA2       
 KA1       0.966E-02
 F          0.00     0.821E-03
 KA2        0.00      0.00     0.498E-01

  Standard Errors of Estimated Covariance Matrix:

           KA1       F         KA2       
 KA1         2.1    
 F          -1.0      0.22E-02
 KA2        -1.0      -1.0       14.    

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope     0.135       49.2    
  SDinter     0.100      Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  2) =   1.543045         ! KA1       
       Pmean(  4) =  0.7923853         ! F         
       Pmean(  5) =   2.414569         ! KA2       
 
       Pcov(  2,  2) =  0.9662988E-02  ! KA1        & KA1       
       Pcov(  4,  2) =   0.000000      ! F          & KA1       
       Pcov(  4,  4) =  0.8208078E-03  ! F          & F         
       Pcov(  5,  2) =   0.000000      ! KA2        & KA1       
       Pcov(  5,  4) =   0.000000      ! KA2        & F         
       Pcov(  5,  5) =  0.4981113E-01  ! KA2        & KA2       

      ________________________________________


 List of Files Created

  Record of program run and all results:
    C.run
  Summary of population estimates at each iteration:
    CIT.csv
  Individual subject estimates at final iteration:
    CIND.csv
  Table of predictions and residuals for each subject:
    CRSD.csv
  Information for plotting model predictions for each subject:
    CPLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    C.eps
  Command file for subsequent Batch runs:
    C.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 13:53:59 2018

