
  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:55:01 2018


 Enter file name for storing session run (*.run): D.run

      ----- MODEL INPUT/OUTPUT INFORMATION -----

 Enter the data file name (*.dat): data_null.csv

    - Successfully read all   24 subjects in the data file.

     ----- INITIALIZE PARAMETERS -----

 Enter parameter file name (*.prm or *IND.csv):  param_null.prm

 Indicate which parameters are to be estimated: 

               Value     Estimate? (Y/N)
 KE         0.2300           y
 KA1         2.000           y
 V           21.00           y
 F          0.8000           y
 KA2         2.000           y
 SDinter    0.1000           n
 SDslope    0.1000           y

 Select parameter distribution model (1 - Normal, 2 - Lognormal):  2

 Select full or diagonal covariance matrix (1 - Full, 2 - Diagonal):  2

 Enter number of samples/EM iteration (1000 -   3000):      3000

 Enter number of EM iterations:        30


      ________________________________________



      ----- INDIVIDUAL SUBJECT RESULTS -----

 EM Iteration:  30

 Iteration:   30
  Subj. #:    1
  Subject: S1A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.723    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1631      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2687      [  1.495    ,   1.516    ]
 V              26.15       26.18       2.960      [  24.18    ,   28.17    ]
 F             0.9950      0.9961       2.960      [ 0.9203    ,   1.072    ]
 KA2            2.801       2.802      0.4125      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.23      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.140E-06
 KA1       -.354E-06 0.164E-04
 V         -.328E-05 0.375E-04 0.600    
 F         0.889E-07 -.115E-05 0.228E-01 0.869E-03
 KA2       -.190E-08 0.166E-07 -.911E-05 -.336E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.20        13.21       -0.1337E-01   0.2091E-02
      3       1.000        18.00        18.00       -0.4999E-02   0.6781E-03
      4       1.500        19.00        18.98        0.1574E-01   0.4848E-03
      5       2.000        18.30        18.31       -0.6015E-02   0.6152E-03
      6       3.000        15.40        15.44       -0.3555E-01   0.1339E-02
      7       4.000        12.50        12.46        0.3602E-01   0.2382E-02
      8       6.000        7.920        7.917        0.3462E-02   0.4554E-02
      9       8.000        5.000        5.002       -0.2165E-02   0.6313E-02
     10       10.00        3.160        3.159        0.5931E-03   0.7573E-02
     11       12.00        1.990        1.995       -0.5444E-02   0.8428E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.21       0.1846E-01  -0.2932    
                3       18.00       0.1578E-01  -0.1935    
                4       18.98       0.1316E-01   0.7135    
                5       18.31       0.1393E-01  -0.2438    
                6       15.44       0.1587E-01  -0.9723    
                7       12.46       0.1565E-01   0.7376    
                8       7.917       0.1383E-01   0.5113E-01
                9       5.002       0.1176E-01  -0.2734E-01
               10       3.159       0.9540E-02   0.6766E-02
               11       1.995       0.7421E-02  -0.5933E-01

 Iteration:   30
  Subj. #:    2
  Subject: S2A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.427    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1624      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2587      [  1.495    ,   1.515    ]
 V              25.71       25.73       2.960      [  23.77    ,   27.68    ]
 F              1.008       1.008       2.960      [ 0.9316    ,   1.085    ]
 KA2            2.801       2.802      0.4134      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.26      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.139E-06
 KA1       -.377E-06 0.152E-04
 V         -.348E-05 0.355E-04 0.580    
 F         0.796E-07 -.108E-05 0.227E-01 0.891E-03
 KA2       -.149E-08 0.289E-07 0.593E-06 0.986E-08 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.60        13.61       -0.1096E-01   0.1944E-02
      3       1.000        18.54        18.55       -0.6310E-02   0.5672E-03
      4       1.500        19.57        19.55        0.1534E-01   0.3871E-03
      5       2.000        18.85        18.86       -0.5800E-02   0.5083E-03
      6       3.000        15.86        15.90       -0.3890E-01   0.1203E-02
      7       4.000        12.88        12.84        0.4194E-01   0.2234E-02
      8       6.000        8.160        8.154        0.5889E-02   0.4423E-02
      9       8.000        5.150        5.152       -0.2280E-02   0.6215E-02
     10       10.00        3.250        3.254       -0.4222E-02   0.7505E-02
     11       12.00        2.050        2.055       -0.5330E-02   0.8383E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.61       0.1785E-01  -0.2492    
                3       18.55       0.1482E-01  -0.2665    
                4       19.55       0.1201E-01   0.7781    
                5       18.86       0.1290E-01  -0.2586    
                6       15.90       0.1513E-01   -1.122    
                7       12.84       0.1515E-01   0.8870    
                8       8.154       0.1370E-01   0.8838E-01
                9       5.152       0.1182E-01  -0.2901E-01
               10       3.254       0.9654E-02  -0.4879E-01
               11       2.055       0.7539E-02  -0.5824E-01

 Iteration:   30
  Subj. #:    3
  Subject: S3A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.103    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1639      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2779      [  1.494    ,   1.516    ]
 V              26.60       26.65       2.957      [  24.62    ,   28.68    ]
 F             0.9819      0.9838       2.957      [ 0.9090    ,   1.059    ]
 KA2            2.801       2.802      0.4128      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.21      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.142E-06
 KA1       -.328E-06 0.175E-04
 V         -.331E-05 0.452E-04 0.621    
 F         0.896E-07 -.982E-06 0.229E-01 0.846E-03
 KA2       0.131E-07 0.249E-07 0.257E-05 0.115E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.80        12.82       -0.1553E-01   0.2243E-02
      3       1.000        17.46        17.46       -0.3794E-02   0.7988E-03
      4       1.500        18.43        18.41        0.1565E-01   0.5933E-03
      5       2.000        17.75        17.76       -0.6990E-02   0.7322E-03
      6       3.000        14.94        14.97       -0.3318E-01   0.1482E-02
      7       4.000        12.13        12.09        0.3911E-01   0.2533E-02
      8       6.000        7.680        7.680        0.2373E-03   0.4686E-02
      9       8.000        4.850        4.853       -0.2656E-02   0.6411E-02
     10       10.00        3.070        3.065        0.4963E-02   0.7640E-02
     11       12.00        1.930        1.936       -0.5880E-02   0.8473E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.82       0.1903E-01  -0.3287    
                3       17.46       0.1674E-01  -0.1357    
                4       18.41       0.1429E-01   0.6412    
                5       17.76       0.1491E-01  -0.2596    
                6       14.97       0.1653E-01  -0.8628    
                7       12.09       0.1609E-01   0.7766    
                8       7.680       0.1393E-01   0.3297E-02
                9       4.853       0.1170E-01  -0.3326E-01
               10       3.065       0.9423E-02   0.5673E-01
               11       1.936       0.7302E-02  -0.6391E-01

 Iteration:   30
  Subj. #:    4
  Subject: S4A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.486    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1645      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2839      [  1.494    ,   1.516    ]
 V              26.91       26.98       2.956      [  24.93    ,   29.03    ]
 F             0.9732      0.9754       2.955      [ 0.9013    ,   1.049    ]
 KA2            2.801       2.802      0.4132      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.19      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.143E-06
 KA1       -.314E-06 0.183E-04
 V         -.317E-05 0.456E-04 0.636    
 F         0.962E-07 -.104E-05 0.230E-01 0.831E-03
 KA2       -.723E-08 -.103E-07 0.104E-04 0.355E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.54        12.55       -0.1220E-01   0.2346E-02
      3       1.000        17.10        17.11       -0.5089E-02   0.8843E-03
      4       1.500        18.05        18.04        0.1379E-01   0.6714E-03
      5       2.000        17.39        17.39       -0.2401E-02   0.8155E-03
      6       3.000        14.63        14.67       -0.3575E-01   0.1581E-02
      7       4.000        11.88        11.84        0.3741E-01   0.2637E-02
      8       6.000        7.520        7.522       -0.1960E-02   0.4775E-02
      9       8.000        4.750        4.753       -0.2880E-02   0.6476E-02
     10       10.00        3.000        3.002       -0.1976E-02   0.7686E-02
     11       12.00        1.890        1.896       -0.6025E-02   0.8503E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.55       0.1942E-01  -0.2525    
                3       17.11       0.1740E-01  -0.1725    
                4       18.04       0.1504E-01   0.5307    
                5       17.39       0.1555E-01  -0.8530E-01
                6       14.67       0.1694E-01  -0.9000    
                7       11.84       0.1635E-01   0.7280    
                8       7.522       0.1398E-01  -0.2854E-01
                9       4.753       0.1165E-01  -0.3588E-01
               10       3.002       0.9346E-02  -0.2258E-01
               11       1.896       0.7224E-02  -0.6536E-01

 Iteration:   30
  Subj. #:    5
  Subject: S5A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.241    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1617      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2507      [  1.495    ,   1.515    ]
 V              25.43       25.43       2.958      [  23.50    ,   27.37    ]
 F              1.016       1.016       2.957      [ 0.9391    ,   1.094    ]
 KA2            2.801       2.802      0.4134      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.28      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.138E-06
 KA1       -.389E-06 0.142E-04
 V         -.338E-05 0.344E-04 0.566    
 F         0.812E-07 -.101E-05 0.226E-01 0.904E-03
 KA2       -.786E-09 -.485E-07 0.196E-04 0.796E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.86        13.87       -0.1473E-01   0.1850E-02
      3       1.000        18.90        18.91       -0.6825E-02   0.4989E-03
      4       1.500        19.95        19.94        0.1436E-01   0.3279E-03
      5       2.000        19.22        19.22       -0.3770E-02   0.4424E-03
      6       3.000        16.17        16.21       -0.3977E-01   0.1117E-02
      7       4.000        13.13        13.09        0.4070E-01   0.2137E-02
      8       6.000        8.320        8.314        0.6195E-02   0.4336E-02
      9       8.000        5.250        5.253       -0.3226E-02   0.6150E-02
     10       10.00        3.320        3.318        0.1996E-02   0.7460E-02
     11       12.00        2.090        2.096       -0.5628E-02   0.8352E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.87       0.1733E-01  -0.3431    
                3       18.91       0.1412E-01  -0.3072    
                4       19.94       0.1123E-01   0.7911    
                5       19.22       0.1220E-01  -0.1806    
                6       16.21       0.1462E-01   -1.191    
                7       13.09       0.1479E-01   0.8799    
                8       8.314       0.1360E-01   0.9390E-01
                9       5.253       0.1184E-01  -0.4122E-01
               10       3.318       0.9719E-02   0.2306E-01
               11       2.096       0.7609E-02  -0.6161E-01

 Iteration:   30
  Subj. #:    6
  Subject: S6A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.063    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1606      [ 0.2288    ,  0.2307    ]
 KA1            1.506       1.506      0.2389      [  1.497    ,   1.515    ]
 V              25.03       25.02       2.959      [  23.11    ,   26.92    ]
 F              1.029       1.028       2.959      [ 0.9499    ,   1.106    ]
 KA2            2.801       2.802      0.4129      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.31      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.136E-06
 KA1       -.409E-06 0.129E-04
 V         -.338E-05 0.309E-04 0.548    
 F         0.774E-07 -.991E-06 0.225E-01 0.925E-03
 KA2       -.647E-09 0.159E-07 -.134E-04 -.568E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        14.26        14.27       -0.1354E-01   0.1711E-02
      3       1.000        19.44        19.45       -0.7338E-02   0.4046E-03
      4       1.500        20.52        20.50        0.1679E-01   0.2489E-03
      5       2.000        19.76        19.77       -0.9385E-02   0.3532E-03
      6       3.000        16.63        16.67       -0.3807E-01   0.9943E-03
      7       4.000        13.50        13.46        0.4140E-01   0.1999E-02
      8       6.000        8.550        8.548        0.2174E-02   0.4210E-02
      9       8.000        5.400        5.401       -0.8355E-03   0.6055E-02
     10       10.00        3.410        3.411       -0.1078E-02   0.7394E-02
     11       12.00        2.150        2.154       -0.4313E-02   0.8308E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       14.27       0.1651E-01  -0.3281    
                3       19.45       0.1303E-01  -0.3665    
                4       20.50       0.1005E-01    1.063    
                5       19.77       0.1119E-01  -0.5008    
                6       16.67       0.1385E-01   -1.208    
                7       13.46       0.1425E-01   0.9254    
                8       8.548       0.1344E-01   0.3333E-01
                9       5.401       0.1187E-01  -0.1083E-01
               10       3.411       0.9805E-02  -0.1259E-01
               11       2.154       0.7704E-02  -0.4735E-01

 Iteration:   30
  Subj. #:    7
  Subject: S7A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.140    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1654      [ 0.2288    ,  0.2307    ]
 KA1            1.504       1.505      0.2920      [  1.493    ,   1.516    ]
 V              27.41       27.49       2.959      [  25.40    ,   29.58    ]
 F             0.9597      0.9626       2.959      [ 0.8894    ,   1.036    ]
 KA2            2.801       2.802      0.4125      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.17      1.00
 V          -0.01      0.02      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.144E-06
 KA1       -.289E-06 0.193E-04
 V         -.286E-05 0.565E-04 0.662    
 F         0.110E-06 -.784E-06 0.232E-01 0.811E-03
 KA2       0.758E-09 -.422E-07 0.252E-04 0.886E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.14        12.15       -0.1490E-01   0.2507E-02
      3       1.000        16.56        16.56       -0.4130E-02   0.1021E-02
      4       1.500        17.48        17.47        0.1383E-01   0.7983E-03
      5       2.000        16.84        16.84       -0.2969E-02   0.9495E-03
      6       3.000        14.17        14.20       -0.3274E-01   0.1735E-02
      7       4.000        11.50        11.47        0.3116E-01   0.2797E-02
      8       6.000        7.290        7.285        0.5334E-02   0.4911E-02
      9       8.000        4.600        4.603       -0.2992E-02   0.6576E-02
     10       10.00        2.910        2.907        0.2665E-02   0.7754E-02
     11       12.00        1.830        1.836       -0.6269E-02   0.8548E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.15       0.1985E-01  -0.2982    
                3       16.56       0.1826E-01  -0.1306    
                4       17.47       0.1610E-01   0.4881    
                5       16.84       0.1650E-01  -0.9754E-01
                6       14.20       0.1756E-01  -0.7866    
                7       11.47       0.1675E-01   0.5888    
                8       7.285       0.1406E-01   0.7595E-01
                9       4.603       0.1158E-01  -0.3698E-01
               10       2.907       0.9224E-02   0.3022E-01
               11       1.836       0.7102E-02  -0.6783E-01

 Iteration:   30
  Subj. #:    8
  Subject: S8A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.744    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1642      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2812      [  1.494    ,   1.516    ]
 V              26.76       26.81       2.958      [  24.77    ,   28.85    ]
 F             0.9776      0.9796       2.958      [ 0.9051    ,   1.054    ]
 KA2            2.801       2.802      0.4139      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.20      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00      0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.142E-06
 KA1       -.323E-06 0.179E-04
 V         -.384E-05 0.380E-04 0.629    
 F         0.713E-07 -.128E-05 0.230E-01 0.840E-03
 KA2       -.276E-08 0.442E-07 -.191E-04 -.699E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        12.67        12.68       -0.1427E-01   0.2294E-02
      3       1.000        17.28        17.28       -0.4270E-02   0.8410E-03
      4       1.500        18.24        18.22        0.1549E-01   0.6319E-03
      5       2.000        17.57        17.57       -0.3522E-02   0.7735E-03
      6       3.000        14.78        14.82       -0.3799E-01   0.1531E-02
      7       4.000        12.00        11.97        0.3469E-01   0.2586E-02
      8       6.000        7.600        7.600        0.2560E-03   0.4731E-02
      9       8.000        4.800        4.802       -0.1950E-02   0.6444E-02
     10       10.00        3.030        3.033       -0.2920E-02   0.7664E-02
     11       12.00        1.910        1.916       -0.5538E-02   0.8488E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       12.68       0.1927E-01  -0.2986    
                3       17.28       0.1712E-01  -0.1487    
                4       18.22       0.1468E-01   0.6148    
                5       17.57       0.1523E-01  -0.1279    
                6       14.82       0.1672E-01  -0.9717    
                7       11.97       0.1620E-01   0.6818    
                8       7.600       0.1394E-01   0.3553E-02
                9       4.802       0.1166E-01  -0.2438E-01
               10       3.033       0.9376E-02  -0.3340E-01
               11       1.916       0.7257E-02  -0.6014E-01

 Iteration:   30
  Subj. #:    9
  Subject: S9A                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9A                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.716    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1619      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.2545      [  1.495    ,   1.515    ]
 V              25.57       25.58       2.959      [  23.63    ,   27.53    ]
 F              1.012       1.012       2.959      [ 0.9354    ,   1.089    ]
 KA2            2.801       2.802      0.4126      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.27      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00      0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.138E-06
 KA1       -.381E-06 0.147E-04
 V         -.305E-05 0.338E-04 0.573    
 F         0.945E-07 -.109E-05 0.227E-01 0.897E-03
 KA2       0.284E-08 0.233E-07 0.266E-04 0.106E-05 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.73        13.74       -0.1270E-01   0.1896E-02
      3       1.000        18.72        18.73       -0.5895E-02   0.5326E-03
      4       1.500        19.76        19.74        0.1592E-01   0.3571E-03
      5       2.000        19.03        19.04       -0.8500E-02   0.4750E-03
      6       3.000        16.02        16.05       -0.3303E-01   0.1160E-02
      7       4.000        13.00        12.96        0.3742E-01   0.2186E-02
      8       6.000        8.240        8.233        0.6728E-02   0.4380E-02
      9       8.000        5.200        5.202       -0.2344E-02   0.6183E-02
     10       10.00        3.290        3.286        0.4129E-02   0.7483E-02
     11       12.00        2.070        2.075       -0.5337E-02   0.8368E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.74       0.1757E-01  -0.2923    
                3       18.73       0.1445E-01  -0.2570    
                4       19.74       0.1163E-01   0.8412    
                5       19.04       0.1258E-01  -0.3914    
                6       16.05       0.1490E-01  -0.9707    
                7       12.96       0.1499E-01   0.8000    
                8       8.233       0.1366E-01   0.1015    
                9       5.202       0.1183E-01  -0.2990E-01
               10       3.286       0.9684E-02   0.4768E-01
               11       2.075       0.7570E-02  -0.5837E-01

 Iteration:   30
  Subj. #:   10
  Subject: S10A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.163    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1624      [ 0.2288    ,  0.2308    ]
 KA1            1.505       1.505      0.2586      [  1.495    ,   1.515    ]
 V              25.73       25.74       2.958      [  23.78    ,   27.70    ]
 F              1.007       1.008       2.957      [ 0.9312    ,   1.084    ]
 KA2            2.801       2.802      0.4130      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.26      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.139E-06
 KA1       -.375E-06 0.152E-04
 V         -.309E-05 0.390E-04 0.580    
 F         0.951E-07 -.940E-06 0.227E-01 0.888E-03
 KA2       0.226E-08 -.250E-07 -.307E-04 -.120E-05 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1667E-01   0.1949E-02
      3       1.000        18.52        18.53       -0.6332E-02   0.5711E-03
      4       1.500        19.55        19.53        0.1691E-01   0.3906E-03
      5       2.000        18.83        18.83       -0.4538E-02   0.5122E-03
      6       3.000        15.84        15.88       -0.4023E-01   0.1209E-02
      7       4.000        12.86        12.82        0.3759E-01   0.2240E-02
      8       6.000        8.140        8.143       -0.3465E-02   0.4429E-02
      9       8.000        5.130        5.145       -0.1511E-01   0.6220E-02
     10       10.00        3.230        3.249       -0.1941E-01   0.7509E-02
     11       12.00        2.030        2.052       -0.2211E-01   0.8385E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.1784E-01  -0.3782    
                3       18.53       0.1484E-01  -0.2665    
                4       19.53       0.1205E-01   0.8540    
                5       18.83       0.1293E-01  -0.2019    
                6       15.88       0.1514E-01   -1.158    
                7       12.82       0.1516E-01   0.7937    
                8       8.143       0.1370E-01  -0.5224E-01
                9       5.145       0.1181E-01  -0.1917    
               10       3.249       0.9644E-02  -0.2241    
               11       2.052       0.7530E-02  -0.2415    

 Iteration:   30
  Subj. #:   11
  Subject: S11A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.957    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1615      [ 0.2288    ,  0.2308    ]
 KA1            1.505       1.505      0.2512      [  1.495    ,   1.515    ]
 V              25.45       25.45       2.957      [  23.51    ,   27.38    ]
 F              1.016       1.016       2.957      [ 0.9387    ,   1.093    ]
 KA2            2.801       2.802      0.4131      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.28      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2        -0.00     -0.00      0.00      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.138E-06
 KA1       -.389E-06 0.143E-04
 V         -.370E-05 0.383E-04 0.566    
 F         0.681E-07 -.864E-06 0.226E-01 0.902E-03
 KA2       -.179E-08 -.748E-09 0.194E-04 0.768E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.84        13.86       -0.2049E-01   0.1855E-02
      3       1.000        18.88        18.89       -0.6935E-02   0.5025E-03
      4       1.500        19.93        19.91        0.1582E-01   0.3312E-03
      5       2.000        19.20        19.20       -0.2607E-02   0.4461E-03
      6       3.000        16.15        16.19       -0.4117E-01   0.1122E-02
      7       4.000        13.11        13.07        0.3630E-01   0.2143E-02
      8       6.000        8.300        8.303       -0.3160E-02   0.4342E-02
      9       8.000        5.230        5.246       -0.1604E-01   0.6154E-02
     10       10.00        3.300        3.313       -0.1317E-01   0.7463E-02
     11       12.00        2.070        2.092       -0.2239E-01   0.8355E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.86       0.1734E-01  -0.4764    
                3       18.89       0.1414E-01  -0.3110    
                4       19.91       0.1127E-01   0.8679    
                5       19.20       0.1226E-01  -0.1248    
                6       16.19       0.1466E-01   -1.230    
                7       13.07       0.1482E-01   0.7837    
                8       8.303       0.1361E-01  -0.4813E-01
                9       5.246       0.1183E-01  -0.2045    
               10       3.313       0.9703E-02  -0.1525    
               11       2.092       0.7594E-02  -0.2450    

 Iteration:   30
  Subj. #:   12
  Subject: S12A                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12A                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.097    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1625      [ 0.2288    ,  0.2308    ]
 KA1            1.505       1.505      0.2587      [  1.495    ,   1.515    ]
 V              25.73       25.74       2.959      [  23.78    ,   27.70    ]
 F              1.007       1.008       2.959      [ 0.9312    ,   1.085    ]
 KA2            2.801       2.802      0.4132      [  2.772    ,   2.831    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.26      1.00
 V          -0.01      0.01      1.00
 F           0.01     -0.01      1.00      1.00
 KA2         0.00     -0.00     -0.00     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.139E-06
 KA1       -.375E-06 0.152E-04
 V         -.307E-05 0.355E-04 0.580    
 F         0.958E-07 -.107E-05 0.227E-01 0.889E-03
 KA2       0.364E-09 -.146E-07 -.194E-04 -.752E-06 0.134E-03


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        13.58        13.60       -0.1668E-01   0.1949E-02
      3       1.000        18.52        18.53       -0.6332E-02   0.5711E-03
      4       1.500        19.55        19.53        0.1694E-01   0.3906E-03
      5       2.000        18.83        18.83       -0.4482E-02   0.5122E-03
      6       3.000        15.84        15.88       -0.4013E-01   0.1209E-02
      7       4.000        12.86        12.82        0.3772E-01   0.2240E-02
      8       6.000        8.140        8.143       -0.3316E-02   0.4429E-02
      9       8.000        5.130        5.145       -0.1497E-01   0.6220E-02
     10       10.00        3.220        3.249       -0.2930E-01   0.7509E-02
     11       12.00        2.030        2.052       -0.2203E-01   0.8385E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       13.60       0.1785E-01  -0.3785    
                3       18.53       0.1485E-01  -0.2666    
                4       19.53       0.1206E-01   0.8554    
                5       18.83       0.1294E-01  -0.1994    
                6       15.88       0.1516E-01   -1.155    
                7       12.82       0.1517E-01   0.7965    
                8       8.143       0.1371E-01  -0.5000E-01
                9       5.145       0.1182E-01  -0.1899    
               10       3.249       0.9650E-02  -0.3382    
               11       2.052       0.7534E-02  -0.2406    

 Iteration:   30
  Subj. #:   13
  Subject: S1B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S1B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -34.159    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1585      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3649      [  1.491    ,   1.519    ]
 V              26.29       26.29      0.6593E-01  [  26.25    ,   26.34    ]
 F             0.9968      0.9984       3.857      [ 0.8994    ,   1.097    ]
 KA2            2.802       2.802      0.2501      [  2.784    ,   2.820    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.64     -0.00      1.00
 F           0.00      0.00     -0.00      1.00
 KA2        -0.28      0.00      0.59     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.132E-06
 KA1       0.196E-08 0.301E-04
 V         -.402E-05 -.103E-07 0.300E-03
 F         0.114E-09 0.437E-06 -.776E-06 0.148E-02
 KA2       -.717E-06 0.219E-08 0.715E-04 -.114E-06 0.491E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.70        18.71       -0.1030E-01   0.5356E-03
      3       1.000        21.30        21.29        0.9746E-02   0.1574E-03
      4       1.500        20.10        20.12       -0.1616E-01   0.3016E-03
      5       2.000        18.20        18.21       -0.1347E-01   0.6342E-03
      6       3.000        14.60        14.55        0.4590E-01   0.1617E-02
      7       4.000        11.60        11.57        0.2799E-01   0.2753E-02
      8       6.000        7.310        7.310        0.6592E-04   0.4896E-02
      9       8.000        4.610        4.617       -0.7465E-02   0.6566E-02
     10       10.00        2.910        2.917       -0.6714E-02   0.7747E-02
     11       12.00        1.830        1.842       -0.1240E-01   0.8544E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.71       0.1674E-01  -0.4472    
                3       21.29       0.9208E-02   0.7747    
                4       20.12       0.1018E-01  -0.9320    
                5       18.21       0.1107E-01  -0.5356    
                6       14.55       0.1162E-01    1.141    
                7       11.57       0.1222E-01   0.5332    
                8       7.310       0.1235E-01   0.8141E-03
                9       4.617       0.1098E-01  -0.9220E-01
               10       2.917       0.8997E-02  -0.7633E-01
               11       1.842       0.7000E-02  -0.1342    

 Iteration:   30
  Subj. #:   14
  Subject: S2B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S2B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.262    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1560      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3643      [  1.491    ,   1.519    ]
 V              25.28       25.28      0.5728E-01  [  25.24    ,   25.32    ]
 F             0.9969      0.9983       3.851      [ 0.8995    ,   1.097    ]
 KA2            2.803       2.803      0.2231      [  2.787    ,   2.819    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.71      0.00      1.00
 F          -0.00     -0.00      0.00      1.00
 KA2        -0.34      0.00      0.65      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.128E-06
 KA1       -.241E-08 0.301E-04
 V         -.369E-05 0.573E-07 0.210E-03
 F         -.138E-07 -.623E-06 0.100E-05 0.148E-02
 KA2       -.764E-06 0.259E-07 0.592E-04 0.116E-06 0.391E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.45        19.46       -0.1187E-01   0.4022E-03
      3       1.000        22.15        22.14        0.8595E-02   0.8188E-04
      4       1.500        20.90        20.92       -0.1850E-01   0.1980E-03
      5       2.000        18.93        18.94       -0.9136E-02   0.4930E-03
      6       3.000        15.18        15.13        0.4653E-01   0.1432E-02
      7       4.000        12.06        12.03        0.2754E-01   0.2558E-02
      8       6.000        7.600        7.601       -0.5475E-03   0.4731E-02
      9       8.000        4.790        4.801       -0.1088E-01   0.6445E-02
     10       10.00        3.030        3.032       -0.2477E-02   0.7664E-02
     11       12.00        1.900        1.915       -0.1546E-01   0.8488E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.46       0.1468E-01  -0.5939    
                3       22.14       0.7152E-02   0.9473    
                4       20.92       0.8396E-02   -1.316    
                5       18.94       0.9527E-02  -0.4122    
                6       15.13       0.1070E-01    1.230    
                7       12.03       0.1180E-01   0.5444    
                8       7.601       0.1237E-01  -0.8093E-02
                9       4.801       0.1112E-01  -0.1356    
               10       3.032       0.9153E-02  -0.2834E-01
               11       1.915       0.7136E-02  -0.1679    

 Iteration:   30
  Subj. #:   15
  Subject: S3B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S3B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.918    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1605      [ 0.2287    ,  0.2306    ]
 KA1            1.505       1.505      0.3649      [  1.491    ,   1.519    ]
 V              27.38       27.38      0.7540E-01  [  27.33    ,   27.44    ]
 F             0.9968      0.9984       3.851      [ 0.8995    ,   1.097    ]
 KA2            2.800       2.800      0.2745      [  2.781    ,   2.820    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.58     -0.00      1.00
 F           0.00      0.00     -0.00      1.00
 KA2        -0.24     -0.00      0.53      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.136E-06
 KA1       0.478E-09 0.302E-04
 V         -.439E-05 -.257E-06 0.426E-03
 F         0.276E-08 0.599E-06 -.186E-06 0.148E-02
 KA2       -.678E-06 -.697E-07 0.849E-04 0.255E-07 0.591E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.95        17.96       -0.1041E-01   0.6877E-03
      3       1.000        20.45        20.44        0.1025E-01   0.2572E-03
      4       1.500        19.30        19.31       -0.1382E-01   0.4270E-03
      5       2.000        17.47        17.49       -0.1751E-01   0.7933E-03
      6       3.000        14.02        13.97        0.4574E-01   0.1815E-02
      7       4.000        11.14        11.11        0.2893E-01   0.2955E-02
      8       6.000        7.020        7.019        0.1155E-02   0.5065E-02
      9       8.000        4.430        4.434       -0.3647E-02   0.6689E-02
     10       10.00        2.790        2.801       -0.1064E-01   0.7831E-02
     11       12.00        1.760        1.769       -0.9100E-02   0.8599E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.96       0.1849E-01  -0.3989    
                3       20.44       0.1114E-01   0.6374    
                4       19.31       0.1186E-01  -0.6700    
                5       17.49       0.1249E-01  -0.6225    
                6       13.97       0.1246E-01    1.073    
                7       11.11       0.1259E-01   0.5320    
                8       7.019       0.1228E-01   0.1611E-01
                9       4.434       0.1080E-01  -0.4466E-01
               10       2.801       0.8804E-02  -0.1202    
               11       1.769       0.6834E-02  -0.9816E-01

 Iteration:   30
  Subj. #:   16
  Subject: S4B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S4B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -29.795    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1622      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.3641      [  1.491    ,   1.519    ]
 V              28.58       28.58      0.8515E-01  [  28.51    ,   28.64    ]
 F             0.9968      0.9984       3.859      [ 0.8993    ,   1.097    ]
 KA2            2.800       2.801      0.2956      [  2.779    ,   2.822    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.52      0.00      1.00
 F           0.00     -0.00      0.00      1.00
 KA2        -0.20      0.00      0.48      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.139E-06
 KA1       -.186E-08 0.300E-04
 V         -.471E-05 0.193E-06 0.592E-03
 F         0.874E-08 -.264E-06 0.388E-06 0.148E-02
 KA2       -.614E-06 0.587E-07 0.968E-04 0.251E-06 0.686E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.20        17.21       -0.1142E-01   0.8585E-03
      3       1.000        19.60        19.59        0.1347E-01   0.3819E-03
      4       1.500        18.49        18.51       -0.1712E-01   0.5749E-03
      5       2.000        16.74        16.76       -0.1682E-01   0.9714E-03
      6       3.000        13.43        13.39        0.3996E-01   0.2025E-02
      7       4.000        10.67        10.65        0.2369E-01   0.3166E-02
      8       6.000        6.730        6.725        0.5033E-02   0.5238E-02
      9       8.000        4.240        4.248       -0.7826E-02   0.6815E-02
     10       10.00        2.680        2.683       -0.3141E-02   0.7917E-02
     11       12.00        1.680        1.695       -0.1481E-01   0.8656E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.21       0.2005E-01  -0.3915    
                3       19.59       0.1299E-01   0.6876    
                4       18.51       0.1344E-01  -0.7155    
                5       16.76       0.1382E-01  -0.5405    
                6       13.39       0.1328E-01   0.8878    
                7       10.65       0.1299E-01   0.4208    
                8       6.725       0.1224E-01   0.6942E-01
                9       4.248       0.1061E-01  -0.9487E-01
               10       2.683       0.8605E-02  -0.3534E-01
               11       1.695       0.6659E-02  -0.1592    

 Iteration:   30
  Subj. #:   17
  Subject: S5B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S5B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.363    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1525      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3642      [  1.491    ,   1.519    ]
 V              24.34       24.34      0.4880E-01  [  24.31    ,   24.37    ]
 F             0.9969      0.9983       3.853      [ 0.8994    ,   1.097    ]
 KA2            2.804       2.804      0.1929      [  2.790    ,   2.817    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.79     -0.00      1.00
 F          -0.00      0.00      0.00      1.00
 KA2        -0.41      0.00      0.73      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.123E-06
 KA1       0.922E-09 0.300E-04
 V         -.329E-05 -.192E-07 0.141E-03
 F         -.165E-07 0.133E-06 0.121E-05 0.148E-02
 KA2       -.782E-06 0.711E-08 0.472E-04 0.372E-06 0.293E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.20        20.21       -0.1294E-01   0.2880E-03
      3       1.000        23.00        23.00        0.4668E-02   0.3070E-04
      4       1.500        21.71        21.73       -0.1506E-01   0.1158E-03
      5       2.000        19.66        19.67       -0.9326E-02   0.3688E-03
      6       3.000        15.77        15.72        0.5302E-01   0.1256E-02
      7       4.000        12.53        12.50        0.3353E-01   0.2369E-02
      8       6.000        7.890        7.894       -0.3747E-02   0.4566E-02
      9       8.000        4.980        4.986       -0.6141E-02   0.6323E-02
     10       10.00        3.140        3.150       -0.9532E-02   0.7580E-02
     11       12.00        1.970        1.989       -0.1943E-01   0.8432E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.21       0.1222E-01  -0.7644    
                3       23.00       0.4807E-02   0.8393    
                4       21.73       0.6485E-02   -1.401    
                5       19.67       0.7922E-02  -0.4864    
                6       15.72       0.9837E-02    1.496    
                7       12.50       0.1144E-01   0.6886    
                8       7.894       0.1239E-01  -0.5558E-01
                9       4.986       0.1123E-01  -0.7731E-01
               10       3.150       0.9268E-02  -0.1095    
               11       1.989       0.7236E-02  -0.2116    

 Iteration:   30
  Subj. #:   18
  Subject: S6B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S6B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.399    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1552      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3648      [  1.491    ,   1.519    ]
 V              25.03       25.03      0.5497E-01  [  25.00    ,   25.07    ]
 F             0.9969      0.9984       3.856      [ 0.8994    ,   1.097    ]
 KA2            2.803       2.803      0.2155      [  2.788    ,   2.819    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.73      0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.35      0.00      0.67     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.127E-06
 KA1       0.465E-09 0.301E-04
 V         -.358E-05 0.597E-07 0.189E-03
 F         0.182E-07 -.345E-06 -.681E-06 0.148E-02
 KA2       -.761E-06 0.527E-08 0.558E-04 -.223E-06 0.365E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.64        19.66       -0.1509E-01   0.3710E-03
      3       1.000        22.37        22.36        0.8606E-02   0.6634E-04
      4       1.500        21.11        21.13       -0.1630E-01   0.1747E-03
      5       2.000        19.11        19.13       -0.1714E-01   0.4593E-03
      6       3.000        15.33        15.28        0.4659E-01   0.1385E-02
      7       4.000        12.18        12.15        0.2857E-01   0.2509E-02
      8       6.000        7.680        7.675        0.4613E-02   0.4688E-02
      9       8.000        4.840        4.848       -0.7959E-02   0.6414E-02
     10       10.00        3.060        3.062       -0.2088E-02   0.7643E-02
     11       12.00        1.920        1.934       -0.1409E-01   0.8474E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.66       0.1409E-01  -0.7855    
                3       22.36       0.6576E-02    1.054    
                4       21.13       0.7914E-02   -1.235    
                5       19.13       0.9130E-02  -0.8005    
                6       15.28       0.1050E-01    1.251    
                7       12.15       0.1173E-01   0.5702    
                8       7.675       0.1240E-01   0.6723E-01
                9       4.848       0.1116E-01  -0.9945E-01
               10       3.062       0.9193E-02  -0.2393E-01
               11       1.934       0.7169E-02  -0.1531    

 Iteration:   30
  Subj. #:   19
  Subject: S7B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S7B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.730    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1608      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.3643      [  1.491    ,   1.519    ]
 V              27.67       27.67      0.7764E-01  [  27.61    ,   27.72    ]
 F             0.9968      0.9984       3.849      [ 0.8996    ,   1.097    ]
 KA2            2.801       2.802      0.2803      [  2.781    ,   2.822    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.56     -0.00      1.00
 F          -0.00      0.00      0.00      1.00
 KA2        -0.23     -0.00      0.52      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.136E-06
 KA1       0.105E-08 0.301E-04
 V         -.446E-05 -.160E-06 0.461E-03
 F         -.246E-07 0.622E-06 0.227E-05 0.148E-02
 KA2       -.665E-06 -.575E-07 0.882E-04 0.499E-06 0.617E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.77        17.78       -0.8224E-02   0.7275E-03
      3       1.000        20.24        20.23        0.1020E-01   0.2856E-03
      4       1.500        19.10        19.11       -0.1415E-01   0.4616E-03
      5       2.000        17.29        17.31       -0.1612E-01   0.8358E-03
      6       3.000        13.87        13.83        0.4121E-01   0.1866E-02
      7       4.000        11.02        11.00        0.2490E-01   0.3007E-02
      8       6.000        6.940        6.945       -0.5221E-02   0.5108E-02
      9       8.000        4.380        4.387       -0.6909E-02   0.6721E-02
     10       10.00        2.760        2.771       -0.1097E-01   0.7853E-02
     11       12.00        1.740        1.750       -0.1027E-01   0.8614E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.78       0.1889E-01  -0.3069    
                3       20.23       0.1157E-01   0.6015    
                4       19.11       0.1224E-01  -0.6602    
                5       17.31       0.1282E-01  -0.5584    
                6       13.83       0.1265E-01   0.9537    
                7       11.00       0.1268E-01   0.4539    
                8       6.945       0.1226E-01  -0.7318E-01
                9       4.387       0.1074E-01  -0.8434E-01
               10       2.771       0.8747E-02  -0.1238    
               11       1.750       0.6785E-02  -0.1106    

 Iteration:   30
  Subj. #:   20
  Subject: S8B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S8B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.755    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1568      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3651      [  1.491    ,   1.519    ]
 V              25.52       25.52      0.5940E-01  [  25.49    ,   25.56    ]
 F             0.9969      0.9983       3.856      [ 0.8994    ,   1.097    ]
 KA2            2.802       2.802      0.2296      [  2.786    ,   2.819    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.69     -0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.32     -0.00      0.64     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.130E-06
 KA1       0.312E-08 0.302E-04
 V         -.378E-05 -.153E-06 0.230E-03
 F         0.708E-08 -.434E-06 -.600E-06 0.148E-02
 KA2       -.752E-06 -.168E-07 0.620E-04 -.136E-06 0.414E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.26        19.27       -0.1349E-01   0.4339E-03
      3       1.000        21.94        21.93        0.1006E-01   0.9835E-04
      4       1.500        20.70        20.72       -0.2006E-01   0.2216E-03
      5       2.000        18.75        18.76       -0.1007E-01   0.5262E-03
      6       3.000        15.04        14.99        0.4918E-01   0.1476E-02
      7       4.000        11.95        11.92        0.3074E-01   0.2605E-02
      8       6.000        7.530        7.529        0.6972E-03   0.4771E-02
      9       8.000        4.750        4.756       -0.6045E-02   0.6474E-02
     10       10.00        3.000        3.004       -0.4259E-02   0.7684E-02
     11       12.00        1.880        1.898       -0.1771E-01   0.8502E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.27       0.1520E-01  -0.6499    
                3       21.93       0.7696E-02    1.012    
                4       20.72       0.8853E-02   -1.349    
                5       18.76       0.9918E-02  -0.4397    
                6       14.99       0.1093E-01    1.280    
                7       11.92       0.1191E-01   0.6021    
                8       7.529       0.1238E-01   0.9963E-02
                9       4.756       0.1110E-01  -0.7521E-01
               10       3.004       0.9126E-02  -0.4863E-01
               11       1.898       0.7113E-02  -0.1921    

 Iteration:   30
  Subj. #:   21
  Subject: S9B                 

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S9B                 

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.920    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1601      [ 0.2288    ,  0.2306    ]
 KA1            1.505       1.505      0.3640      [  1.491    ,   1.519    ]
 V              27.10       27.10      0.7287E-01  [  27.05    ,   27.15    ]
 F             0.9968      0.9984       3.851      [ 0.8996    ,   1.097    ]
 KA2            2.801       2.801      0.2685      [  2.782    ,   2.821    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.59      0.00      1.00
 F           0.00     -0.00     -0.00      1.00
 KA2        -0.25      0.00      0.55     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.135E-06
 KA1       -.330E-08 0.300E-04
 V         -.428E-05 0.361E-06 0.390E-03
 F         0.420E-08 -.160E-06 -.128E-05 0.148E-02
 KA2       -.684E-06 0.320E-07 0.813E-04 -.386E-06 0.566E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        18.14        18.15       -0.8140E-02   0.6478E-03
      3       1.000        20.66        20.65        0.8915E-02   0.2301E-03
      4       1.500        19.50        19.51       -0.1242E-01   0.3939E-03
      5       2.000        17.65        17.67       -0.1686E-01   0.7523E-03
      6       3.000        14.16        14.12        0.4276E-01   0.1765E-02
      7       4.000        11.25        11.22        0.2542E-01   0.2904E-02
      8       6.000        7.090        7.090       -0.3474E-03   0.5023E-02
      9       8.000        4.470        4.479       -0.8686E-02   0.6659E-02
     10       10.00        2.820        2.829       -0.9007E-02   0.7811E-02
     11       12.00        1.780        1.787       -0.6971E-02   0.8586E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       18.15       0.1807E-01  -0.3219    
                3       20.65       0.1065E-01   0.5856    
                4       19.51       0.1145E-01  -0.6273    
                5       17.67       0.1216E-01  -0.6155    
                6       14.12       0.1227E-01    1.018    
                7       11.22       0.1252E-01   0.4715    
                8       7.090       0.1232E-01  -0.5026E-02
                9       4.479       0.1086E-01  -0.1065    
               10       2.829       0.8865E-02  -0.1019    
               11       1.787       0.6884E-02  -0.7525E-01

 Iteration:   30
  Subj. #:   22
  Subject: S10B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S10B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -33.136    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1557      [ 0.2289    ,  0.2307    ]
 KA1            1.505       1.505      0.3645      [  1.491    ,   1.519    ]
 V              25.30       25.30      0.5740E-01  [  25.27    ,   25.34    ]
 F             0.9968      0.9983       3.857      [ 0.8993    ,   1.097    ]
 KA2            2.803       2.803      0.2238      [  2.787    ,   2.819    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.71     -0.00      1.00
 F          -0.00      0.00     -0.00      1.00
 KA2        -0.34     -0.00      0.65     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.128E-06
 KA1       0.413E-09 0.301E-04
 V         -.368E-05 -.725E-07 0.211E-03
 F         -.110E-07 0.591E-06 -.391E-06 0.148E-02
 KA2       -.760E-06 -.112E-07 0.593E-04 -.597E-09 0.394E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        19.43        19.44       -0.1384E-01   0.4052E-03
      3       1.000        22.13        22.12        0.9475E-02   0.8344E-04
      4       1.500        20.88        20.90       -0.1826E-01   0.2004E-03
      5       2.000        18.91        18.92       -0.1026E-01   0.4964E-03
      6       3.000        15.16        15.12        0.4256E-01   0.1437E-02
      7       4.000        12.04        12.02        0.2105E-01   0.2563E-02
      8       6.000        7.580        7.591       -0.1105E-01   0.4736E-02
      9       8.000        4.770        4.794       -0.2427E-01   0.6449E-02
     10       10.00        3.010        3.028       -0.1791E-01   0.7667E-02
     11       12.00        1.880        1.912       -0.3234E-01   0.8491E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       19.44       0.1475E-01  -0.6895    
                3       22.12       0.7208E-02    1.035    
                4       20.90       0.8434E-02   -1.291    
                5       18.92       0.9558E-02  -0.4612    
                6       15.12       0.1071E-01    1.123    
                7       12.02       0.1179E-01   0.4155    
                8       7.591       0.1235E-01  -0.1607    
                9       4.794       0.1109E-01  -0.3023    
               10       3.028       0.9127E-02  -0.2046    
               11       1.912       0.7115E-02  -0.3510    

 Iteration:   30
  Subj. #:   23
  Subject: S11B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S11B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -31.211    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2298      0.2298      0.1529      [ 0.2289    ,  0.2307    ]
 KA1            1.505       1.505      0.3648      [  1.491    ,   1.519    ]
 V              24.36       24.36      0.4904E-01  [  24.33    ,   24.39    ]
 F             0.9968      0.9984       3.856      [ 0.8995    ,   1.097    ]
 KA2            2.803       2.803      0.1937      [  2.789    ,   2.817    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1         0.00      1.00
 V          -0.79     -0.00      1.00
 F           0.00      0.00     -0.00      1.00
 KA2        -0.41      0.00      0.73     -0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.123E-06
 KA1       0.692E-09 0.301E-04
 V         -.331E-05 -.293E-07 0.143E-03
 F         0.883E-08 0.328E-07 -.954E-06 0.148E-02
 KA2       -.778E-06 0.145E-07 0.474E-04 -.420E-06 0.295E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        20.18        20.20       -0.1503E-01   0.2905E-03
      3       1.000        22.98        22.97        0.5237E-02   0.3165E-04
      4       1.500        21.69        21.71       -0.1511E-01   0.1175E-03
      5       2.000        19.64        19.65       -0.1066E-01   0.3717E-03
      6       3.000        15.75        15.70        0.4903E-01   0.1261E-02
      7       4.000        12.51        12.48        0.2716E-01   0.2374E-02
      8       6.000        7.870        7.884       -0.1399E-01   0.4572E-02
      9       8.000        4.960        4.979       -0.1926E-01   0.6328E-02
     10       10.00        3.120        3.145       -0.2473E-01   0.7583E-02
     11       12.00        1.950        1.986       -0.3610E-01   0.8435E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       20.20       0.1229E-01  -0.8842    
                3       22.97       0.4866E-02   0.9278    
                4       21.71       0.6533E-02   -1.396    
                5       19.65       0.7969E-02  -0.5537    
                6       15.70       0.9876E-02    1.381    
                7       12.48       0.1147E-01   0.5571    
                8       7.884       0.1241E-01  -0.2071    
                9       4.979       0.1124E-01  -0.2422    
               10       3.145       0.9279E-02  -0.2840    
               11       1.986       0.7243E-02  -0.3931    

 Iteration:   30
  Subj. #:   24
  Subject: S12B                

            --- Estimation Summary---

 Data file name: data_null.csv

 Subject: S12B                

 Model:  Model Peroral con Output                                    

  Output        R-squared
  Y( 1)           1.00    

 -2LogLikelihood:   -32.826    


               Initial    Conditional
 Parameter      Value       Mean      SE (CV%)     Confidence interval (95%)

 KE            0.2297      0.2297      0.1605      [ 0.2288    ,  0.2307    ]
 KA1            1.505       1.505      0.3640      [  1.491    ,   1.519    ]
 V              27.41       27.41      0.7560E-01  [  27.36    ,   27.46    ]
 F             0.9968      0.9983       3.849      [ 0.8995    ,   1.097    ]
 KA2            2.800       2.801      0.2744      [  2.781    ,   2.820    ]


 SDslope       -.4108E-02
 SDinter       0.1000       Not estimated


  Correlation Matrix

           KE        KA1       V         F         KA2       
 KE          1.00
 KA1        -0.00      1.00
 V          -0.58      0.00      1.00
 F           0.00     -0.00      0.00      1.00
 KA2        -0.24     -0.00      0.53      0.00      1.00


  Covariance Matrix

           KE        KA1       V         F         KA2       
 KE        0.136E-06
 KA1       -.205E-08 0.300E-04
 V         -.440E-05 0.747E-07 0.429E-03
 F         0.164E-08 -.211E-06 0.165E-06 0.148E-02
 KA2       -.675E-06 -.184E-07 0.848E-04 0.183E-06 0.591E-04


 Y( 1)
  Obs.Num.   Time         Data       Model Est.     Residual     Variance
      1       0.000        0.000        0.000         0.000       0.1000E-01
      2      0.5000        17.93        17.94       -0.1220E-01   0.6916E-03
      3       1.000        20.43        20.42        0.1167E-01   0.2601E-03
      4       1.500        19.28        19.29       -0.1300E-01   0.4305E-03
      5       2.000        17.45        17.47       -0.1818E-01   0.7978E-03
      6       3.000        14.00        13.96        0.4193E-01   0.1820E-02
      7       4.000        11.12        11.10        0.2239E-01   0.2961E-02
      8       6.000        7.000        7.010       -0.9605E-02   0.5070E-02
      9       8.000        4.410        4.427       -0.1734E-01   0.6693E-02
     10       10.00        2.770        2.796       -0.2636E-01   0.7835E-02
     11       12.00        1.740        1.766       -0.2621E-01   0.8602E-02

 Y( 1) (Continued)                 Std. Dev.   Standardized
           Obs.Num.   Model Est.   Model Est.   Residual
                1       0.000        0.000        0.000    
                2       17.94       0.1851E-01  -0.4660    
                3       20.42       0.1118E-01   0.7218    
                4       19.29       0.1189E-01  -0.6278    
                5       17.47       0.1251E-01  -0.6444    
                6       13.96       0.1246E-01   0.9825    
                7       11.10       0.1258E-01   0.4113    
                8       7.010       0.1227E-01  -0.1350    
                9       4.427       0.1078E-01  -0.2121    
               10       2.796       0.8791E-02  -0.2979    
               11       1.766       0.6823E-02  -0.2827    

      ________________________________________


      ----- MLEM FINAL POPULATION PARAMETER ESTIMATES -----

 Thu Dec  6 14:58:03 2018

 Data file name: data_null.csv

 Model:  Model Peroral con Output                                    

 Number of data sets analyzed successfully:    24

 Importance Sampler with number samples/iteration:    3000

 Total number of EM iterations:   30

 Lognormal distribution option

 -2logLikelihood:   -785.334    

 Model Selection Criteria
  AIC:       -763.334    
  BIC:       -723.998    

        --- A. Population Mean & Population Standard Deviation ---  

 Parameter     Mean        %RSE         Std.Dev.   SD as CV%     %RSE
  KE          0.230       0.597         0.370E-03   0.161       0.249E+04
  KA1          1.50        3.03         0.480E-02   0.319       0.553E+04
  V            26.1        20.9          1.21        4.62        49.7    
  F           0.998        16.5         0.369E-01    3.69        133.    
  KA2          2.80        2.55         0.956E-02   0.341       0.360E+04

        --- B. Full Population Covariance of Estimated Parameters ---  

  As Covariance Matrix:

           KE        KA1       V         F         KA2       
 KE        0.137E-06
 KA1        0.00     0.231E-04
 V          0.00      0.00      1.45    
 F          0.00      0.00      0.00     0.136E-02
 KA2        0.00      0.00      0.00      0.00     0.914E-04

  As Covariance Matrix for ln(parameters):

           KE        KA1       V         F         KA2       
 KE        0.259E-05
 KA1        0.00     0.102E-04
 V          0.00      0.00     0.213E-02
 F          0.00      0.00      0.00     0.136E-02
 KA2        0.00      0.00      0.00      0.00     0.116E-04

  Standard Errors of Estimated Covariance Matrix for ln(parameters):

           KE        KA1       V         F         KA2       
 KE         0.13E-03
 KA1        -1.0      0.11E-02
 V          -1.0      -1.0      0.22E-02
 F          -1.0      -1.0      -1.0      0.35E-02
 KA2        -1.0      -1.0      -1.0      -1.0      0.84E-03

        --- D. Error Variance Model Parameters ---  

Parameter     Estimate    %RSE
  SDslope    -0.411E-02   17.3    
  SDinter     0.100      Not estimated

        --- F. Population Mean and Covariance (ADAPT Format) ---  

       Pmean(  1) =  0.2297458         ! KE        
       Pmean(  2) =   1.504980         ! KA1       
       Pmean(  3) =   26.10049         ! V         
       Pmean(  4) =  0.9982720         ! F         
       Pmean(  5) =   2.801888         ! KA2       
 
       Pcov(  1,  1) =  0.1368716E-06  ! KE         & KE        
       Pcov(  2,  1) =   0.000000      ! KA1        & KE        
       Pcov(  2,  2) =  0.2305349E-04  ! KA1        & KA1       
       Pcov(  3,  1) =   0.000000      ! V          & KE        
       Pcov(  3,  2) =   0.000000      ! V          & KA1       
       Pcov(  3,  3) =   1.453373      ! V          & V         
       Pcov(  4,  1) =   0.000000      ! F          & KE        
       Pcov(  4,  2) =   0.000000      ! F          & KA1       
       Pcov(  4,  3) =   0.000000      ! F          & V         
       Pcov(  4,  4) =  0.1358391E-02  ! F          & F         
       Pcov(  5,  1) =   0.000000      ! KA2        & KE        
       Pcov(  5,  2) =   0.000000      ! KA2        & KA1       
       Pcov(  5,  3) =   0.000000      ! KA2        & V         
       Pcov(  5,  4) =   0.000000      ! KA2        & F         
       Pcov(  5,  5) =  0.9137974E-04  ! KA2        & KA2       

      ________________________________________


 List of Files Created

  Record of program run and all results:
    D.run
  Summary of population estimates at each iteration:
    DIT.csv
  Individual subject estimates at final iteration:
    DIND.csv
  Table of predictions and residuals for each subject:
    DRSD.csv
  Information for plotting model predictions for each subject:
    DPLT.csv
  Composite residual and prediction vs measurements graphs and
  individual subject model prediction and measurement vs time graphs:
    D.eps
  Command file for subsequent Batch runs:
    D.aci


      ________________________________________


  ADAPT 5  MLEM -- MAXIMUM LIKELIHOOD EM POP. EST.  Thu Dec  6 14:58:05 2018

